// generated by newgenasym  Thu Jun 16 10:54:54 2022


module adi_adclk914 (d, \d# , e_pad, nc, q, \q# , vcc, vee, vref, vt);
    inout d;
    inout \d# ;
    inout e_pad;
    inout [5:0] nc;
    inout q;
    inout \q# ;
    inout [1:0] vcc;
    inout [1:0] vee;
    inout vref;
    inout vt;


    initial
        begin
        end

endmodule
