// generated by newgenasym  Thu Dec 20 18:16:25 2018


module spx_sp3077een (a, b, d, gnd, r, vcc, y, z);
    output a;
    output b;
    input d;
    input gnd;
    input r;
    input vcc;
    output y;
    output z;


    initial
        begin
        end

endmodule
