-- generated by newgenasym Thu Dec 20 18:16:25 2018

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity spx_SP3077EEN is
    port (    
	A:         OUT    STD_LOGIC;    
	B:         OUT    STD_LOGIC;    
	D:         IN     STD_LOGIC;    
	GND:       IN     STD_LOGIC;    
	R:         IN     STD_LOGIC;    
	VCC:       IN     STD_LOGIC;    
	Y:         OUT    STD_LOGIC;    
	Z:         OUT    STD_LOGIC);
end spx_SP3077EEN;
