-- generated by newgenasym Tue Aug 17 19:35:23 2021

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity esd_uni is
    port (    
	\1\:       INOUT  STD_LOGIC;    
	\2\:       INOUT  STD_LOGIC);
end esd_uni;
