// generated by newgenasym  Tue Jan 10 09:24:16 2012


module ti_tps51200drc (en, gnd, pgnd, pgood, refin, refout, thermal, vin, vldoin, vo,
        vosns);
    input en;
    input gnd;
    input pgnd;
    output pgood;
    input refin;
    output refout;
    input thermal;
    input vin;
    input vldoin;
    input vo;
    input vosns;


    initial
        begin
        end

endmodule
