-- generated by newgenasym Tue Jan 10 09:24:16 2012

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity ti_tps51200drc is
    port (    
	EN:        IN     STD_LOGIC;    
	GND:       IN     STD_LOGIC;    
	PGND:      IN     STD_LOGIC;    
	PGOOD:     OUT    STD_LOGIC;    
	REFIN:     IN     STD_LOGIC;    
	REFOUT:    OUT    STD_LOGIC;    
	THERMAL:   IN     STD_LOGIC;    
	VIN:       IN     STD_LOGIC;    
	VLDOIN:    IN     STD_LOGIC;    
	VO:        IN     STD_LOGIC;    
	VOSNS:     IN     STD_LOGIC);
end ti_tps51200drc;
