-- generated by newgenasym Thu Apr 23 13:25:33 2015

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity rf_conn_ufl_smt is
    port (    
	GND:       IN     STD_LOGIC_VECTOR (1 DOWNTO 0);    
	RF:        IN     STD_LOGIC);
end rf_conn_ufl_smt;
