// generated by newgenasym  Wed Jul 27 14:47:11 2022


module au5325 (a0_csb, a1_sdo, fdec, finc, gnd, i2c_sel, in0, in0b, in1,
        in1b, in2, in2b, in3, in3b, in_sel0, in_sel1, intrb, io14,
        io15, io3, lolb, nc_1, nc_2, nc_3, oeb, out0bn_d, out0bp_d,
        out0n_c_d, out0p_c_d, out0tn_a, out0tp_a, out1n_c_d,
        out1p_c_d, out2n_b_c, out2p_b_c, out3n_b_c, out3p_b_c,
        out4n_b_c, out4p_b_c, out5n_b_c, out5p_b_c, out6n_a_b,
        out6p_a_b, out7n_a_b, out7p_a_b, rstb, sclk, sda_sdio, vdd,
        vdda, vddo0, vddo0b, vddo0t, vddo1, vddo2, vddo3, vddo4,
        vddo5, vddo6, vddo7, x1, x2, xa, xb);
    inout a0_csb;
    inout a1_sdo;
    inout fdec;
    inout finc;
    inout gnd;
    inout i2c_sel;
    inout in0;
    inout in0b;
    inout in1;
    inout in1b;
    inout in2;
    inout in2b;
    inout in3;
    inout in3b;
    inout in_sel0;
    inout in_sel1;
    inout intrb;
    inout io14;
    inout io15;
    inout io3;
    inout lolb;
    inout nc_1;
    inout nc_2;
    inout nc_3;
    inout oeb;
    inout out0bn_d;
    inout out0bp_d;
    inout out0n_c_d;
    inout out0p_c_d;
    inout out0tn_a;
    inout out0tp_a;
    inout out1n_c_d;
    inout out1p_c_d;
    inout out2n_b_c;
    inout out2p_b_c;
    inout out3n_b_c;
    inout out3p_b_c;
    inout out4n_b_c;
    inout out4p_b_c;
    inout out5n_b_c;
    inout out5p_b_c;
    inout out6n_a_b;
    inout out6p_a_b;
    inout out7n_a_b;
    inout out7p_a_b;
    inout rstb;
    inout sclk;
    inout sda_sdio;
    inout [1:0] vdd;
    inout vdda;
    inout vddo0;
    inout vddo0b;
    inout vddo0t;
    inout vddo1;
    inout vddo2;
    inout vddo3;
    inout vddo4;
    inout vddo5;
    inout vddo6;
    inout vddo7;
    inout x1;
    inout x2;
    inout xa;
    inout xb;


    initial
        begin
        end

endmodule
