// generated by newgenasym  Thu Mar 18 17:11:25 2021


module mc_lfcg_xxxx (gnd, intput, \output );
    inout [5:0] gnd;
    inout intput;
    inout \output ;


    initial
        begin
        end

endmodule
