-- generated by newgenasym Thu Mar 18 17:11:25 2021

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity mc_lfcg_xxxx is
    port (    
	GND:       INOUT  STD_LOGIC_VECTOR (5 DOWNTO 0);    
	INTPUT:    INOUT  STD_LOGIC;    
	OUTPUT:    INOUT  STD_LOGIC);
end mc_lfcg_xxxx;
