-- generated by newgenasym Tue Oct 30 20:00:54 2018

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity xilinx_spiflash_8p is
    port (    
	\cs#\:     IN     STD_LOGIC;    
	EPAD:      INOUT  STD_LOGIC;    
	\hold#_io3\: OUT    STD_LOGIC;    
	SCK:       OUT    STD_LOGIC;    
	SI_IO0:    OUT    STD_LOGIC;    
	SO_IO1:    IN     STD_LOGIC;    
	VCC:       OUT    STD_LOGIC;    
	VSS:       IN     STD_LOGIC;    
	\wp#_io2\: IN     STD_LOGIC);
end xilinx_spiflash_8p;
