// generated by newgenasym  Mon May 23 14:28:54 2022


module mc_tc1_33_75g2 (not_used, pri, pri_dot, sec, sec_dot);
    inout not_used;
    inout pri;
    inout pri_dot;
    inout sec;
    inout sec_dot;


    initial
        begin
        end

endmodule
