// generated by newgenasym  Mon Jul 04 20:59:13 2022


module adi_ltm4638 (clkout, compa, compb, fb, freq, gnd, intvcc, \mode/clkin ,
        pgood, phmode, run, sw, \track/ss , \tsense+ , \tsense- , vin,
        \vosns+ , \vosns- , vout);
    inout clkout;
    inout compa;
    inout compb;
    inout fb;
    inout freq;
    inout [17:0] gnd;
    inout intvcc;
    inout \mode/clkin ;
    inout pgood;
    inout phmode;
    inout run;
    inout sw;
    inout \track/ss ;
    inout \tsense+ ;
    inout \tsense- ;
    inout [5:0] vin;
    inout \vosns+ ;
    inout \vosns- ;
    inout [8:0] vout;


    initial
        begin
        end

endmodule
