-- generated by newgenasym Mon Jul 04 20:59:13 2022

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity adi_ltm4638 is
    port (    
	CLKOUT:    INOUT  STD_LOGIC;    
	COMPA:     INOUT  STD_LOGIC;    
	COMPB:     INOUT  STD_LOGIC;    
	FB:        INOUT  STD_LOGIC;    
	FREQ:      INOUT  STD_LOGIC;    
	GND:       INOUT  STD_LOGIC_VECTOR (17 DOWNTO 0);    
	INTVCC:    INOUT  STD_LOGIC;    
	\mode/clkin\: INOUT  STD_LOGIC;    
	PGOOD:     INOUT  STD_LOGIC;    
	PHMODE:    INOUT  STD_LOGIC;    
	RUN:       INOUT  STD_LOGIC;    
	SW:        INOUT  STD_LOGIC;    
	\track/ss\: INOUT  STD_LOGIC;    
	\tsense+\: INOUT  STD_LOGIC;    
	\tsense-\: INOUT  STD_LOGIC;    
	VIN:       INOUT  STD_LOGIC_VECTOR (5 DOWNTO 0);    
	\vosns+\:  INOUT  STD_LOGIC;    
	\vosns-\:  INOUT  STD_LOGIC;    
	VOUT:      INOUT  STD_LOGIC_VECTOR (8 DOWNTO 0));
end adi_ltm4638;
