-- generated by newgenasym Fri Apr 02 16:40:03 2021

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity mc_dvga2_33a is
    port (    
	C0P5:      INOUT  STD_LOGIC;    
	C1:        INOUT  STD_LOGIC;    
	C16:       INOUT  STD_LOGIC;    
	C2:        INOUT  STD_LOGIC;    
	C4:        INOUT  STD_LOGIC;    
	C8:        INOUT  STD_LOGIC;    
	CLOCK:     INOUT  STD_LOGIC;    
	DATA:      INOUT  STD_LOGIC;    
	GND_1:     INOUT  STD_LOGIC;    
	GND_2:     INOUT  STD_LOGIC;    
	LE:        INOUT  STD_LOGIC;    
	NC:        INOUT  STD_LOGIC_VECTOR (13 DOWNTO 0);    
	NC_1:      INOUT  STD_LOGIC;    
	NC_2:      INOUT  STD_LOGIC;    
	RF_JUMP_IN: INOUT  STD_LOGIC;    
	RF_JUMP_OUT: INOUT  STD_LOGIC;    
	RFIN:      INOUT  STD_LOGIC;    
	\rfout/vd2\: INOUT  STD_LOGIC;    
	VD1_0:     INOUT  STD_LOGIC;    
	VD1_1:     INOUT  STD_LOGIC);
end mc_dvga2_33a;
