// generated by newgenasym  Tue Oct 11 14:55:00 2016


module ns_lm25069pmme_2 (gate, gnd, out, ovlo, pgd, pwr, sense, timer, \uvlo/en , vin);
    inout gate;
    input gnd;
    inout out;
    inout ovlo;
    input pgd;
    input pwr;
    input sense;
    inout timer;
    inout \uvlo/en ;
    input vin;


    initial
        begin
        end

endmodule
