-- generated by newgenasym Tue Oct 11 14:55:00 2016

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity ns_lm25069pmme_2 is
    port (    
	GATE:      INOUT  STD_LOGIC;    
	GND:       IN     STD_LOGIC;    
	\out\:     INOUT  STD_LOGIC;    
	OVLO:      INOUT  STD_LOGIC;    
	PGD:       IN     STD_LOGIC;    
	PWR:       IN     STD_LOGIC;    
	SENSE:     IN     STD_LOGIC;    
	TIMER:     INOUT  STD_LOGIC;    
	\uvlo/en\: INOUT  STD_LOGIC;    
	VIN:       IN     STD_LOGIC);
end ns_lm25069pmme_2;
