// generated by newgenasym  Mon Jun 13 17:53:55 2022


module qorvo_rfsw1012 (ctrl, e_pad, en, gnd, rf1, rf2, rfc, vdd);
    inout ctrl;
    inout e_pad;
    inout en;
    inout [5:0] gnd;
    inout rf1;
    inout rf2;
    inout rfc;
    inout vdd;


    initial
        begin
        end

endmodule
