-- generated by newgenasym Mon Oct 21 14:20:38 2019

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity mur_sf1186b_3 is
    port (    
	GND_1:     INOUT  STD_LOGIC;    
	GND_3:     INOUT  STD_LOGIC;    
	GND_4:     INOUT  STD_LOGIC;    
	GND_6:     INOUT  STD_LOGIC;    
	INPUT:     INOUT  STD_LOGIC;    
	OUTPUT:    INOUT  STD_LOGIC);
end mur_sf1186b_3;
