// generated by newgenasym  Fri Mar 24 11:17:40 2017


module ttn_ox_xxxxx (gnd, \nc/3_state , \output , vdd);
    input gnd;
    inout \nc/3_state ;
    output \output ;
    input vdd;


    initial
        begin
        end

endmodule
