// generated by newgenasym  Sat Dec 28 13:41:00 2019


module skylab_skg09d (extint_5, gnd_1, gnd_10, gnd_12, gpio0_18, gpio14_16,
        gpio15_17, lna_en_13, nc_7, pps_4, reset_9, rf_in_11, rxd_3,
        txd_2, v_bckp_6, vant_15, vcc_8, vcc_rf_14);
    inout extint_5;
    inout gnd_1;
    inout gnd_10;
    inout gnd_12;
    inout gpio0_18;
    inout gpio14_16;
    inout gpio15_17;
    inout lna_en_13;
    inout nc_7;
    inout pps_4;
    inout reset_9;
    inout rf_in_11;
    inout rxd_3;
    inout txd_2;
    inout v_bckp_6;
    inout vant_15;
    inout vcc_8;
    inout vcc_rf_14;


    initial
        begin
        end

endmodule
