-- generated by newgenasym Wed Jan 17 09:41:33 2007

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity mur_blm18 is
    port (    
	P1:        INOUT  STD_LOGIC;    
	P2:        INOUT  STD_LOGIC);
end mur_blm18;
