-- generated by newgenasym Mon Jan 08 13:07:57 2018

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity ttn_xx_xxxx is
    port (    
	\1\:       INOUT  STD_LOGIC;    
	\2\:       INOUT  STD_LOGIC;    
	\3\:       INOUT  STD_LOGIC;    
	\4\:       INOUT  STD_LOGIC);
end ttn_xx_xxxx;
