-- generated by newgenasym Mon Nov 10 16:22:46 2014

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity r_s is
    port (    
	A0:        INOUT  STD_LOGIC;    
	B0:        INOUT  STD_LOGIC);
end r_s;
