// generated by newgenasym  Tue Jan 05 09:08:39 2016


module \ltm4644iy#pbf  (clkin, clkout, comp1, comp2, comp3, comp4, fb1, fb2, fb3, fb4,
        gnd, intvcc1, intvcc2, intvcc3, intvcc4, mode1, mode2, mode3,
        mode4, pgood1, pgood2, pgood3, pgood4, run1, run2, run3, run4,
        sgnd, svin1, svin2, svin3, svin4, temp, \track/ss1 , \track/ss2 ,
        \track/ss3 , \track/ss4 , vin1, vin2, vin3, vin4, vout1, vout2,
        vout3, vout4);
    inout clkin;
    inout clkout;
    inout comp1;
    inout comp2;
    inout comp3;
    inout comp4;
    inout fb1;
    inout fb2;
    inout fb3;
    inout fb4;
    inout [21:1] gnd;
    inout intvcc1;
    inout intvcc2;
    inout intvcc3;
    inout intvcc4;
    inout mode1;
    inout mode2;
    inout mode3;
    inout mode4;
    inout pgood1;
    inout pgood2;
    inout pgood3;
    inout pgood4;
    inout run1;
    inout run2;
    inout run3;
    inout run4;
    inout sgnd;
    inout svin1;
    inout svin2;
    inout svin3;
    inout svin4;
    inout temp;
    inout \track/ss1 ;
    inout \track/ss2 ;
    inout \track/ss3 ;
    inout \track/ss4 ;
    inout [2:1] vin1;
    inout [2:1] vin2;
    inout [2:1] vin3;
    inout [2:1] vin4;
    inout [3:1] vout1;
    inout [3:1] vout2;
    inout [3:1] vout3;
    inout [3:1] vout4;


    initial
        begin
        end

endmodule
