-- generated by newgenasym Sat May 02 13:41:22 2020

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity ad_adp1763 is
    port (    
	EN:        INOUT  STD_LOGIC;    
	EPAD:      INOUT  STD_LOGIC;    
	GND:       INOUT  STD_LOGIC;    
	PG:        INOUT  STD_LOGIC;    
	REFCAP:    INOUT  STD_LOGIC;    
	SENSE:     INOUT  STD_LOGIC;    
	SS:        INOUT  STD_LOGIC;    
	VADJ:      INOUT  STD_LOGIC;    
	VIN:       INOUT  STD_LOGIC_VECTOR (3 DOWNTO 0);    
	VOUT:      INOUT  STD_LOGIC_VECTOR (3 DOWNTO 0);    
	VREG:      INOUT  STD_LOGIC);
end ad_adp1763;
