// generated by newgenasym  Tue May 31 14:14:33 2022


module adi_ad9689 (agnd_b10, agnd_b5, agnd_c10, agnd_c11, agnd_c4, agnd_c5,
        agnd_c_a6, agnd_c_a9, agnd_c_b6, agnd_c_b7, agnd_c_b8,
        agnd_c_b9, agnd_c_c6, agnd_c_c7, agnd_c_c8, agnd_c_c9,
        agnd_c_d7, agnd_c_d8, agnd_d10, agnd_d11, agnd_d12,
        agnd_d13, agnd_d2, agnd_d3, agnd_d4, agnd_d5, agnd_d6,
        agnd_d9, agnd_e10, agnd_e11, agnd_e12, agnd_e13, agnd_e2,
        agnd_e3, agnd_e4, agnd_e5, agnd_e9, agnd_f10, agnd_f11,
        agnd_f12, agnd_f13, agnd_f2, agnd_f3, agnd_f4, agnd_f5,
        agnd_f6, agnd_f9, agnd_g10, agnd_g11, agnd_g12, agnd_g13,
        agnd_g2, agnd_g3, agnd_g4, agnd_g5, agnd_g6, agnd_g7,
        agnd_g8, agnd_g9, agnd_h1, agnd_h11, agnd_h12, agnd_h13,
        agnd_h14, agnd_h2, agnd_h3, agnd_h4, agnd_h5, agnd_h6,
        agnd_h7, agnd_h8, agnd_h9, agnd_i_k1, agnd_i_k10,
        agnd_i_k11, agnd_i_k12, agnd_i_k13, agnd_i_k14, agnd_i_k2,
        agnd_i_k3, agnd_i_k4, agnd_i_k5, agnd_i_k6, agnd_i_k7,
        agnd_i_k8, agnd_i_k9, agnd_j1, agnd_j10, agnd_j11,
        agnd_j12, agnd_j13, agnd_j14, agnd_j2, agnd_j3, agnd_j4,
        agnd_j5, agnd_j6, agnd_j7, agnd_j8, agnd_j9, agnd_s_e6,
        agnd_s_e8, avdd1_a12, avdd1_a3, avdd1_b12, avdd1_b3,
        avdd1_c12, avdd1_c3, avdd1_c_a10, avdd1_c_a11, avdd1_c_a4,
        avdd1_c_a5, avdd1_c_b11, avdd1_c_b4, avdd1_sr, avdd2_a1,
        avdd2_a13, avdd2_a14, avdd2_a2, avdd2_b1, avdd2_b13,
        avdd2_b14, avdd2_b2, avdd2_c1, avdd2_c13, avdd2_c14,
        avdd2_c2, avdd3_d1, avdd3_d14, avdd3_g1, avdd3_g14, \clk+ ,
        \clk- , csb, dgnd_l1, dgnd_l12, dgnd_l13, dgnd_l14, dgnd_m1,
        dgnd_m2, drgnd_m10, drgnd_m12, drgnd_m3, drgnd_m4,
        drgnd_m9, drgnd_n12, drgnd_n3, drgnd_p12, drgnd_p3,
        drvdd1_m11, drvdd1_m5, drvdd1_m6, drvdd1_m7, drvdd1_m8,
        drvdd2_m13, dvdd_m14, dvdd_n1, dvdd_n14, dvdd_n2, dvdd_p1,
        dvdd_p14, dvdd_p2, \fd_a/gpio_a0 , \fd_b/gpio_b0 , gpio_a1,
        gpio_b1, \pdwn/stby , sclk, sdio, \serdout0+ , \serdout0- ,
        \serdout1+ , \serdout1- , \serdout2+ , \serdout2- , \serdout3+ ,
        \serdout3- , \serdout4+ , \serdout4- , \serdout5+ , \serdout5- ,
        \serdout6+ , \serdout6- , \serdout7+ , \serdout7- , spivdd_l10,
        spivdd_l3, \syncinb+ , \syncinb- , \sysref+ , \sysref- , \vin+a ,
        \vin+b , \vin-a , \vin-b , vref);
    inout agnd_b10;
    inout agnd_b5;
    inout agnd_c10;
    inout agnd_c11;
    inout agnd_c4;
    inout agnd_c5;
    inout agnd_c_a6;
    inout agnd_c_a9;
    inout agnd_c_b6;
    inout agnd_c_b7;
    inout agnd_c_b8;
    inout agnd_c_b9;
    inout agnd_c_c6;
    inout agnd_c_c7;
    inout agnd_c_c8;
    inout agnd_c_c9;
    inout agnd_c_d7;
    inout agnd_c_d8;
    inout agnd_d10;
    inout agnd_d11;
    inout agnd_d12;
    inout agnd_d13;
    inout agnd_d2;
    inout agnd_d3;
    inout agnd_d4;
    inout agnd_d5;
    inout agnd_d6;
    inout agnd_d9;
    inout agnd_e10;
    inout agnd_e11;
    inout agnd_e12;
    inout agnd_e13;
    inout agnd_e2;
    inout agnd_e3;
    inout agnd_e4;
    inout agnd_e5;
    inout agnd_e9;
    inout agnd_f10;
    inout agnd_f11;
    inout agnd_f12;
    inout agnd_f13;
    inout agnd_f2;
    inout agnd_f3;
    inout agnd_f4;
    inout agnd_f5;
    inout agnd_f6;
    inout agnd_f9;
    inout agnd_g10;
    inout agnd_g11;
    inout agnd_g12;
    inout agnd_g13;
    inout agnd_g2;
    inout agnd_g3;
    inout agnd_g4;
    inout agnd_g5;
    inout agnd_g6;
    inout agnd_g7;
    inout agnd_g8;
    inout agnd_g9;
    inout agnd_h1;
    inout agnd_h11;
    inout agnd_h12;
    inout agnd_h13;
    inout agnd_h14;
    inout agnd_h2;
    inout agnd_h3;
    inout agnd_h4;
    inout agnd_h5;
    inout agnd_h6;
    inout agnd_h7;
    inout agnd_h8;
    inout agnd_h9;
    inout agnd_i_k1;
    inout agnd_i_k10;
    inout agnd_i_k11;
    inout agnd_i_k12;
    inout agnd_i_k13;
    inout agnd_i_k14;
    inout agnd_i_k2;
    inout agnd_i_k3;
    inout agnd_i_k4;
    inout agnd_i_k5;
    inout agnd_i_k6;
    inout agnd_i_k7;
    inout agnd_i_k8;
    inout agnd_i_k9;
    inout agnd_j1;
    inout agnd_j10;
    inout agnd_j11;
    inout agnd_j12;
    inout agnd_j13;
    inout agnd_j14;
    inout agnd_j2;
    inout agnd_j3;
    inout agnd_j4;
    inout agnd_j5;
    inout agnd_j6;
    inout agnd_j7;
    inout agnd_j8;
    inout agnd_j9;
    inout agnd_s_e6;
    inout agnd_s_e8;
    inout avdd1_a12;
    inout avdd1_a3;
    inout avdd1_b12;
    inout avdd1_b3;
    inout avdd1_c12;
    inout avdd1_c3;
    inout avdd1_c_a10;
    inout avdd1_c_a11;
    inout avdd1_c_a4;
    inout avdd1_c_a5;
    inout avdd1_c_b11;
    inout avdd1_c_b4;
    inout avdd1_sr;
    inout avdd2_a1;
    inout avdd2_a13;
    inout avdd2_a14;
    inout avdd2_a2;
    inout avdd2_b1;
    inout avdd2_b13;
    inout avdd2_b14;
    inout avdd2_b2;
    inout avdd2_c1;
    inout avdd2_c13;
    inout avdd2_c14;
    inout avdd2_c2;
    inout avdd3_d1;
    inout avdd3_d14;
    inout avdd3_g1;
    inout avdd3_g14;
    inout \clk+ ;
    inout \clk- ;
    inout csb;
    inout dgnd_l1;
    inout dgnd_l12;
    inout dgnd_l13;
    inout dgnd_l14;
    inout dgnd_m1;
    inout dgnd_m2;
    inout drgnd_m10;
    inout drgnd_m12;
    inout drgnd_m3;
    inout drgnd_m4;
    inout drgnd_m9;
    inout drgnd_n12;
    inout drgnd_n3;
    inout drgnd_p12;
    inout drgnd_p3;
    inout drvdd1_m11;
    inout drvdd1_m5;
    inout drvdd1_m6;
    inout drvdd1_m7;
    inout drvdd1_m8;
    inout drvdd2_m13;
    inout dvdd_m14;
    inout dvdd_n1;
    inout dvdd_n14;
    inout dvdd_n2;
    inout dvdd_p1;
    inout dvdd_p14;
    inout dvdd_p2;
    inout \fd_a/gpio_a0 ;
    inout \fd_b/gpio_b0 ;
    inout gpio_a1;
    inout gpio_b1;
    inout \pdwn/stby ;
    inout sclk;
    inout sdio;
    inout \serdout0+ ;
    inout \serdout0- ;
    inout \serdout1+ ;
    inout \serdout1- ;
    inout \serdout2+ ;
    inout \serdout2- ;
    inout \serdout3+ ;
    inout \serdout3- ;
    inout \serdout4+ ;
    inout \serdout4- ;
    inout \serdout5+ ;
    inout \serdout5- ;
    inout \serdout6+ ;
    inout \serdout6- ;
    inout \serdout7+ ;
    inout \serdout7- ;
    inout spivdd_l10;
    inout spivdd_l3;
    inout \syncinb+ ;
    inout \syncinb- ;
    inout \sysref+ ;
    inout \sysref- ;
    inout \vin+a ;
    inout \vin+b ;
    inout \vin-a ;
    inout \vin-b ;
    inout vref;


    initial
        begin
        end

endmodule
