-- generated by newgenasym Mon Nov 12 21:49:22 2018

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity will_mos_n is
    port (    
	\1\:       INOUT  STD_LOGIC;    
	\2\:       INOUT  STD_LOGIC;    
	\3\:       INOUT  STD_LOGIC);
end will_mos_n;
