-- generated by newgenasym Mon Nov 10 14:51:51 2014

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity r is
    port (    
	A0:        INOUT  STD_LOGIC;    
	B0:        INOUT  STD_LOGIC);
end r;
