// generated by newgenasym  Mon Jun 06 11:15:05 2022


module spx_sp3078een (a, b, de, di, gnd, \re# , ro, vcc);
    output a;
    output b;
    input de;
    input di;
    output gnd;
    input \re# ;
    input ro;
    output vcc;


    initial
        begin
        end

endmodule
