-- generated by newgenasym Mon Jun 06 11:15:05 2022

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity spx_sp3078een is
    port (    
	A:         OUT    STD_LOGIC;    
	B:         OUT    STD_LOGIC;    
	DE:        IN     STD_LOGIC;    
	DI:        IN     STD_LOGIC;    
	GND:       OUT    STD_LOGIC;    
	\re#\:     IN     STD_LOGIC;    
	RO:        IN     STD_LOGIC;    
	VCC:       OUT    STD_LOGIC);
end spx_sp3078een;
