-- generated by newgenasym Sat May 26 14:01:45 2018

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity c is
    port (    
	A0:        INOUT  STD_LOGIC;    
	B0:        INOUT  STD_LOGIC);
end c;
