-- generated by newgenasym Sun Jan 06 15:22:43 2019

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity dp_o11f_o11h is
    port (    
	GND_3:     INOUT  STD_LOGIC;    
	NC_2:      INOUT  STD_LOGIC;    
	NC_5:      INOUT  STD_LOGIC;    
	OUTPUT_4:  INOUT  STD_LOGIC;    
	VC_1:      INOUT  STD_LOGIC;    
	VCC_6:     INOUT  STD_LOGIC);
end dp_o11f_o11h;
