// generated by newgenasym  Mon May 16 14:21:46 2022


module xilinx_xcku115_2flva1517i (cclk_0, cfgbvs_0, d00_mosi_0, d01_din_0, d02_0, d03_0,
        done_0, dxn, dxp, gnd, gndadc, init_b_0,
        io_l10n_t1u_n7_qbc_ad4n_24, io_l10n_t1u_n7_qbc_ad4n_25,
        io_l10n_t1u_n7_qbc_ad4n_44, io_l10n_t1u_n7_qbc_ad4n_45,
        io_l10n_t1u_n7_qbc_ad4n_46, io_l10n_t1u_n7_qbc_ad4n_47,
        io_l10n_t1u_n7_qbc_ad4n_48, io_l10n_t1u_n7_qbc_ad4n_64,
        io_l10n_t1u_n7_qbc_ad4n_66, io_l10n_t1u_n7_qbc_ad4n_67,
        io_l10n_t1u_n7_qbc_ad4n_68,
        io_l10n_t1u_n7_qbc_ad4n_a13_d29_65,
        io_l10p_t1u_n6_qbc_ad4p_24, io_l10p_t1u_n6_qbc_ad4p_25,
        io_l10p_t1u_n6_qbc_ad4p_44, io_l10p_t1u_n6_qbc_ad4p_45,
        io_l10p_t1u_n6_qbc_ad4p_46, io_l10p_t1u_n6_qbc_ad4p_47,
        io_l10p_t1u_n6_qbc_ad4p_48, io_l10p_t1u_n6_qbc_ad4p_64,
        io_l10p_t1u_n6_qbc_ad4p_66, io_l10p_t1u_n6_qbc_ad4p_67,
        io_l10p_t1u_n6_qbc_ad4p_68,
        io_l10p_t1u_n6_qbc_ad4p_a12_d28_65,
        io_l11n_t1u_n9_gc_24, io_l11n_t1u_n9_gc_25,
        io_l11n_t1u_n9_gc_44, io_l11n_t1u_n9_gc_45,
        io_l11n_t1u_n9_gc_46, io_l11n_t1u_n9_gc_47,
        io_l11n_t1u_n9_gc_48, io_l11n_t1u_n9_gc_64,
        io_l11n_t1u_n9_gc_66, io_l11n_t1u_n9_gc_67,
        io_l11n_t1u_n9_gc_68, io_l11n_t1u_n9_gc_a11_d27_65,
        io_l11p_t1u_n8_gc_24, io_l11p_t1u_n8_gc_25,
        io_l11p_t1u_n8_gc_44, io_l11p_t1u_n8_gc_45,
        io_l11p_t1u_n8_gc_46, io_l11p_t1u_n8_gc_47,
        io_l11p_t1u_n8_gc_48, io_l11p_t1u_n8_gc_64,
        io_l11p_t1u_n8_gc_66, io_l11p_t1u_n8_gc_67,
        io_l11p_t1u_n8_gc_68, io_l11p_t1u_n8_gc_a10_d26_65,
        io_l12n_t1u_n11_gc_24, io_l12n_t1u_n11_gc_25,
        io_l12n_t1u_n11_gc_44, io_l12n_t1u_n11_gc_45,
        io_l12n_t1u_n11_gc_46, io_l12n_t1u_n11_gc_47,
        io_l12n_t1u_n11_gc_48, io_l12n_t1u_n11_gc_64,
        io_l12n_t1u_n11_gc_66, io_l12n_t1u_n11_gc_67,
        io_l12n_t1u_n11_gc_68, io_l12n_t1u_n11_gc_a09_d25_65,
        io_l12p_t1u_n10_gc_24, io_l12p_t1u_n10_gc_25,
        io_l12p_t1u_n10_gc_44, io_l12p_t1u_n10_gc_45,
        io_l12p_t1u_n10_gc_46, io_l12p_t1u_n10_gc_47,
        io_l12p_t1u_n10_gc_48, io_l12p_t1u_n10_gc_64,
        io_l12p_t1u_n10_gc_66, io_l12p_t1u_n10_gc_67,
        io_l12p_t1u_n10_gc_68, io_l12p_t1u_n10_gc_a08_d24_65,
        io_l13n_t2l_n1_gc_qbc_24, io_l13n_t2l_n1_gc_qbc_25,
        io_l13n_t2l_n1_gc_qbc_44, io_l13n_t2l_n1_gc_qbc_45,
        io_l13n_t2l_n1_gc_qbc_46, io_l13n_t2l_n1_gc_qbc_47,
        io_l13n_t2l_n1_gc_qbc_48, io_l13n_t2l_n1_gc_qbc_64,
        io_l13n_t2l_n1_gc_qbc_66, io_l13n_t2l_n1_gc_qbc_67,
        io_l13n_t2l_n1_gc_qbc_68,
        io_l13n_t2l_n1_gc_qbc_a07_d23_65,
        io_l13p_t2l_n0_gc_qbc_24, io_l13p_t2l_n0_gc_qbc_25,
        io_l13p_t2l_n0_gc_qbc_44, io_l13p_t2l_n0_gc_qbc_45,
        io_l13p_t2l_n0_gc_qbc_46, io_l13p_t2l_n0_gc_qbc_47,
        io_l13p_t2l_n0_gc_qbc_48, io_l13p_t2l_n0_gc_qbc_64,
        io_l13p_t2l_n0_gc_qbc_66, io_l13p_t2l_n0_gc_qbc_67,
        io_l13p_t2l_n0_gc_qbc_68,
        io_l13p_t2l_n0_gc_qbc_a06_d22_65, io_l14n_t2l_n3_gc_24,
        io_l14n_t2l_n3_gc_25, io_l14n_t2l_n3_gc_44,
        io_l14n_t2l_n3_gc_45, io_l14n_t2l_n3_gc_46,
        io_l14n_t2l_n3_gc_47, io_l14n_t2l_n3_gc_48,
        io_l14n_t2l_n3_gc_64, io_l14n_t2l_n3_gc_66,
        io_l14n_t2l_n3_gc_67, io_l14n_t2l_n3_gc_68,
        io_l14n_t2l_n3_gc_a05_d21_65, io_l14p_t2l_n2_gc_24,
        io_l14p_t2l_n2_gc_25, io_l14p_t2l_n2_gc_44,
        io_l14p_t2l_n2_gc_45, io_l14p_t2l_n2_gc_46,
        io_l14p_t2l_n2_gc_47, io_l14p_t2l_n2_gc_48,
        io_l14p_t2l_n2_gc_64, io_l14p_t2l_n2_gc_66,
        io_l14p_t2l_n2_gc_67, io_l14p_t2l_n2_gc_68,
        io_l14p_t2l_n2_gc_a04_d20_65, io_l15n_t2l_n5_ad11n_24,
        io_l15n_t2l_n5_ad11n_25, io_l15n_t2l_n5_ad11n_44,
        io_l15n_t2l_n5_ad11n_45, io_l15n_t2l_n5_ad11n_46,
        io_l15n_t2l_n5_ad11n_47, io_l15n_t2l_n5_ad11n_48,
        io_l15n_t2l_n5_ad11n_64, io_l15n_t2l_n5_ad11n_66,
        io_l15n_t2l_n5_ad11n_67, io_l15n_t2l_n5_ad11n_68,
        io_l15n_t2l_n5_ad11n_a03_d19_65,
        io_l15p_t2l_n4_ad11p_24, io_l15p_t2l_n4_ad11p_25,
        io_l15p_t2l_n4_ad11p_44, io_l15p_t2l_n4_ad11p_45,
        io_l15p_t2l_n4_ad11p_46, io_l15p_t2l_n4_ad11p_47,
        io_l15p_t2l_n4_ad11p_48, io_l15p_t2l_n4_ad11p_64,
        io_l15p_t2l_n4_ad11p_66, io_l15p_t2l_n4_ad11p_67,
        io_l15p_t2l_n4_ad11p_68,
        io_l15p_t2l_n4_ad11p_a02_d18_65,
        io_l16n_t2u_n7_qbc_ad3n_24, io_l16n_t2u_n7_qbc_ad3n_25,
        io_l16n_t2u_n7_qbc_ad3n_44, io_l16n_t2u_n7_qbc_ad3n_45,
        io_l16n_t2u_n7_qbc_ad3n_46, io_l16n_t2u_n7_qbc_ad3n_47,
        io_l16n_t2u_n7_qbc_ad3n_48, io_l16n_t2u_n7_qbc_ad3n_64,
        io_l16n_t2u_n7_qbc_ad3n_66, io_l16n_t2u_n7_qbc_ad3n_67,
        io_l16n_t2u_n7_qbc_ad3n_68,
        io_l16n_t2u_n7_qbc_ad3n_a01_d17_65,
        io_l16p_t2u_n6_qbc_ad3p_24, io_l16p_t2u_n6_qbc_ad3p_25,
        io_l16p_t2u_n6_qbc_ad3p_44, io_l16p_t2u_n6_qbc_ad3p_45,
        io_l16p_t2u_n6_qbc_ad3p_46, io_l16p_t2u_n6_qbc_ad3p_47,
        io_l16p_t2u_n6_qbc_ad3p_48, io_l16p_t2u_n6_qbc_ad3p_64,
        io_l16p_t2u_n6_qbc_ad3p_66, io_l16p_t2u_n6_qbc_ad3p_67,
        io_l16p_t2u_n6_qbc_ad3p_68,
        io_l16p_t2u_n6_qbc_ad3p_a00_d16_65,
        io_l17n_t2u_n9_ad10n_24, io_l17n_t2u_n9_ad10n_25,
        io_l17n_t2u_n9_ad10n_44, io_l17n_t2u_n9_ad10n_45,
        io_l17n_t2u_n9_ad10n_46, io_l17n_t2u_n9_ad10n_47,
        io_l17n_t2u_n9_ad10n_48, io_l17n_t2u_n9_ad10n_64,
        io_l17n_t2u_n9_ad10n_66, io_l17n_t2u_n9_ad10n_67,
        io_l17n_t2u_n9_ad10n_68, io_l17n_t2u_n9_ad10n_d15_65,
        io_l17p_t2u_n8_ad10p_24, io_l17p_t2u_n8_ad10p_25,
        io_l17p_t2u_n8_ad10p_44, io_l17p_t2u_n8_ad10p_45,
        io_l17p_t2u_n8_ad10p_46, io_l17p_t2u_n8_ad10p_47,
        io_l17p_t2u_n8_ad10p_48, io_l17p_t2u_n8_ad10p_64,
        io_l17p_t2u_n8_ad10p_66, io_l17p_t2u_n8_ad10p_67,
        io_l17p_t2u_n8_ad10p_68, io_l17p_t2u_n8_ad10p_d14_65,
        io_l18n_t2u_n11_ad2n_24, io_l18n_t2u_n11_ad2n_25,
        io_l18n_t2u_n11_ad2n_44, io_l18n_t2u_n11_ad2n_45,
        io_l18n_t2u_n11_ad2n_46, io_l18n_t2u_n11_ad2n_47,
        io_l18n_t2u_n11_ad2n_48, io_l18n_t2u_n11_ad2n_64,
        io_l18n_t2u_n11_ad2n_66, io_l18n_t2u_n11_ad2n_67,
        io_l18n_t2u_n11_ad2n_68, io_l18n_t2u_n11_ad2n_d13_65,
        io_l18p_t2u_n10_ad2p_24, io_l18p_t2u_n10_ad2p_25,
        io_l18p_t2u_n10_ad2p_44, io_l18p_t2u_n10_ad2p_45,
        io_l18p_t2u_n10_ad2p_46, io_l18p_t2u_n10_ad2p_47,
        io_l18p_t2u_n10_ad2p_48, io_l18p_t2u_n10_ad2p_64,
        io_l18p_t2u_n10_ad2p_66, io_l18p_t2u_n10_ad2p_67,
        io_l18p_t2u_n10_ad2p_68, io_l18p_t2u_n10_ad2p_d12_65,
        io_l19n_t3l_n1_dbc_ad9n_24, io_l19n_t3l_n1_dbc_ad9n_25,
        io_l19n_t3l_n1_dbc_ad9n_44, io_l19n_t3l_n1_dbc_ad9n_45,
        io_l19n_t3l_n1_dbc_ad9n_46, io_l19n_t3l_n1_dbc_ad9n_47,
        io_l19n_t3l_n1_dbc_ad9n_48, io_l19n_t3l_n1_dbc_ad9n_64,
        io_l19n_t3l_n1_dbc_ad9n_66, io_l19n_t3l_n1_dbc_ad9n_67,
        io_l19n_t3l_n1_dbc_ad9n_68,
        io_l19n_t3l_n1_dbc_ad9n_d11_65,
        io_l19p_t3l_n0_dbc_ad9p_24, io_l19p_t3l_n0_dbc_ad9p_25,
        io_l19p_t3l_n0_dbc_ad9p_44, io_l19p_t3l_n0_dbc_ad9p_45,
        io_l19p_t3l_n0_dbc_ad9p_46, io_l19p_t3l_n0_dbc_ad9p_47,
        io_l19p_t3l_n0_dbc_ad9p_48, io_l19p_t3l_n0_dbc_ad9p_64,
        io_l19p_t3l_n0_dbc_ad9p_66, io_l19p_t3l_n0_dbc_ad9p_67,
        io_l19p_t3l_n0_dbc_ad9p_68,
        io_l19p_t3l_n0_dbc_ad9p_d10_65, io_l1n_t0l_n1_dbc_24,
        io_l1n_t0l_n1_dbc_25, io_l1n_t0l_n1_dbc_44,
        io_l1n_t0l_n1_dbc_45, io_l1n_t0l_n1_dbc_46,
        io_l1n_t0l_n1_dbc_47, io_l1n_t0l_n1_dbc_48,
        io_l1n_t0l_n1_dbc_64, io_l1n_t0l_n1_dbc_66,
        io_l1n_t0l_n1_dbc_67, io_l1n_t0l_n1_dbc_68,
        io_l1n_t0l_n1_dbc_rs1_65, io_l1p_t0l_n0_dbc_24,
        io_l1p_t0l_n0_dbc_25, io_l1p_t0l_n0_dbc_44,
        io_l1p_t0l_n0_dbc_45, io_l1p_t0l_n0_dbc_46,
        io_l1p_t0l_n0_dbc_47, io_l1p_t0l_n0_dbc_48,
        io_l1p_t0l_n0_dbc_64, io_l1p_t0l_n0_dbc_66,
        io_l1p_t0l_n0_dbc_67, io_l1p_t0l_n0_dbc_68,
        io_l1p_t0l_n0_dbc_rs0_65, io_l20n_t3l_n3_ad1n_24,
        io_l20n_t3l_n3_ad1n_25, io_l20n_t3l_n3_ad1n_44,
        io_l20n_t3l_n3_ad1n_45, io_l20n_t3l_n3_ad1n_46,
        io_l20n_t3l_n3_ad1n_47, io_l20n_t3l_n3_ad1n_48,
        io_l20n_t3l_n3_ad1n_64, io_l20n_t3l_n3_ad1n_66,
        io_l20n_t3l_n3_ad1n_67, io_l20n_t3l_n3_ad1n_68,
        io_l20n_t3l_n3_ad1n_d09_65, io_l20p_t3l_n2_ad1p_24,
        io_l20p_t3l_n2_ad1p_25, io_l20p_t3l_n2_ad1p_44,
        io_l20p_t3l_n2_ad1p_45, io_l20p_t3l_n2_ad1p_46,
        io_l20p_t3l_n2_ad1p_47, io_l20p_t3l_n2_ad1p_48,
        io_l20p_t3l_n2_ad1p_64, io_l20p_t3l_n2_ad1p_66,
        io_l20p_t3l_n2_ad1p_67, io_l20p_t3l_n2_ad1p_68,
        io_l20p_t3l_n2_ad1p_d08_65, io_l21n_t3l_n5_ad8n_24,
        io_l21n_t3l_n5_ad8n_25, io_l21n_t3l_n5_ad8n_44,
        io_l21n_t3l_n5_ad8n_45, io_l21n_t3l_n5_ad8n_46,
        io_l21n_t3l_n5_ad8n_47, io_l21n_t3l_n5_ad8n_48,
        io_l21n_t3l_n5_ad8n_64, io_l21n_t3l_n5_ad8n_66,
        io_l21n_t3l_n5_ad8n_67, io_l21n_t3l_n5_ad8n_68,
        io_l21n_t3l_n5_ad8n_d07_65, io_l21p_t3l_n4_ad8p_24,
        io_l21p_t3l_n4_ad8p_25, io_l21p_t3l_n4_ad8p_44,
        io_l21p_t3l_n4_ad8p_45, io_l21p_t3l_n4_ad8p_46,
        io_l21p_t3l_n4_ad8p_47, io_l21p_t3l_n4_ad8p_48,
        io_l21p_t3l_n4_ad8p_64, io_l21p_t3l_n4_ad8p_66,
        io_l21p_t3l_n4_ad8p_67, io_l21p_t3l_n4_ad8p_68,
        io_l21p_t3l_n4_ad8p_d06_65, io_l22n_t3u_n7_dbc_ad0n_24,
        io_l22n_t3u_n7_dbc_ad0n_25, io_l22n_t3u_n7_dbc_ad0n_44,
        io_l22n_t3u_n7_dbc_ad0n_45, io_l22n_t3u_n7_dbc_ad0n_46,
        io_l22n_t3u_n7_dbc_ad0n_47, io_l22n_t3u_n7_dbc_ad0n_48,
        io_l22n_t3u_n7_dbc_ad0n_64, io_l22n_t3u_n7_dbc_ad0n_66,
        io_l22n_t3u_n7_dbc_ad0n_67, io_l22n_t3u_n7_dbc_ad0n_68,
        io_l22n_t3u_n7_dbc_ad0n_d05_65,
        io_l22p_t3u_n6_dbc_ad0p_24, io_l22p_t3u_n6_dbc_ad0p_25,
        io_l22p_t3u_n6_dbc_ad0p_44, io_l22p_t3u_n6_dbc_ad0p_45,
        io_l22p_t3u_n6_dbc_ad0p_46, io_l22p_t3u_n6_dbc_ad0p_47,
        io_l22p_t3u_n6_dbc_ad0p_48, io_l22p_t3u_n6_dbc_ad0p_64,
        io_l22p_t3u_n6_dbc_ad0p_66, io_l22p_t3u_n6_dbc_ad0p_67,
        io_l22p_t3u_n6_dbc_ad0p_68,
        io_l22p_t3u_n6_dbc_ad0p_d04_65, io_l23n_t3u_n9_24,
        io_l23n_t3u_n9_25, io_l23n_t3u_n9_44, io_l23n_t3u_n9_45,
        io_l23n_t3u_n9_46, io_l23n_t3u_n9_47, io_l23n_t3u_n9_48,
        io_l23n_t3u_n9_64, io_l23n_t3u_n9_66, io_l23n_t3u_n9_67,
        io_l23n_t3u_n9_68, io_l23n_t3u_n9_i2c_sda_65,
        io_l23p_t3u_n8_24, io_l23p_t3u_n8_25, io_l23p_t3u_n8_44,
        io_l23p_t3u_n8_45, io_l23p_t3u_n8_46, io_l23p_t3u_n8_47,
        io_l23p_t3u_n8_48, io_l23p_t3u_n8_64, io_l23p_t3u_n8_66,
        io_l23p_t3u_n8_67, io_l23p_t3u_n8_68,
        io_l23p_t3u_n8_i2c_sclk_65, io_l24n_t3u_n11_24,
        io_l24n_t3u_n11_25, io_l24n_t3u_n11_44,
        io_l24n_t3u_n11_45, io_l24n_t3u_n11_46,
        io_l24n_t3u_n11_47, io_l24n_t3u_n11_48,
        io_l24n_t3u_n11_64, io_l24n_t3u_n11_66,
        io_l24n_t3u_n11_67, io_l24n_t3u_n11_68,
        io_l24n_t3u_n11_dout_cso_b_65, io_l24p_t3u_n10_24,
        io_l24p_t3u_n10_25, io_l24p_t3u_n10_44,
        io_l24p_t3u_n10_45, io_l24p_t3u_n10_46,
        io_l24p_t3u_n10_47, io_l24p_t3u_n10_48,
        io_l24p_t3u_n10_64, io_l24p_t3u_n10_66,
        io_l24p_t3u_n10_67, io_l24p_t3u_n10_68,
        io_l24p_t3u_n10_emcclk_65, io_l2n_t0l_n3_24,
        io_l2n_t0l_n3_25, io_l2n_t0l_n3_44, io_l2n_t0l_n3_45,
        io_l2n_t0l_n3_46, io_l2n_t0l_n3_47, io_l2n_t0l_n3_48,
        io_l2n_t0l_n3_64, io_l2n_t0l_n3_66, io_l2n_t0l_n3_67,
        io_l2n_t0l_n3_68, io_l2n_t0l_n3_fwe_fcs2_b_65,
        io_l2p_t0l_n2_24, io_l2p_t0l_n2_25, io_l2p_t0l_n2_44,
        io_l2p_t0l_n2_45, io_l2p_t0l_n2_46, io_l2p_t0l_n2_47,
        io_l2p_t0l_n2_48, io_l2p_t0l_n2_64, io_l2p_t0l_n2_66,
        io_l2p_t0l_n2_67, io_l2p_t0l_n2_68,
        io_l2p_t0l_n2_foe_b_65, io_l3n_t0l_n5_ad15n_24,
        io_l3n_t0l_n5_ad15n_25, io_l3n_t0l_n5_ad15n_44,
        io_l3n_t0l_n5_ad15n_45, io_l3n_t0l_n5_ad15n_46,
        io_l3n_t0l_n5_ad15n_47, io_l3n_t0l_n5_ad15n_48,
        io_l3n_t0l_n5_ad15n_64, io_l3n_t0l_n5_ad15n_66,
        io_l3n_t0l_n5_ad15n_67, io_l3n_t0l_n5_ad15n_68,
        io_l3n_t0l_n5_ad15n_a27_65, io_l3p_t0l_n4_ad15p_24,
        io_l3p_t0l_n4_ad15p_25, io_l3p_t0l_n4_ad15p_44,
        io_l3p_t0l_n4_ad15p_45, io_l3p_t0l_n4_ad15p_46,
        io_l3p_t0l_n4_ad15p_47, io_l3p_t0l_n4_ad15p_48,
        io_l3p_t0l_n4_ad15p_64, io_l3p_t0l_n4_ad15p_66,
        io_l3p_t0l_n4_ad15p_67, io_l3p_t0l_n4_ad15p_68,
        io_l3p_t0l_n4_ad15p_a26_65, io_l4n_t0u_n7_dbc_ad7n_24,
        io_l4n_t0u_n7_dbc_ad7n_25, io_l4n_t0u_n7_dbc_ad7n_44,
        io_l4n_t0u_n7_dbc_ad7n_45, io_l4n_t0u_n7_dbc_ad7n_46,
        io_l4n_t0u_n7_dbc_ad7n_47, io_l4n_t0u_n7_dbc_ad7n_48,
        io_l4n_t0u_n7_dbc_ad7n_64, io_l4n_t0u_n7_dbc_ad7n_66,
        io_l4n_t0u_n7_dbc_ad7n_67, io_l4n_t0u_n7_dbc_ad7n_68,
        io_l4n_t0u_n7_dbc_ad7n_a25_65,
        io_l4p_t0u_n6_dbc_ad7p_24, io_l4p_t0u_n6_dbc_ad7p_25,
        io_l4p_t0u_n6_dbc_ad7p_44, io_l4p_t0u_n6_dbc_ad7p_45,
        io_l4p_t0u_n6_dbc_ad7p_46, io_l4p_t0u_n6_dbc_ad7p_47,
        io_l4p_t0u_n6_dbc_ad7p_48, io_l4p_t0u_n6_dbc_ad7p_64,
        io_l4p_t0u_n6_dbc_ad7p_66, io_l4p_t0u_n6_dbc_ad7p_67,
        io_l4p_t0u_n6_dbc_ad7p_68,
        io_l4p_t0u_n6_dbc_ad7p_a24_65, io_l5n_t0u_n9_ad14n_24,
        io_l5n_t0u_n9_ad14n_25, io_l5n_t0u_n9_ad14n_44,
        io_l5n_t0u_n9_ad14n_45, io_l5n_t0u_n9_ad14n_46,
        io_l5n_t0u_n9_ad14n_47, io_l5n_t0u_n9_ad14n_48,
        io_l5n_t0u_n9_ad14n_64, io_l5n_t0u_n9_ad14n_66,
        io_l5n_t0u_n9_ad14n_67, io_l5n_t0u_n9_ad14n_68,
        io_l5n_t0u_n9_ad14n_a23_65, io_l5p_t0u_n8_ad14p_24,
        io_l5p_t0u_n8_ad14p_25, io_l5p_t0u_n8_ad14p_44,
        io_l5p_t0u_n8_ad14p_45, io_l5p_t0u_n8_ad14p_46,
        io_l5p_t0u_n8_ad14p_47, io_l5p_t0u_n8_ad14p_48,
        io_l5p_t0u_n8_ad14p_64, io_l5p_t0u_n8_ad14p_66,
        io_l5p_t0u_n8_ad14p_67, io_l5p_t0u_n8_ad14p_68,
        io_l5p_t0u_n8_ad14p_a22_65, io_l6n_t0u_n11_ad6n_24,
        io_l6n_t0u_n11_ad6n_25, io_l6n_t0u_n11_ad6n_44,
        io_l6n_t0u_n11_ad6n_45, io_l6n_t0u_n11_ad6n_46,
        io_l6n_t0u_n11_ad6n_47, io_l6n_t0u_n11_ad6n_48,
        io_l6n_t0u_n11_ad6n_64, io_l6n_t0u_n11_ad6n_66,
        io_l6n_t0u_n11_ad6n_67, io_l6n_t0u_n11_ad6n_68,
        io_l6n_t0u_n11_ad6n_a21_65, io_l6p_t0u_n10_ad6p_24,
        io_l6p_t0u_n10_ad6p_25, io_l6p_t0u_n10_ad6p_44,
        io_l6p_t0u_n10_ad6p_45, io_l6p_t0u_n10_ad6p_46,
        io_l6p_t0u_n10_ad6p_47, io_l6p_t0u_n10_ad6p_48,
        io_l6p_t0u_n10_ad6p_64, io_l6p_t0u_n10_ad6p_66,
        io_l6p_t0u_n10_ad6p_67, io_l6p_t0u_n10_ad6p_68,
        io_l6p_t0u_n10_ad6p_a20_65, io_l7n_t1l_n1_qbc_ad13n_24,
        io_l7n_t1l_n1_qbc_ad13n_25, io_l7n_t1l_n1_qbc_ad13n_44,
        io_l7n_t1l_n1_qbc_ad13n_45, io_l7n_t1l_n1_qbc_ad13n_46,
        io_l7n_t1l_n1_qbc_ad13n_47, io_l7n_t1l_n1_qbc_ad13n_48,
        io_l7n_t1l_n1_qbc_ad13n_64, io_l7n_t1l_n1_qbc_ad13n_66,
        io_l7n_t1l_n1_qbc_ad13n_67, io_l7n_t1l_n1_qbc_ad13n_68,
        io_l7n_t1l_n1_qbc_ad13n_a19_65,
        io_l7p_t1l_n0_qbc_ad13p_24, io_l7p_t1l_n0_qbc_ad13p_25,
        io_l7p_t1l_n0_qbc_ad13p_44, io_l7p_t1l_n0_qbc_ad13p_45,
        io_l7p_t1l_n0_qbc_ad13p_46, io_l7p_t1l_n0_qbc_ad13p_47,
        io_l7p_t1l_n0_qbc_ad13p_48, io_l7p_t1l_n0_qbc_ad13p_64,
        io_l7p_t1l_n0_qbc_ad13p_66, io_l7p_t1l_n0_qbc_ad13p_67,
        io_l7p_t1l_n0_qbc_ad13p_68,
        io_l7p_t1l_n0_qbc_ad13p_a18_65, io_l8n_t1l_n3_ad5n_24,
        io_l8n_t1l_n3_ad5n_25, io_l8n_t1l_n3_ad5n_44,
        io_l8n_t1l_n3_ad5n_45, io_l8n_t1l_n3_ad5n_46,
        io_l8n_t1l_n3_ad5n_47, io_l8n_t1l_n3_ad5n_48,
        io_l8n_t1l_n3_ad5n_64, io_l8n_t1l_n3_ad5n_66,
        io_l8n_t1l_n3_ad5n_67, io_l8n_t1l_n3_ad5n_68,
        io_l8n_t1l_n3_ad5n_a17_65, io_l8p_t1l_n2_ad5p_24,
        io_l8p_t1l_n2_ad5p_25, io_l8p_t1l_n2_ad5p_44,
        io_l8p_t1l_n2_ad5p_45, io_l8p_t1l_n2_ad5p_46,
        io_l8p_t1l_n2_ad5p_47, io_l8p_t1l_n2_ad5p_48,
        io_l8p_t1l_n2_ad5p_64, io_l8p_t1l_n2_ad5p_66,
        io_l8p_t1l_n2_ad5p_67, io_l8p_t1l_n2_ad5p_68,
        io_l8p_t1l_n2_ad5p_a16_65, io_l9n_t1l_n5_ad12n_24,
        io_l9n_t1l_n5_ad12n_25, io_l9n_t1l_n5_ad12n_44,
        io_l9n_t1l_n5_ad12n_45, io_l9n_t1l_n5_ad12n_46,
        io_l9n_t1l_n5_ad12n_47, io_l9n_t1l_n5_ad12n_48,
        io_l9n_t1l_n5_ad12n_64, io_l9n_t1l_n5_ad12n_66,
        io_l9n_t1l_n5_ad12n_67, io_l9n_t1l_n5_ad12n_68,
        io_l9n_t1l_n5_ad12n_a15_d31_65, io_l9p_t1l_n4_ad12p_24,
        io_l9p_t1l_n4_ad12p_25, io_l9p_t1l_n4_ad12p_44,
        io_l9p_t1l_n4_ad12p_45, io_l9p_t1l_n4_ad12p_46,
        io_l9p_t1l_n4_ad12p_47, io_l9p_t1l_n4_ad12p_48,
        io_l9p_t1l_n4_ad12p_64, io_l9p_t1l_n4_ad12p_66,
        io_l9p_t1l_n4_ad12p_67, io_l9p_t1l_n4_ad12p_68,
        io_l9p_t1l_n4_ad12p_a14_d30_65, io_t0u_n12_64,
        io_t0u_n12_a28_65, io_t0u_n12_vrp_24, io_t0u_n12_vrp_25,
        io_t0u_n12_vrp_44, io_t0u_n12_vrp_45, io_t0u_n12_vrp_46,
        io_t0u_n12_vrp_47, io_t0u_n12_vrp_48, io_t0u_n12_vrp_66,
        io_t0u_n12_vrp_67, io_t0u_n12_vrp_68, io_t1u_n12_24,
        io_t1u_n12_25, io_t1u_n12_44, io_t1u_n12_45,
        io_t1u_n12_46, io_t1u_n12_47, io_t1u_n12_48,
        io_t1u_n12_64, io_t1u_n12_66, io_t1u_n12_67,
        io_t1u_n12_68, io_t1u_n12_perstn1_65, io_t2u_n12_24,
        io_t2u_n12_25, io_t2u_n12_44, io_t2u_n12_45,
        io_t2u_n12_46, io_t2u_n12_47, io_t2u_n12_48,
        io_t2u_n12_64, io_t2u_n12_66, io_t2u_n12_67,
        io_t2u_n12_68, io_t2u_n12_csi_adv_b_65, io_t3u_n12_24,
        io_t3u_n12_25, io_t3u_n12_44, io_t3u_n12_45,
        io_t3u_n12_46, io_t3u_n12_47, io_t3u_n12_48,
        io_t3u_n12_64, io_t3u_n12_66, io_t3u_n12_67,
        io_t3u_n12_68, io_t3u_n12_perstn0_65, m0_0, m1_0, m2_0,
        mgtavcc_l, mgtavcc_rn, mgtavcc_rs, mgtavtt_l, mgtavtt_rn,
        mgtavtt_rs, mgtavttrcal_l, mgtavttrcal_rn,
        mgtavttrcal_rs, mgthrxn0_126, mgthrxn0_127, mgthrxn0_128,
        mgthrxn0_224, mgthrxn0_225, mgthrxn0_226, mgthrxn0_227,
        mgthrxn0_228, mgthrxn0_229, mgthrxn0_230, mgthrxn0_231,
        mgthrxn0_232, mgthrxn1_126, mgthrxn1_127, mgthrxn1_128,
        mgthrxn1_224, mgthrxn1_225, mgthrxn1_226, mgthrxn1_227,
        mgthrxn1_228, mgthrxn1_229, mgthrxn1_230, mgthrxn1_231,
        mgthrxn1_232, mgthrxn2_126, mgthrxn2_127, mgthrxn2_128,
        mgthrxn2_224, mgthrxn2_225, mgthrxn2_226, mgthrxn2_227,
        mgthrxn2_228, mgthrxn2_229, mgthrxn2_230, mgthrxn2_231,
        mgthrxn2_232, mgthrxn3_126, mgthrxn3_127, mgthrxn3_128,
        mgthrxn3_224, mgthrxn3_225, mgthrxn3_226, mgthrxn3_227,
        mgthrxn3_228, mgthrxn3_229, mgthrxn3_230, mgthrxn3_231,
        mgthrxn3_232, mgthrxp0_126, mgthrxp0_127, mgthrxp0_128,
        mgthrxp0_224, mgthrxp0_225, mgthrxp0_226, mgthrxp0_227,
        mgthrxp0_228, mgthrxp0_229, mgthrxp0_230, mgthrxp0_231,
        mgthrxp0_232, mgthrxp1_126, mgthrxp1_127, mgthrxp1_128,
        mgthrxp1_224, mgthrxp1_225, mgthrxp1_226, mgthrxp1_227,
        mgthrxp1_228, mgthrxp1_229, mgthrxp1_230, mgthrxp1_231,
        mgthrxp1_232, mgthrxp2_126, mgthrxp2_127, mgthrxp2_128,
        mgthrxp2_224, mgthrxp2_225, mgthrxp2_226, mgthrxp2_227,
        mgthrxp2_228, mgthrxp2_229, mgthrxp2_230, mgthrxp2_231,
        mgthrxp2_232, mgthrxp3_126, mgthrxp3_127, mgthrxp3_128,
        mgthrxp3_224, mgthrxp3_225, mgthrxp3_226, mgthrxp3_227,
        mgthrxp3_228, mgthrxp3_229, mgthrxp3_230, mgthrxp3_231,
        mgthrxp3_232, mgthtxn0_126, mgthtxn0_127, mgthtxn0_128,
        mgthtxn0_224, mgthtxn0_225, mgthtxn0_226, mgthtxn0_227,
        mgthtxn0_228, mgthtxn0_229, mgthtxn0_230, mgthtxn0_231,
        mgthtxn0_232, mgthtxn1_126, mgthtxn1_127, mgthtxn1_128,
        mgthtxn1_224, mgthtxn1_225, mgthtxn1_226, mgthtxn1_227,
        mgthtxn1_228, mgthtxn1_229, mgthtxn1_230, mgthtxn1_231,
        mgthtxn1_232, mgthtxn2_126, mgthtxn2_127, mgthtxn2_128,
        mgthtxn2_224, mgthtxn2_225, mgthtxn2_226, mgthtxn2_227,
        mgthtxn2_228, mgthtxn2_229, mgthtxn2_230, mgthtxn2_231,
        mgthtxn2_232, mgthtxn3_126, mgthtxn3_127, mgthtxn3_128,
        mgthtxn3_224, mgthtxn3_225, mgthtxn3_226, mgthtxn3_227,
        mgthtxn3_228, mgthtxn3_229, mgthtxn3_230, mgthtxn3_231,
        mgthtxn3_232, mgthtxp0_126, mgthtxp0_127, mgthtxp0_128,
        mgthtxp0_224, mgthtxp0_225, mgthtxp0_226, mgthtxp0_227,
        mgthtxp0_228, mgthtxp0_229, mgthtxp0_230, mgthtxp0_231,
        mgthtxp0_232, mgthtxp1_126, mgthtxp1_127, mgthtxp1_128,
        mgthtxp1_224, mgthtxp1_225, mgthtxp1_226, mgthtxp1_227,
        mgthtxp1_228, mgthtxp1_229, mgthtxp1_230, mgthtxp1_231,
        mgthtxp1_232, mgthtxp2_126, mgthtxp2_127, mgthtxp2_128,
        mgthtxp2_224, mgthtxp2_225, mgthtxp2_226, mgthtxp2_227,
        mgthtxp2_228, mgthtxp2_229, mgthtxp2_230, mgthtxp2_231,
        mgthtxp2_232, mgthtxp3_126, mgthtxp3_127, mgthtxp3_128,
        mgthtxp3_224, mgthtxp3_225, mgthtxp3_226, mgthtxp3_227,
        mgthtxp3_228, mgthtxp3_229, mgthtxp3_230, mgthtxp3_231,
        mgthtxp3_232, mgtrefclk0n_126, mgtrefclk0n_127,
        mgtrefclk0n_128, mgtrefclk0n_224, mgtrefclk0n_225,
        mgtrefclk0n_226, mgtrefclk0n_227, mgtrefclk0n_228,
        mgtrefclk0n_229, mgtrefclk0n_230, mgtrefclk0n_231,
        mgtrefclk0n_232, mgtrefclk0p_126, mgtrefclk0p_127,
        mgtrefclk0p_128, mgtrefclk0p_224, mgtrefclk0p_225,
        mgtrefclk0p_226, mgtrefclk0p_227, mgtrefclk0p_228,
        mgtrefclk0p_229, mgtrefclk0p_230, mgtrefclk0p_231,
        mgtrefclk0p_232, mgtrefclk1n_126, mgtrefclk1n_127,
        mgtrefclk1n_128, mgtrefclk1n_224, mgtrefclk1n_225,
        mgtrefclk1n_226, mgtrefclk1n_227, mgtrefclk1n_228,
        mgtrefclk1n_229, mgtrefclk1n_230, mgtrefclk1n_231,
        mgtrefclk1n_232, mgtrefclk1p_126, mgtrefclk1p_127,
        mgtrefclk1p_128, mgtrefclk1p_224, mgtrefclk1p_225,
        mgtrefclk1p_226, mgtrefclk1p_227, mgtrefclk1p_228,
        mgtrefclk1p_229, mgtrefclk1p_230, mgtrefclk1p_231,
        mgtrefclk1p_232, mgtrref_l, mgtrref_rn, mgtrref_rs,
        mgtvccaux_l, mgtvccaux_rn, mgtvccaux_rs, por_override,
        program_b_0, pudc_b_0, rdwr_fcs_b_0, tck_0, tdi_0, tdo_0,
        tms_0, vbatt, vccadc, vccaux, vccaux_io, vccbram, vccint,
        vccint_io, vcco_0, vcco_24, vcco_25, vcco_44, vcco_45,
        vcco_46, vcco_47, vcco_48, vcco_64, vcco_65, vcco_66,
        vcco_67, vcco_68, vn, vp, vref_24, vref_25, vref_44, vref_45,
        vref_46, vref_47, vref_48, vref_64, vref_65, vref_66,
        vref_67, vref_68, vrefn, vrefp);
    inout cclk_0;
    inout cfgbvs_0;
    inout d00_mosi_0;
    inout d01_din_0;
    inout d02_0;
    inout d03_0;
    inout done_0;
    inout dxn;
    inout dxp;
    inout [349:0] gnd;
    inout gndadc;
    inout init_b_0;
    inout io_l10n_t1u_n7_qbc_ad4n_24;
    inout io_l10n_t1u_n7_qbc_ad4n_25;
    inout io_l10n_t1u_n7_qbc_ad4n_44;
    inout io_l10n_t1u_n7_qbc_ad4n_45;
    inout io_l10n_t1u_n7_qbc_ad4n_46;
    inout io_l10n_t1u_n7_qbc_ad4n_47;
    inout io_l10n_t1u_n7_qbc_ad4n_48;
    inout io_l10n_t1u_n7_qbc_ad4n_64;
    inout io_l10n_t1u_n7_qbc_ad4n_66;
    inout io_l10n_t1u_n7_qbc_ad4n_67;
    inout io_l10n_t1u_n7_qbc_ad4n_68;
    inout io_l10n_t1u_n7_qbc_ad4n_a13_d29_65;
    inout io_l10p_t1u_n6_qbc_ad4p_24;
    inout io_l10p_t1u_n6_qbc_ad4p_25;
    inout io_l10p_t1u_n6_qbc_ad4p_44;
    inout io_l10p_t1u_n6_qbc_ad4p_45;
    inout io_l10p_t1u_n6_qbc_ad4p_46;
    inout io_l10p_t1u_n6_qbc_ad4p_47;
    inout io_l10p_t1u_n6_qbc_ad4p_48;
    inout io_l10p_t1u_n6_qbc_ad4p_64;
    inout io_l10p_t1u_n6_qbc_ad4p_66;
    inout io_l10p_t1u_n6_qbc_ad4p_67;
    inout io_l10p_t1u_n6_qbc_ad4p_68;
    inout io_l10p_t1u_n6_qbc_ad4p_a12_d28_65;
    inout io_l11n_t1u_n9_gc_24;
    inout io_l11n_t1u_n9_gc_25;
    inout io_l11n_t1u_n9_gc_44;
    inout io_l11n_t1u_n9_gc_45;
    inout io_l11n_t1u_n9_gc_46;
    inout io_l11n_t1u_n9_gc_47;
    inout io_l11n_t1u_n9_gc_48;
    inout io_l11n_t1u_n9_gc_64;
    inout io_l11n_t1u_n9_gc_66;
    inout io_l11n_t1u_n9_gc_67;
    inout io_l11n_t1u_n9_gc_68;
    inout io_l11n_t1u_n9_gc_a11_d27_65;
    inout io_l11p_t1u_n8_gc_24;
    inout io_l11p_t1u_n8_gc_25;
    inout io_l11p_t1u_n8_gc_44;
    inout io_l11p_t1u_n8_gc_45;
    inout io_l11p_t1u_n8_gc_46;
    inout io_l11p_t1u_n8_gc_47;
    inout io_l11p_t1u_n8_gc_48;
    inout io_l11p_t1u_n8_gc_64;
    inout io_l11p_t1u_n8_gc_66;
    inout io_l11p_t1u_n8_gc_67;
    inout io_l11p_t1u_n8_gc_68;
    inout io_l11p_t1u_n8_gc_a10_d26_65;
    inout io_l12n_t1u_n11_gc_24;
    inout io_l12n_t1u_n11_gc_25;
    inout io_l12n_t1u_n11_gc_44;
    inout io_l12n_t1u_n11_gc_45;
    inout io_l12n_t1u_n11_gc_46;
    inout io_l12n_t1u_n11_gc_47;
    inout io_l12n_t1u_n11_gc_48;
    inout io_l12n_t1u_n11_gc_64;
    inout io_l12n_t1u_n11_gc_66;
    inout io_l12n_t1u_n11_gc_67;
    inout io_l12n_t1u_n11_gc_68;
    inout io_l12n_t1u_n11_gc_a09_d25_65;
    inout io_l12p_t1u_n10_gc_24;
    inout io_l12p_t1u_n10_gc_25;
    inout io_l12p_t1u_n10_gc_44;
    inout io_l12p_t1u_n10_gc_45;
    inout io_l12p_t1u_n10_gc_46;
    inout io_l12p_t1u_n10_gc_47;
    inout io_l12p_t1u_n10_gc_48;
    inout io_l12p_t1u_n10_gc_64;
    inout io_l12p_t1u_n10_gc_66;
    inout io_l12p_t1u_n10_gc_67;
    inout io_l12p_t1u_n10_gc_68;
    inout io_l12p_t1u_n10_gc_a08_d24_65;
    inout io_l13n_t2l_n1_gc_qbc_24;
    inout io_l13n_t2l_n1_gc_qbc_25;
    inout io_l13n_t2l_n1_gc_qbc_44;
    inout io_l13n_t2l_n1_gc_qbc_45;
    inout io_l13n_t2l_n1_gc_qbc_46;
    inout io_l13n_t2l_n1_gc_qbc_47;
    inout io_l13n_t2l_n1_gc_qbc_48;
    inout io_l13n_t2l_n1_gc_qbc_64;
    inout io_l13n_t2l_n1_gc_qbc_66;
    inout io_l13n_t2l_n1_gc_qbc_67;
    inout io_l13n_t2l_n1_gc_qbc_68;
    inout io_l13n_t2l_n1_gc_qbc_a07_d23_65;
    inout io_l13p_t2l_n0_gc_qbc_24;
    inout io_l13p_t2l_n0_gc_qbc_25;
    inout io_l13p_t2l_n0_gc_qbc_44;
    inout io_l13p_t2l_n0_gc_qbc_45;
    inout io_l13p_t2l_n0_gc_qbc_46;
    inout io_l13p_t2l_n0_gc_qbc_47;
    inout io_l13p_t2l_n0_gc_qbc_48;
    inout io_l13p_t2l_n0_gc_qbc_64;
    inout io_l13p_t2l_n0_gc_qbc_66;
    inout io_l13p_t2l_n0_gc_qbc_67;
    inout io_l13p_t2l_n0_gc_qbc_68;
    inout io_l13p_t2l_n0_gc_qbc_a06_d22_65;
    inout io_l14n_t2l_n3_gc_24;
    inout io_l14n_t2l_n3_gc_25;
    inout io_l14n_t2l_n3_gc_44;
    inout io_l14n_t2l_n3_gc_45;
    inout io_l14n_t2l_n3_gc_46;
    inout io_l14n_t2l_n3_gc_47;
    inout io_l14n_t2l_n3_gc_48;
    inout io_l14n_t2l_n3_gc_64;
    inout io_l14n_t2l_n3_gc_66;
    inout io_l14n_t2l_n3_gc_67;
    inout io_l14n_t2l_n3_gc_68;
    inout io_l14n_t2l_n3_gc_a05_d21_65;
    inout io_l14p_t2l_n2_gc_24;
    inout io_l14p_t2l_n2_gc_25;
    inout io_l14p_t2l_n2_gc_44;
    inout io_l14p_t2l_n2_gc_45;
    inout io_l14p_t2l_n2_gc_46;
    inout io_l14p_t2l_n2_gc_47;
    inout io_l14p_t2l_n2_gc_48;
    inout io_l14p_t2l_n2_gc_64;
    inout io_l14p_t2l_n2_gc_66;
    inout io_l14p_t2l_n2_gc_67;
    inout io_l14p_t2l_n2_gc_68;
    inout io_l14p_t2l_n2_gc_a04_d20_65;
    inout io_l15n_t2l_n5_ad11n_24;
    inout io_l15n_t2l_n5_ad11n_25;
    inout io_l15n_t2l_n5_ad11n_44;
    inout io_l15n_t2l_n5_ad11n_45;
    inout io_l15n_t2l_n5_ad11n_46;
    inout io_l15n_t2l_n5_ad11n_47;
    inout io_l15n_t2l_n5_ad11n_48;
    inout io_l15n_t2l_n5_ad11n_64;
    inout io_l15n_t2l_n5_ad11n_66;
    inout io_l15n_t2l_n5_ad11n_67;
    inout io_l15n_t2l_n5_ad11n_68;
    inout io_l15n_t2l_n5_ad11n_a03_d19_65;
    inout io_l15p_t2l_n4_ad11p_24;
    inout io_l15p_t2l_n4_ad11p_25;
    inout io_l15p_t2l_n4_ad11p_44;
    inout io_l15p_t2l_n4_ad11p_45;
    inout io_l15p_t2l_n4_ad11p_46;
    inout io_l15p_t2l_n4_ad11p_47;
    inout io_l15p_t2l_n4_ad11p_48;
    inout io_l15p_t2l_n4_ad11p_64;
    inout io_l15p_t2l_n4_ad11p_66;
    inout io_l15p_t2l_n4_ad11p_67;
    inout io_l15p_t2l_n4_ad11p_68;
    inout io_l15p_t2l_n4_ad11p_a02_d18_65;
    inout io_l16n_t2u_n7_qbc_ad3n_24;
    inout io_l16n_t2u_n7_qbc_ad3n_25;
    inout io_l16n_t2u_n7_qbc_ad3n_44;
    inout io_l16n_t2u_n7_qbc_ad3n_45;
    inout io_l16n_t2u_n7_qbc_ad3n_46;
    inout io_l16n_t2u_n7_qbc_ad3n_47;
    inout io_l16n_t2u_n7_qbc_ad3n_48;
    inout io_l16n_t2u_n7_qbc_ad3n_64;
    inout io_l16n_t2u_n7_qbc_ad3n_66;
    inout io_l16n_t2u_n7_qbc_ad3n_67;
    inout io_l16n_t2u_n7_qbc_ad3n_68;
    inout io_l16n_t2u_n7_qbc_ad3n_a01_d17_65;
    inout io_l16p_t2u_n6_qbc_ad3p_24;
    inout io_l16p_t2u_n6_qbc_ad3p_25;
    inout io_l16p_t2u_n6_qbc_ad3p_44;
    inout io_l16p_t2u_n6_qbc_ad3p_45;
    inout io_l16p_t2u_n6_qbc_ad3p_46;
    inout io_l16p_t2u_n6_qbc_ad3p_47;
    inout io_l16p_t2u_n6_qbc_ad3p_48;
    inout io_l16p_t2u_n6_qbc_ad3p_64;
    inout io_l16p_t2u_n6_qbc_ad3p_66;
    inout io_l16p_t2u_n6_qbc_ad3p_67;
    inout io_l16p_t2u_n6_qbc_ad3p_68;
    inout io_l16p_t2u_n6_qbc_ad3p_a00_d16_65;
    inout io_l17n_t2u_n9_ad10n_24;
    inout io_l17n_t2u_n9_ad10n_25;
    inout io_l17n_t2u_n9_ad10n_44;
    inout io_l17n_t2u_n9_ad10n_45;
    inout io_l17n_t2u_n9_ad10n_46;
    inout io_l17n_t2u_n9_ad10n_47;
    inout io_l17n_t2u_n9_ad10n_48;
    inout io_l17n_t2u_n9_ad10n_64;
    inout io_l17n_t2u_n9_ad10n_66;
    inout io_l17n_t2u_n9_ad10n_67;
    inout io_l17n_t2u_n9_ad10n_68;
    inout io_l17n_t2u_n9_ad10n_d15_65;
    inout io_l17p_t2u_n8_ad10p_24;
    inout io_l17p_t2u_n8_ad10p_25;
    inout io_l17p_t2u_n8_ad10p_44;
    inout io_l17p_t2u_n8_ad10p_45;
    inout io_l17p_t2u_n8_ad10p_46;
    inout io_l17p_t2u_n8_ad10p_47;
    inout io_l17p_t2u_n8_ad10p_48;
    inout io_l17p_t2u_n8_ad10p_64;
    inout io_l17p_t2u_n8_ad10p_66;
    inout io_l17p_t2u_n8_ad10p_67;
    inout io_l17p_t2u_n8_ad10p_68;
    inout io_l17p_t2u_n8_ad10p_d14_65;
    inout io_l18n_t2u_n11_ad2n_24;
    inout io_l18n_t2u_n11_ad2n_25;
    inout io_l18n_t2u_n11_ad2n_44;
    inout io_l18n_t2u_n11_ad2n_45;
    inout io_l18n_t2u_n11_ad2n_46;
    inout io_l18n_t2u_n11_ad2n_47;
    inout io_l18n_t2u_n11_ad2n_48;
    inout io_l18n_t2u_n11_ad2n_64;
    inout io_l18n_t2u_n11_ad2n_66;
    inout io_l18n_t2u_n11_ad2n_67;
    inout io_l18n_t2u_n11_ad2n_68;
    inout io_l18n_t2u_n11_ad2n_d13_65;
    inout io_l18p_t2u_n10_ad2p_24;
    inout io_l18p_t2u_n10_ad2p_25;
    inout io_l18p_t2u_n10_ad2p_44;
    inout io_l18p_t2u_n10_ad2p_45;
    inout io_l18p_t2u_n10_ad2p_46;
    inout io_l18p_t2u_n10_ad2p_47;
    inout io_l18p_t2u_n10_ad2p_48;
    inout io_l18p_t2u_n10_ad2p_64;
    inout io_l18p_t2u_n10_ad2p_66;
    inout io_l18p_t2u_n10_ad2p_67;
    inout io_l18p_t2u_n10_ad2p_68;
    inout io_l18p_t2u_n10_ad2p_d12_65;
    inout io_l19n_t3l_n1_dbc_ad9n_24;
    inout io_l19n_t3l_n1_dbc_ad9n_25;
    inout io_l19n_t3l_n1_dbc_ad9n_44;
    inout io_l19n_t3l_n1_dbc_ad9n_45;
    inout io_l19n_t3l_n1_dbc_ad9n_46;
    inout io_l19n_t3l_n1_dbc_ad9n_47;
    inout io_l19n_t3l_n1_dbc_ad9n_48;
    inout io_l19n_t3l_n1_dbc_ad9n_64;
    inout io_l19n_t3l_n1_dbc_ad9n_66;
    inout io_l19n_t3l_n1_dbc_ad9n_67;
    inout io_l19n_t3l_n1_dbc_ad9n_68;
    inout io_l19n_t3l_n1_dbc_ad9n_d11_65;
    inout io_l19p_t3l_n0_dbc_ad9p_24;
    inout io_l19p_t3l_n0_dbc_ad9p_25;
    inout io_l19p_t3l_n0_dbc_ad9p_44;
    inout io_l19p_t3l_n0_dbc_ad9p_45;
    inout io_l19p_t3l_n0_dbc_ad9p_46;
    inout io_l19p_t3l_n0_dbc_ad9p_47;
    inout io_l19p_t3l_n0_dbc_ad9p_48;
    inout io_l19p_t3l_n0_dbc_ad9p_64;
    inout io_l19p_t3l_n0_dbc_ad9p_66;
    inout io_l19p_t3l_n0_dbc_ad9p_67;
    inout io_l19p_t3l_n0_dbc_ad9p_68;
    inout io_l19p_t3l_n0_dbc_ad9p_d10_65;
    inout io_l1n_t0l_n1_dbc_24;
    inout io_l1n_t0l_n1_dbc_25;
    inout io_l1n_t0l_n1_dbc_44;
    inout io_l1n_t0l_n1_dbc_45;
    inout io_l1n_t0l_n1_dbc_46;
    inout io_l1n_t0l_n1_dbc_47;
    inout io_l1n_t0l_n1_dbc_48;
    inout io_l1n_t0l_n1_dbc_64;
    inout io_l1n_t0l_n1_dbc_66;
    inout io_l1n_t0l_n1_dbc_67;
    inout io_l1n_t0l_n1_dbc_68;
    inout io_l1n_t0l_n1_dbc_rs1_65;
    inout io_l1p_t0l_n0_dbc_24;
    inout io_l1p_t0l_n0_dbc_25;
    inout io_l1p_t0l_n0_dbc_44;
    inout io_l1p_t0l_n0_dbc_45;
    inout io_l1p_t0l_n0_dbc_46;
    inout io_l1p_t0l_n0_dbc_47;
    inout io_l1p_t0l_n0_dbc_48;
    inout io_l1p_t0l_n0_dbc_64;
    inout io_l1p_t0l_n0_dbc_66;
    inout io_l1p_t0l_n0_dbc_67;
    inout io_l1p_t0l_n0_dbc_68;
    inout io_l1p_t0l_n0_dbc_rs0_65;
    inout io_l20n_t3l_n3_ad1n_24;
    inout io_l20n_t3l_n3_ad1n_25;
    inout io_l20n_t3l_n3_ad1n_44;
    inout io_l20n_t3l_n3_ad1n_45;
    inout io_l20n_t3l_n3_ad1n_46;
    inout io_l20n_t3l_n3_ad1n_47;
    inout io_l20n_t3l_n3_ad1n_48;
    inout io_l20n_t3l_n3_ad1n_64;
    inout io_l20n_t3l_n3_ad1n_66;
    inout io_l20n_t3l_n3_ad1n_67;
    inout io_l20n_t3l_n3_ad1n_68;
    inout io_l20n_t3l_n3_ad1n_d09_65;
    inout io_l20p_t3l_n2_ad1p_24;
    inout io_l20p_t3l_n2_ad1p_25;
    inout io_l20p_t3l_n2_ad1p_44;
    inout io_l20p_t3l_n2_ad1p_45;
    inout io_l20p_t3l_n2_ad1p_46;
    inout io_l20p_t3l_n2_ad1p_47;
    inout io_l20p_t3l_n2_ad1p_48;
    inout io_l20p_t3l_n2_ad1p_64;
    inout io_l20p_t3l_n2_ad1p_66;
    inout io_l20p_t3l_n2_ad1p_67;
    inout io_l20p_t3l_n2_ad1p_68;
    inout io_l20p_t3l_n2_ad1p_d08_65;
    inout io_l21n_t3l_n5_ad8n_24;
    inout io_l21n_t3l_n5_ad8n_25;
    inout io_l21n_t3l_n5_ad8n_44;
    inout io_l21n_t3l_n5_ad8n_45;
    inout io_l21n_t3l_n5_ad8n_46;
    inout io_l21n_t3l_n5_ad8n_47;
    inout io_l21n_t3l_n5_ad8n_48;
    inout io_l21n_t3l_n5_ad8n_64;
    inout io_l21n_t3l_n5_ad8n_66;
    inout io_l21n_t3l_n5_ad8n_67;
    inout io_l21n_t3l_n5_ad8n_68;
    inout io_l21n_t3l_n5_ad8n_d07_65;
    inout io_l21p_t3l_n4_ad8p_24;
    inout io_l21p_t3l_n4_ad8p_25;
    inout io_l21p_t3l_n4_ad8p_44;
    inout io_l21p_t3l_n4_ad8p_45;
    inout io_l21p_t3l_n4_ad8p_46;
    inout io_l21p_t3l_n4_ad8p_47;
    inout io_l21p_t3l_n4_ad8p_48;
    inout io_l21p_t3l_n4_ad8p_64;
    inout io_l21p_t3l_n4_ad8p_66;
    inout io_l21p_t3l_n4_ad8p_67;
    inout io_l21p_t3l_n4_ad8p_68;
    inout io_l21p_t3l_n4_ad8p_d06_65;
    inout io_l22n_t3u_n7_dbc_ad0n_24;
    inout io_l22n_t3u_n7_dbc_ad0n_25;
    inout io_l22n_t3u_n7_dbc_ad0n_44;
    inout io_l22n_t3u_n7_dbc_ad0n_45;
    inout io_l22n_t3u_n7_dbc_ad0n_46;
    inout io_l22n_t3u_n7_dbc_ad0n_47;
    inout io_l22n_t3u_n7_dbc_ad0n_48;
    inout io_l22n_t3u_n7_dbc_ad0n_64;
    inout io_l22n_t3u_n7_dbc_ad0n_66;
    inout io_l22n_t3u_n7_dbc_ad0n_67;
    inout io_l22n_t3u_n7_dbc_ad0n_68;
    inout io_l22n_t3u_n7_dbc_ad0n_d05_65;
    inout io_l22p_t3u_n6_dbc_ad0p_24;
    inout io_l22p_t3u_n6_dbc_ad0p_25;
    inout io_l22p_t3u_n6_dbc_ad0p_44;
    inout io_l22p_t3u_n6_dbc_ad0p_45;
    inout io_l22p_t3u_n6_dbc_ad0p_46;
    inout io_l22p_t3u_n6_dbc_ad0p_47;
    inout io_l22p_t3u_n6_dbc_ad0p_48;
    inout io_l22p_t3u_n6_dbc_ad0p_64;
    inout io_l22p_t3u_n6_dbc_ad0p_66;
    inout io_l22p_t3u_n6_dbc_ad0p_67;
    inout io_l22p_t3u_n6_dbc_ad0p_68;
    inout io_l22p_t3u_n6_dbc_ad0p_d04_65;
    inout io_l23n_t3u_n9_24;
    inout io_l23n_t3u_n9_25;
    inout io_l23n_t3u_n9_44;
    inout io_l23n_t3u_n9_45;
    inout io_l23n_t3u_n9_46;
    inout io_l23n_t3u_n9_47;
    inout io_l23n_t3u_n9_48;
    inout io_l23n_t3u_n9_64;
    inout io_l23n_t3u_n9_66;
    inout io_l23n_t3u_n9_67;
    inout io_l23n_t3u_n9_68;
    inout io_l23n_t3u_n9_i2c_sda_65;
    inout io_l23p_t3u_n8_24;
    inout io_l23p_t3u_n8_25;
    inout io_l23p_t3u_n8_44;
    inout io_l23p_t3u_n8_45;
    inout io_l23p_t3u_n8_46;
    inout io_l23p_t3u_n8_47;
    inout io_l23p_t3u_n8_48;
    inout io_l23p_t3u_n8_64;
    inout io_l23p_t3u_n8_66;
    inout io_l23p_t3u_n8_67;
    inout io_l23p_t3u_n8_68;
    inout io_l23p_t3u_n8_i2c_sclk_65;
    inout io_l24n_t3u_n11_24;
    inout io_l24n_t3u_n11_25;
    inout io_l24n_t3u_n11_44;
    inout io_l24n_t3u_n11_45;
    inout io_l24n_t3u_n11_46;
    inout io_l24n_t3u_n11_47;
    inout io_l24n_t3u_n11_48;
    inout io_l24n_t3u_n11_64;
    inout io_l24n_t3u_n11_66;
    inout io_l24n_t3u_n11_67;
    inout io_l24n_t3u_n11_68;
    inout io_l24n_t3u_n11_dout_cso_b_65;
    inout io_l24p_t3u_n10_24;
    inout io_l24p_t3u_n10_25;
    inout io_l24p_t3u_n10_44;
    inout io_l24p_t3u_n10_45;
    inout io_l24p_t3u_n10_46;
    inout io_l24p_t3u_n10_47;
    inout io_l24p_t3u_n10_48;
    inout io_l24p_t3u_n10_64;
    inout io_l24p_t3u_n10_66;
    inout io_l24p_t3u_n10_67;
    inout io_l24p_t3u_n10_68;
    inout io_l24p_t3u_n10_emcclk_65;
    inout io_l2n_t0l_n3_24;
    inout io_l2n_t0l_n3_25;
    inout io_l2n_t0l_n3_44;
    inout io_l2n_t0l_n3_45;
    inout io_l2n_t0l_n3_46;
    inout io_l2n_t0l_n3_47;
    inout io_l2n_t0l_n3_48;
    inout io_l2n_t0l_n3_64;
    inout io_l2n_t0l_n3_66;
    inout io_l2n_t0l_n3_67;
    inout io_l2n_t0l_n3_68;
    inout io_l2n_t0l_n3_fwe_fcs2_b_65;
    inout io_l2p_t0l_n2_24;
    inout io_l2p_t0l_n2_25;
    inout io_l2p_t0l_n2_44;
    inout io_l2p_t0l_n2_45;
    inout io_l2p_t0l_n2_46;
    inout io_l2p_t0l_n2_47;
    inout io_l2p_t0l_n2_48;
    inout io_l2p_t0l_n2_64;
    inout io_l2p_t0l_n2_66;
    inout io_l2p_t0l_n2_67;
    inout io_l2p_t0l_n2_68;
    inout io_l2p_t0l_n2_foe_b_65;
    inout io_l3n_t0l_n5_ad15n_24;
    inout io_l3n_t0l_n5_ad15n_25;
    inout io_l3n_t0l_n5_ad15n_44;
    inout io_l3n_t0l_n5_ad15n_45;
    inout io_l3n_t0l_n5_ad15n_46;
    inout io_l3n_t0l_n5_ad15n_47;
    inout io_l3n_t0l_n5_ad15n_48;
    inout io_l3n_t0l_n5_ad15n_64;
    inout io_l3n_t0l_n5_ad15n_66;
    inout io_l3n_t0l_n5_ad15n_67;
    inout io_l3n_t0l_n5_ad15n_68;
    inout io_l3n_t0l_n5_ad15n_a27_65;
    inout io_l3p_t0l_n4_ad15p_24;
    inout io_l3p_t0l_n4_ad15p_25;
    inout io_l3p_t0l_n4_ad15p_44;
    inout io_l3p_t0l_n4_ad15p_45;
    inout io_l3p_t0l_n4_ad15p_46;
    inout io_l3p_t0l_n4_ad15p_47;
    inout io_l3p_t0l_n4_ad15p_48;
    inout io_l3p_t0l_n4_ad15p_64;
    inout io_l3p_t0l_n4_ad15p_66;
    inout io_l3p_t0l_n4_ad15p_67;
    inout io_l3p_t0l_n4_ad15p_68;
    inout io_l3p_t0l_n4_ad15p_a26_65;
    inout io_l4n_t0u_n7_dbc_ad7n_24;
    inout io_l4n_t0u_n7_dbc_ad7n_25;
    inout io_l4n_t0u_n7_dbc_ad7n_44;
    inout io_l4n_t0u_n7_dbc_ad7n_45;
    inout io_l4n_t0u_n7_dbc_ad7n_46;
    inout io_l4n_t0u_n7_dbc_ad7n_47;
    inout io_l4n_t0u_n7_dbc_ad7n_48;
    inout io_l4n_t0u_n7_dbc_ad7n_64;
    inout io_l4n_t0u_n7_dbc_ad7n_66;
    inout io_l4n_t0u_n7_dbc_ad7n_67;
    inout io_l4n_t0u_n7_dbc_ad7n_68;
    inout io_l4n_t0u_n7_dbc_ad7n_a25_65;
    inout io_l4p_t0u_n6_dbc_ad7p_24;
    inout io_l4p_t0u_n6_dbc_ad7p_25;
    inout io_l4p_t0u_n6_dbc_ad7p_44;
    inout io_l4p_t0u_n6_dbc_ad7p_45;
    inout io_l4p_t0u_n6_dbc_ad7p_46;
    inout io_l4p_t0u_n6_dbc_ad7p_47;
    inout io_l4p_t0u_n6_dbc_ad7p_48;
    inout io_l4p_t0u_n6_dbc_ad7p_64;
    inout io_l4p_t0u_n6_dbc_ad7p_66;
    inout io_l4p_t0u_n6_dbc_ad7p_67;
    inout io_l4p_t0u_n6_dbc_ad7p_68;
    inout io_l4p_t0u_n6_dbc_ad7p_a24_65;
    inout io_l5n_t0u_n9_ad14n_24;
    inout io_l5n_t0u_n9_ad14n_25;
    inout io_l5n_t0u_n9_ad14n_44;
    inout io_l5n_t0u_n9_ad14n_45;
    inout io_l5n_t0u_n9_ad14n_46;
    inout io_l5n_t0u_n9_ad14n_47;
    inout io_l5n_t0u_n9_ad14n_48;
    inout io_l5n_t0u_n9_ad14n_64;
    inout io_l5n_t0u_n9_ad14n_66;
    inout io_l5n_t0u_n9_ad14n_67;
    inout io_l5n_t0u_n9_ad14n_68;
    inout io_l5n_t0u_n9_ad14n_a23_65;
    inout io_l5p_t0u_n8_ad14p_24;
    inout io_l5p_t0u_n8_ad14p_25;
    inout io_l5p_t0u_n8_ad14p_44;
    inout io_l5p_t0u_n8_ad14p_45;
    inout io_l5p_t0u_n8_ad14p_46;
    inout io_l5p_t0u_n8_ad14p_47;
    inout io_l5p_t0u_n8_ad14p_48;
    inout io_l5p_t0u_n8_ad14p_64;
    inout io_l5p_t0u_n8_ad14p_66;
    inout io_l5p_t0u_n8_ad14p_67;
    inout io_l5p_t0u_n8_ad14p_68;
    inout io_l5p_t0u_n8_ad14p_a22_65;
    inout io_l6n_t0u_n11_ad6n_24;
    inout io_l6n_t0u_n11_ad6n_25;
    inout io_l6n_t0u_n11_ad6n_44;
    inout io_l6n_t0u_n11_ad6n_45;
    inout io_l6n_t0u_n11_ad6n_46;
    inout io_l6n_t0u_n11_ad6n_47;
    inout io_l6n_t0u_n11_ad6n_48;
    inout io_l6n_t0u_n11_ad6n_64;
    inout io_l6n_t0u_n11_ad6n_66;
    inout io_l6n_t0u_n11_ad6n_67;
    inout io_l6n_t0u_n11_ad6n_68;
    inout io_l6n_t0u_n11_ad6n_a21_65;
    inout io_l6p_t0u_n10_ad6p_24;
    inout io_l6p_t0u_n10_ad6p_25;
    inout io_l6p_t0u_n10_ad6p_44;
    inout io_l6p_t0u_n10_ad6p_45;
    inout io_l6p_t0u_n10_ad6p_46;
    inout io_l6p_t0u_n10_ad6p_47;
    inout io_l6p_t0u_n10_ad6p_48;
    inout io_l6p_t0u_n10_ad6p_64;
    inout io_l6p_t0u_n10_ad6p_66;
    inout io_l6p_t0u_n10_ad6p_67;
    inout io_l6p_t0u_n10_ad6p_68;
    inout io_l6p_t0u_n10_ad6p_a20_65;
    inout io_l7n_t1l_n1_qbc_ad13n_24;
    inout io_l7n_t1l_n1_qbc_ad13n_25;
    inout io_l7n_t1l_n1_qbc_ad13n_44;
    inout io_l7n_t1l_n1_qbc_ad13n_45;
    inout io_l7n_t1l_n1_qbc_ad13n_46;
    inout io_l7n_t1l_n1_qbc_ad13n_47;
    inout io_l7n_t1l_n1_qbc_ad13n_48;
    inout io_l7n_t1l_n1_qbc_ad13n_64;
    inout io_l7n_t1l_n1_qbc_ad13n_66;
    inout io_l7n_t1l_n1_qbc_ad13n_67;
    inout io_l7n_t1l_n1_qbc_ad13n_68;
    inout io_l7n_t1l_n1_qbc_ad13n_a19_65;
    inout io_l7p_t1l_n0_qbc_ad13p_24;
    inout io_l7p_t1l_n0_qbc_ad13p_25;
    inout io_l7p_t1l_n0_qbc_ad13p_44;
    inout io_l7p_t1l_n0_qbc_ad13p_45;
    inout io_l7p_t1l_n0_qbc_ad13p_46;
    inout io_l7p_t1l_n0_qbc_ad13p_47;
    inout io_l7p_t1l_n0_qbc_ad13p_48;
    inout io_l7p_t1l_n0_qbc_ad13p_64;
    inout io_l7p_t1l_n0_qbc_ad13p_66;
    inout io_l7p_t1l_n0_qbc_ad13p_67;
    inout io_l7p_t1l_n0_qbc_ad13p_68;
    inout io_l7p_t1l_n0_qbc_ad13p_a18_65;
    inout io_l8n_t1l_n3_ad5n_24;
    inout io_l8n_t1l_n3_ad5n_25;
    inout io_l8n_t1l_n3_ad5n_44;
    inout io_l8n_t1l_n3_ad5n_45;
    inout io_l8n_t1l_n3_ad5n_46;
    inout io_l8n_t1l_n3_ad5n_47;
    inout io_l8n_t1l_n3_ad5n_48;
    inout io_l8n_t1l_n3_ad5n_64;
    inout io_l8n_t1l_n3_ad5n_66;
    inout io_l8n_t1l_n3_ad5n_67;
    inout io_l8n_t1l_n3_ad5n_68;
    inout io_l8n_t1l_n3_ad5n_a17_65;
    inout io_l8p_t1l_n2_ad5p_24;
    inout io_l8p_t1l_n2_ad5p_25;
    inout io_l8p_t1l_n2_ad5p_44;
    inout io_l8p_t1l_n2_ad5p_45;
    inout io_l8p_t1l_n2_ad5p_46;
    inout io_l8p_t1l_n2_ad5p_47;
    inout io_l8p_t1l_n2_ad5p_48;
    inout io_l8p_t1l_n2_ad5p_64;
    inout io_l8p_t1l_n2_ad5p_66;
    inout io_l8p_t1l_n2_ad5p_67;
    inout io_l8p_t1l_n2_ad5p_68;
    inout io_l8p_t1l_n2_ad5p_a16_65;
    inout io_l9n_t1l_n5_ad12n_24;
    inout io_l9n_t1l_n5_ad12n_25;
    inout io_l9n_t1l_n5_ad12n_44;
    inout io_l9n_t1l_n5_ad12n_45;
    inout io_l9n_t1l_n5_ad12n_46;
    inout io_l9n_t1l_n5_ad12n_47;
    inout io_l9n_t1l_n5_ad12n_48;
    inout io_l9n_t1l_n5_ad12n_64;
    inout io_l9n_t1l_n5_ad12n_66;
    inout io_l9n_t1l_n5_ad12n_67;
    inout io_l9n_t1l_n5_ad12n_68;
    inout io_l9n_t1l_n5_ad12n_a15_d31_65;
    inout io_l9p_t1l_n4_ad12p_24;
    inout io_l9p_t1l_n4_ad12p_25;
    inout io_l9p_t1l_n4_ad12p_44;
    inout io_l9p_t1l_n4_ad12p_45;
    inout io_l9p_t1l_n4_ad12p_46;
    inout io_l9p_t1l_n4_ad12p_47;
    inout io_l9p_t1l_n4_ad12p_48;
    inout io_l9p_t1l_n4_ad12p_64;
    inout io_l9p_t1l_n4_ad12p_66;
    inout io_l9p_t1l_n4_ad12p_67;
    inout io_l9p_t1l_n4_ad12p_68;
    inout io_l9p_t1l_n4_ad12p_a14_d30_65;
    inout io_t0u_n12_64;
    inout io_t0u_n12_a28_65;
    inout io_t0u_n12_vrp_24;
    inout io_t0u_n12_vrp_25;
    inout io_t0u_n12_vrp_44;
    inout io_t0u_n12_vrp_45;
    inout io_t0u_n12_vrp_46;
    inout io_t0u_n12_vrp_47;
    inout io_t0u_n12_vrp_48;
    inout io_t0u_n12_vrp_66;
    inout io_t0u_n12_vrp_67;
    inout io_t0u_n12_vrp_68;
    inout io_t1u_n12_24;
    inout io_t1u_n12_25;
    inout io_t1u_n12_44;
    inout io_t1u_n12_45;
    inout io_t1u_n12_46;
    inout io_t1u_n12_47;
    inout io_t1u_n12_48;
    inout io_t1u_n12_64;
    inout io_t1u_n12_66;
    inout io_t1u_n12_67;
    inout io_t1u_n12_68;
    inout io_t1u_n12_perstn1_65;
    inout io_t2u_n12_24;
    inout io_t2u_n12_25;
    inout io_t2u_n12_44;
    inout io_t2u_n12_45;
    inout io_t2u_n12_46;
    inout io_t2u_n12_47;
    inout io_t2u_n12_48;
    inout io_t2u_n12_64;
    inout io_t2u_n12_66;
    inout io_t2u_n12_67;
    inout io_t2u_n12_68;
    inout io_t2u_n12_csi_adv_b_65;
    inout io_t3u_n12_24;
    inout io_t3u_n12_25;
    inout io_t3u_n12_44;
    inout io_t3u_n12_45;
    inout io_t3u_n12_46;
    inout io_t3u_n12_47;
    inout io_t3u_n12_48;
    inout io_t3u_n12_64;
    inout io_t3u_n12_66;
    inout io_t3u_n12_67;
    inout io_t3u_n12_68;
    inout io_t3u_n12_perstn0_65;
    inout m0_0;
    inout m1_0;
    inout m2_0;
    inout [10:0] mgtavcc_l;
    inout [14:0] mgtavcc_rn;
    inout [16:0] mgtavcc_rs;
    inout [13:0] mgtavtt_l;
    inout [15:0] mgtavtt_rn;
    inout [20:0] mgtavtt_rs;
    inout mgtavttrcal_l;
    inout mgtavttrcal_rn;
    inout mgtavttrcal_rs;
    inout mgthrxn0_126;
    inout mgthrxn0_127;
    inout mgthrxn0_128;
    inout mgthrxn0_224;
    inout mgthrxn0_225;
    inout mgthrxn0_226;
    inout mgthrxn0_227;
    inout mgthrxn0_228;
    inout mgthrxn0_229;
    inout mgthrxn0_230;
    inout mgthrxn0_231;
    inout mgthrxn0_232;
    inout mgthrxn1_126;
    inout mgthrxn1_127;
    inout mgthrxn1_128;
    inout mgthrxn1_224;
    inout mgthrxn1_225;
    inout mgthrxn1_226;
    inout mgthrxn1_227;
    inout mgthrxn1_228;
    inout mgthrxn1_229;
    inout mgthrxn1_230;
    inout mgthrxn1_231;
    inout mgthrxn1_232;
    inout mgthrxn2_126;
    inout mgthrxn2_127;
    inout mgthrxn2_128;
    inout mgthrxn2_224;
    inout mgthrxn2_225;
    inout mgthrxn2_226;
    inout mgthrxn2_227;
    inout mgthrxn2_228;
    inout mgthrxn2_229;
    inout mgthrxn2_230;
    inout mgthrxn2_231;
    inout mgthrxn2_232;
    inout mgthrxn3_126;
    inout mgthrxn3_127;
    inout mgthrxn3_128;
    inout mgthrxn3_224;
    inout mgthrxn3_225;
    inout mgthrxn3_226;
    inout mgthrxn3_227;
    inout mgthrxn3_228;
    inout mgthrxn3_229;
    inout mgthrxn3_230;
    inout mgthrxn3_231;
    inout mgthrxn3_232;
    inout mgthrxp0_126;
    inout mgthrxp0_127;
    inout mgthrxp0_128;
    inout mgthrxp0_224;
    inout mgthrxp0_225;
    inout mgthrxp0_226;
    inout mgthrxp0_227;
    inout mgthrxp0_228;
    inout mgthrxp0_229;
    inout mgthrxp0_230;
    inout mgthrxp0_231;
    inout mgthrxp0_232;
    inout mgthrxp1_126;
    inout mgthrxp1_127;
    inout mgthrxp1_128;
    inout mgthrxp1_224;
    inout mgthrxp1_225;
    inout mgthrxp1_226;
    inout mgthrxp1_227;
    inout mgthrxp1_228;
    inout mgthrxp1_229;
    inout mgthrxp1_230;
    inout mgthrxp1_231;
    inout mgthrxp1_232;
    inout mgthrxp2_126;
    inout mgthrxp2_127;
    inout mgthrxp2_128;
    inout mgthrxp2_224;
    inout mgthrxp2_225;
    inout mgthrxp2_226;
    inout mgthrxp2_227;
    inout mgthrxp2_228;
    inout mgthrxp2_229;
    inout mgthrxp2_230;
    inout mgthrxp2_231;
    inout mgthrxp2_232;
    inout mgthrxp3_126;
    inout mgthrxp3_127;
    inout mgthrxp3_128;
    inout mgthrxp3_224;
    inout mgthrxp3_225;
    inout mgthrxp3_226;
    inout mgthrxp3_227;
    inout mgthrxp3_228;
    inout mgthrxp3_229;
    inout mgthrxp3_230;
    inout mgthrxp3_231;
    inout mgthrxp3_232;
    inout mgthtxn0_126;
    inout mgthtxn0_127;
    inout mgthtxn0_128;
    inout mgthtxn0_224;
    inout mgthtxn0_225;
    inout mgthtxn0_226;
    inout mgthtxn0_227;
    inout mgthtxn0_228;
    inout mgthtxn0_229;
    inout mgthtxn0_230;
    inout mgthtxn0_231;
    inout mgthtxn0_232;
    inout mgthtxn1_126;
    inout mgthtxn1_127;
    inout mgthtxn1_128;
    inout mgthtxn1_224;
    inout mgthtxn1_225;
    inout mgthtxn1_226;
    inout mgthtxn1_227;
    inout mgthtxn1_228;
    inout mgthtxn1_229;
    inout mgthtxn1_230;
    inout mgthtxn1_231;
    inout mgthtxn1_232;
    inout mgthtxn2_126;
    inout mgthtxn2_127;
    inout mgthtxn2_128;
    inout mgthtxn2_224;
    inout mgthtxn2_225;
    inout mgthtxn2_226;
    inout mgthtxn2_227;
    inout mgthtxn2_228;
    inout mgthtxn2_229;
    inout mgthtxn2_230;
    inout mgthtxn2_231;
    inout mgthtxn2_232;
    inout mgthtxn3_126;
    inout mgthtxn3_127;
    inout mgthtxn3_128;
    inout mgthtxn3_224;
    inout mgthtxn3_225;
    inout mgthtxn3_226;
    inout mgthtxn3_227;
    inout mgthtxn3_228;
    inout mgthtxn3_229;
    inout mgthtxn3_230;
    inout mgthtxn3_231;
    inout mgthtxn3_232;
    inout mgthtxp0_126;
    inout mgthtxp0_127;
    inout mgthtxp0_128;
    inout mgthtxp0_224;
    inout mgthtxp0_225;
    inout mgthtxp0_226;
    inout mgthtxp0_227;
    inout mgthtxp0_228;
    inout mgthtxp0_229;
    inout mgthtxp0_230;
    inout mgthtxp0_231;
    inout mgthtxp0_232;
    inout mgthtxp1_126;
    inout mgthtxp1_127;
    inout mgthtxp1_128;
    inout mgthtxp1_224;
    inout mgthtxp1_225;
    inout mgthtxp1_226;
    inout mgthtxp1_227;
    inout mgthtxp1_228;
    inout mgthtxp1_229;
    inout mgthtxp1_230;
    inout mgthtxp1_231;
    inout mgthtxp1_232;
    inout mgthtxp2_126;
    inout mgthtxp2_127;
    inout mgthtxp2_128;
    inout mgthtxp2_224;
    inout mgthtxp2_225;
    inout mgthtxp2_226;
    inout mgthtxp2_227;
    inout mgthtxp2_228;
    inout mgthtxp2_229;
    inout mgthtxp2_230;
    inout mgthtxp2_231;
    inout mgthtxp2_232;
    inout mgthtxp3_126;
    inout mgthtxp3_127;
    inout mgthtxp3_128;
    inout mgthtxp3_224;
    inout mgthtxp3_225;
    inout mgthtxp3_226;
    inout mgthtxp3_227;
    inout mgthtxp3_228;
    inout mgthtxp3_229;
    inout mgthtxp3_230;
    inout mgthtxp3_231;
    inout mgthtxp3_232;
    inout mgtrefclk0n_126;
    inout mgtrefclk0n_127;
    inout mgtrefclk0n_128;
    inout mgtrefclk0n_224;
    inout mgtrefclk0n_225;
    inout mgtrefclk0n_226;
    inout mgtrefclk0n_227;
    inout mgtrefclk0n_228;
    inout mgtrefclk0n_229;
    inout mgtrefclk0n_230;
    inout mgtrefclk0n_231;
    inout mgtrefclk0n_232;
    inout mgtrefclk0p_126;
    inout mgtrefclk0p_127;
    inout mgtrefclk0p_128;
    inout mgtrefclk0p_224;
    inout mgtrefclk0p_225;
    inout mgtrefclk0p_226;
    inout mgtrefclk0p_227;
    inout mgtrefclk0p_228;
    inout mgtrefclk0p_229;
    inout mgtrefclk0p_230;
    inout mgtrefclk0p_231;
    inout mgtrefclk0p_232;
    inout mgtrefclk1n_126;
    inout mgtrefclk1n_127;
    inout mgtrefclk1n_128;
    inout mgtrefclk1n_224;
    inout mgtrefclk1n_225;
    inout mgtrefclk1n_226;
    inout mgtrefclk1n_227;
    inout mgtrefclk1n_228;
    inout mgtrefclk1n_229;
    inout mgtrefclk1n_230;
    inout mgtrefclk1n_231;
    inout mgtrefclk1n_232;
    inout mgtrefclk1p_126;
    inout mgtrefclk1p_127;
    inout mgtrefclk1p_128;
    inout mgtrefclk1p_224;
    inout mgtrefclk1p_225;
    inout mgtrefclk1p_226;
    inout mgtrefclk1p_227;
    inout mgtrefclk1p_228;
    inout mgtrefclk1p_229;
    inout mgtrefclk1p_230;
    inout mgtrefclk1p_231;
    inout mgtrefclk1p_232;
    inout mgtrref_l;
    inout mgtrref_rn;
    inout mgtrref_rs;
    inout [1:0] mgtvccaux_l;
    inout [1:0] mgtvccaux_rn;
    inout [1:0] mgtvccaux_rs;
    inout por_override;
    inout program_b_0;
    inout pudc_b_0;
    inout rdwr_fcs_b_0;
    inout tck_0;
    inout tdi_0;
    inout tdo_0;
    inout tms_0;
    inout vbatt;
    inout vccadc;
    inout [4:0] vccaux;
    inout [11:0] vccaux_io;
    inout [3:0] vccbram;
    inout [48:0] vccint;
    inout [4:0] vccint_io;
    inout [1:0] vcco_0;
    inout [6:0] vcco_24;
    inout [5:0] vcco_25;
    inout [6:0] vcco_44;
    inout [6:0] vcco_45;
    inout [6:0] vcco_46;
    inout [5:0] vcco_47;
    inout [6:0] vcco_48;
    inout [5:0] vcco_64;
    inout [6:0] vcco_65;
    inout [6:0] vcco_66;
    inout [5:0] vcco_67;
    inout [6:0] vcco_68;
    inout vn;
    inout vp;
    inout vref_24;
    inout vref_25;
    inout vref_44;
    inout vref_45;
    inout vref_46;
    inout vref_47;
    inout vref_48;
    inout vref_64;
    inout vref_65;
    inout vref_66;
    inout vref_67;
    inout vref_68;
    inout vrefn;
    inout vrefp;


    initial
        begin
        end

endmodule
