// generated by newgenasym  Tue May 05 19:23:45 2020


module max_max2688 (gnd, rfin, \rfout/shdnb , vcc);
    inout gnd;
    inout rfin;
    inout \rfout/shdnb ;
    inout vcc;


    initial
        begin
        end

endmodule
