-- generated by newgenasym Tue May 05 19:23:45 2020

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity max_max2688 is
    port (    
	GND:       INOUT  STD_LOGIC;    
	RFIN:      INOUT  STD_LOGIC;    
	\rfout/shdnb\: INOUT  STD_LOGIC;    
	VCC:       INOUT  STD_LOGIC);
end max_max2688;
