-- generated by newgenasym Mon May 23 11:12:07 2022

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity mc_hfcn_xxxx_4pin is
    port (    
	GND:       INOUT  STD_LOGIC_VECTOR (1 DOWNTO 0);    
	\in\:      INOUT  STD_LOGIC;    
	\out\:     INOUT  STD_LOGIC);
end mc_hfcn_xxxx_4pin;
