-- generated by newgenasym Sat Dec 28 13:41:00 2019

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity skylab_skg09d is
    port (    
	EXTINT_5:  INOUT  STD_LOGIC;    
	GND_1:     INOUT  STD_LOGIC;    
	GND_10:    INOUT  STD_LOGIC;    
	GND_12:    INOUT  STD_LOGIC;    
	GPIO0_18:  INOUT  STD_LOGIC;    
	GPIO14_16: INOUT  STD_LOGIC;    
	GPIO15_17: INOUT  STD_LOGIC;    
	LNA_EN_13: INOUT  STD_LOGIC;    
	NC_7:      INOUT  STD_LOGIC;    
	PPS_4:     INOUT  STD_LOGIC;    
	RESET_9:   INOUT  STD_LOGIC;    
	RF_IN_11:  INOUT  STD_LOGIC;    
	RXD_3:     INOUT  STD_LOGIC;    
	TXD_2:     INOUT  STD_LOGIC;    
	V_BCKP_6:  INOUT  STD_LOGIC;    
	VANT_15:   INOUT  STD_LOGIC;    
	VCC_8:     INOUT  STD_LOGIC;    
	VCC_RF_14: INOUT  STD_LOGIC);
end skylab_skg09d;
