// generated by newgenasym  Sat Sep 07 18:49:51 2019


module tyco_1410189_3 (a1, a2, a3, a4, a5, a6, a7, a8, b1, b2, b3, b4, b5, b6, b7, b8, c1,
        c2, c3, c4, c5, c6, c7, c8, d1, d2, d3, d4, d5, d6, d7, d8, e1, e2, e3,
        e4, e5, e6, e7, e8, f1, f2, f3, f4, f5, f6, f7, f8, g1, g2, g3, g4, g5,
        g6, g7, g8, h1, h5);
    inout a1;
    inout a2;
    inout a3;
    inout a4;
    inout a5;
    inout a6;
    inout a7;
    inout a8;
    inout b1;
    inout b2;
    inout b3;
    inout b4;
    inout b5;
    inout b6;
    inout b7;
    inout b8;
    inout c1;
    inout c2;
    inout c3;
    inout c4;
    inout c5;
    inout c6;
    inout c7;
    inout c8;
    inout d1;
    inout d2;
    inout d3;
    inout d4;
    inout d5;
    inout d6;
    inout d7;
    inout d8;
    inout e1;
    inout e2;
    inout e3;
    inout e4;
    inout e5;
    inout e6;
    inout e7;
    inout e8;
    inout f1;
    inout f2;
    inout f3;
    inout f4;
    inout f5;
    inout f6;
    inout f7;
    inout f8;
    inout g1;
    inout g2;
    inout g3;
    inout g4;
    inout g5;
    inout g6;
    inout g7;
    inout g8;
    inout h1;
    inout h5;


    initial
        begin
        end

endmodule
