// generated by newgenasym  Tue Dec 01 20:01:34 2020


module adi_adp7104 (adj, en, epad, gnd_1, gnd_2, \n/c , pg, vin, vout);
    inout adj;
    inout en;
    inout epad;
    inout gnd_1;
    inout gnd_2;
    inout \n/c ;
    inout pg;
    inout vin;
    inout vout;


    initial
        begin
        end

endmodule
