-- generated by newgenasym Tue Dec 01 20:01:34 2020

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity adi_adp7104 is
    port (    
	ADJ:       INOUT  STD_LOGIC;    
	EN:        INOUT  STD_LOGIC;    
	EPAD:      INOUT  STD_LOGIC;    
	GND_1:     INOUT  STD_LOGIC;    
	GND_2:     INOUT  STD_LOGIC;    
	\n/c\:     INOUT  STD_LOGIC;    
	PG:        INOUT  STD_LOGIC;    
	VIN:       INOUT  STD_LOGIC;    
	VOUT:      INOUT  STD_LOGIC);
end adi_adp7104;
