-- generated by newgenasym Thu Jun 16 10:54:54 2022

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity adi_adclk914 is
    port (    
	D:         INOUT  STD_LOGIC;    
	\d#\:      INOUT  STD_LOGIC;    
	E_PAD:     INOUT  STD_LOGIC;    
	NC:        INOUT  STD_LOGIC_VECTOR (5 DOWNTO 0);    
	Q:         INOUT  STD_LOGIC;    
	\q#\:      INOUT  STD_LOGIC;    
	VCC:       INOUT  STD_LOGIC_VECTOR (1 DOWNTO 0);    
	VEE:       INOUT  STD_LOGIC_VECTOR (1 DOWNTO 0);    
	VREF:      INOUT  STD_LOGIC;    
	VT:        INOUT  STD_LOGIC);
end adi_adclk914;
