// generated by newgenasym  Fri Apr 02 16:40:03 2021


module mc_dvga2_33a (c0p5, c1, c16, c2, c4, c8, clock, data, gnd_1, gnd_2, le, nc,
        nc_1, nc_2, rf_jump_in, rf_jump_out, rfin, \rfout/vd2 , vd1_0,
        vd1_1);
    inout c0p5;
    inout c1;
    inout c16;
    inout c2;
    inout c4;
    inout c8;
    inout clock;
    inout data;
    inout gnd_1;
    inout gnd_2;
    inout le;
    inout [13:0] nc;
    inout nc_1;
    inout nc_2;
    inout rf_jump_in;
    inout rf_jump_out;
    inout rfin;
    inout \rfout/vd2 ;
    inout vd1_0;
    inout vd1_1;


    initial
        begin
        end

endmodule
