-- generated by newgenasym Thu May 24 10:41:10 2018

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity mur_blm15 is
    port (    
	P1:        INOUT  STD_LOGIC;    
	P2:        INOUT  STD_LOGIC);
end mur_blm15;
