// generated by newgenasym  Sun Apr 09 18:35:40 2017


module mar_88e1512 (avdd18_19, avdd18_26, avdd18_3, avdd18_38, avdd18_out,
        avdd33_20, avdd33_25, avddc18, clk125, config, dvdd_42,
        dvdd_6, dvdd_out, epad, hsdacn, hsdacp, led0, led1,
        \led2/intn , mdc, \mdin0* , mdin0_p, \mdin1* , mdin1_p, \mdin2* ,
        mdin2_p, \mdin3* , mdin3_p, mdio, reg_in, regcap1, regcap2,
        resetn, rset, rx_clk, rx_ctrl, rxd0, rxd1, rxd2, rxd3, s_inn,
        s_inp, s_outn, s_outp, tstpt, tx_clk, tx_ctrl, txd0, txd1,
        txd2, txd3, vddo_11, vddo_49, vddo_52, vddo_sel, xtal_in,
        xtal_out);
    inout avdd18_19;
    inout avdd18_26;
    inout avdd18_3;
    inout avdd18_38;
    inout avdd18_out;
    inout avdd33_20;
    inout avdd33_25;
    inout avddc18;
    inout clk125;
    inout config;
    inout dvdd_42;
    inout dvdd_6;
    inout dvdd_out;
    inout epad;
    inout hsdacn;
    inout hsdacp;
    inout led0;
    inout led1;
    inout \led2/intn ;
    inout mdc;
    inout \mdin0* ;
    inout mdin0_p;
    inout \mdin1* ;
    inout mdin1_p;
    inout \mdin2* ;
    inout mdin2_p;
    inout \mdin3* ;
    inout mdin3_p;
    inout mdio;
    inout reg_in;
    inout regcap1;
    inout regcap2;
    inout resetn;
    inout rset;
    inout rx_clk;
    inout rx_ctrl;
    inout rxd0;
    inout rxd1;
    inout rxd2;
    inout rxd3;
    inout s_inn;
    inout s_inp;
    inout s_outn;
    inout s_outp;
    inout tstpt;
    inout tx_clk;
    inout tx_ctrl;
    inout txd0;
    inout txd1;
    inout txd2;
    inout txd3;
    inout vddo_11;
    inout vddo_49;
    inout vddo_52;
    inout vddo_sel;
    inout xtal_in;
    inout xtal_out;


    initial
        begin
        end

endmodule
