// generated by newgenasym  Fri Sep 03 09:39:49 2010


module sem_sc431cskqtrt (anode, cathode, reference);
    inout anode;
    inout cathode;
    inout reference;


    initial
        begin
        end

endmodule
