// generated by newgenasym  Mon Dec 13 17:36:16 2021


module mps_mpm3632c (agnd_14, agnd_15, bst, en, fb, out_8_9, out_sense, pg,
        pgnd_1, pgnd_19, pgnd_2, pgnd_20, sw_4, sw_5, sw_6_7, vcc,
        vin_17, vin_18);
    inout agnd_14;
    inout agnd_15;
    inout bst;
    inout en;
    inout fb;
    inout out_8_9;
    inout out_sense;
    inout pg;
    inout pgnd_1;
    inout pgnd_19;
    inout pgnd_2;
    inout pgnd_20;
    inout sw_4;
    inout sw_5;
    inout sw_6_7;
    inout vcc;
    inout vin_17;
    inout vin_18;


    initial
        begin
        end

endmodule
