-- generated by newgenasym Mon Dec 13 17:36:16 2021

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity mps_mpm3632c is
    port (    
	AGND_14:   INOUT  STD_LOGIC;    
	AGND_15:   INOUT  STD_LOGIC;    
	BST:       INOUT  STD_LOGIC;    
	EN:        INOUT  STD_LOGIC;    
	FB:        INOUT  STD_LOGIC;    
	OUT_8_9:   INOUT  STD_LOGIC;    
	OUT_SENSE: INOUT  STD_LOGIC;    
	PG:        INOUT  STD_LOGIC;    
	PGND_1:    INOUT  STD_LOGIC;    
	PGND_19:   INOUT  STD_LOGIC;    
	PGND_2:    INOUT  STD_LOGIC;    
	PGND_20:   INOUT  STD_LOGIC;    
	SW_4:      INOUT  STD_LOGIC;    
	SW_5:      INOUT  STD_LOGIC;    
	SW_6_7:    INOUT  STD_LOGIC;    
	VCC:       INOUT  STD_LOGIC;    
	VIN_17:    INOUT  STD_LOGIC;    
	VIN_18:    INOUT  STD_LOGIC);
end mps_mpm3632c;
