-- generated by newgenasym Mon May 23 11:05:34 2022

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity mc_bfcg_xxxx_4pin is
    port (    
	GND:       INOUT  STD_LOGIC_VECTOR (1 DOWNTO 0);    
	\in\:      INOUT  STD_LOGIC;    
	\out\:     INOUT  STD_LOGIC);
end mc_bfcg_xxxx_4pin;
