-- generated by newgenasym Tue Apr 24 15:22:49 2018

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity is_is21es04gjcli_s is
    port (    
	CLK:       INOUT  STD_LOGIC;    
	CMD:       INOUT  STD_LOGIC;    
	DAT0:      INOUT  STD_LOGIC;    
	DAT1:      INOUT  STD_LOGIC;    
	DAT2:      INOUT  STD_LOGIC;    
	DAT3:      INOUT  STD_LOGIC;    
	DAT4:      INOUT  STD_LOGIC;    
	DAT5:      INOUT  STD_LOGIC;    
	DAT6:      INOUT  STD_LOGIC;    
	DAT7:      INOUT  STD_LOGIC;    
	DS:        INOUT  STD_LOGIC;    
	NC:        INOUT  STD_LOGIC_VECTOR (89 DOWNTO 0);    
	RSTN:      INOUT  STD_LOGIC;    
	RSV_VSS:   INOUT  STD_LOGIC;    
	VCC_E6:    INOUT  STD_LOGIC;    
	VCC_F5:    INOUT  STD_LOGIC;    
	VCC_J10:   INOUT  STD_LOGIC;    
	VCC_K9:    INOUT  STD_LOGIC;    
	VCCQ_C6:   INOUT  STD_LOGIC;    
	VCCQ_M4:   INOUT  STD_LOGIC;    
	VCCQ_N4:   INOUT  STD_LOGIC;    
	VCCQ_P3:   INOUT  STD_LOGIC;    
	VCCQ_P5:   INOUT  STD_LOGIC;    
	VDDI:      INOUT  STD_LOGIC;    
	VSS_A6:    INOUT  STD_LOGIC;    
	VSS_E7:    INOUT  STD_LOGIC;    
	VSS_G5:    INOUT  STD_LOGIC;    
	VSS_H10:   INOUT  STD_LOGIC;    
	VSS_K8:    INOUT  STD_LOGIC;    
	VSSQ_C4:   INOUT  STD_LOGIC;    
	VSSQ_N2:   INOUT  STD_LOGIC;    
	VSSQ_N5:   INOUT  STD_LOGIC;    
	VSSQ_P4:   INOUT  STD_LOGIC;    
	VSSQ_P6:   INOUT  STD_LOGIC);
end is_is21es04gjcli_s;
