-- generated by newgenasym Wed Dec 25 15:45:33 2019

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity pu_h5120nl is
    port (    
	MCT1:      INOUT  STD_LOGIC;    
	MCT2:      INOUT  STD_LOGIC;    
	MCT3:      INOUT  STD_LOGIC;    
	MCT4:      INOUT  STD_LOGIC;    
	\mx1+\:    INOUT  STD_LOGIC;    
	\mx1-\:    INOUT  STD_LOGIC;    
	\mx2+\:    INOUT  STD_LOGIC;    
	\mx2-\:    INOUT  STD_LOGIC;    
	\mx3+\:    INOUT  STD_LOGIC;    
	\mx3-\:    INOUT  STD_LOGIC;    
	\mx4+\:    INOUT  STD_LOGIC;    
	\mx4-\:    INOUT  STD_LOGIC;    
	TCT1:      INOUT  STD_LOGIC;    
	TCT2:      INOUT  STD_LOGIC;    
	TCT3:      INOUT  STD_LOGIC;    
	TCT4:      INOUT  STD_LOGIC;    
	\td1+\:    INOUT  STD_LOGIC;    
	\td1-\:    INOUT  STD_LOGIC;    
	\td2+\:    INOUT  STD_LOGIC;    
	\td2-\:    INOUT  STD_LOGIC;    
	\td3+\:    INOUT  STD_LOGIC;    
	\td3-\:    INOUT  STD_LOGIC;    
	\td4+\:    INOUT  STD_LOGIC;    
	\td4-\:    INOUT  STD_LOGIC);
end pu_h5120nl;
