-- generated by newgenasym Wed Sep 28 21:46:37 2016

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity spx_sp3232eey is
    port (    
	\c1+\:     INOUT  STD_LOGIC;    
	\c1-\:     INOUT  STD_LOGIC;    
	\c2+\:     INOUT  STD_LOGIC;    
	\c2-\:     INOUT  STD_LOGIC;    
	GND:       INOUT  STD_LOGIC;    
	R1IN:      INOUT  STD_LOGIC;    
	R1OUT:     INOUT  STD_LOGIC;    
	R2IN:      INOUT  STD_LOGIC;    
	R2OUT:     INOUT  STD_LOGIC;    
	T1IN:      INOUT  STD_LOGIC;    
	T1OUT:     INOUT  STD_LOGIC;    
	T2IN:      INOUT  STD_LOGIC;    
	T2OUT:     INOUT  STD_LOGIC;    
	\v+\:      INOUT  STD_LOGIC;    
	\v-\:      INOUT  STD_LOGIC;    
	VCC:       INOUT  STD_LOGIC);
end spx_sp3232eey;
