// generated by newgenasym  Tue May 31 14:28:24 2022


module mc_tcm1_83x (not_used, pri, pri_dot, sec, sec_dot);
    inout [1:0] not_used;
    inout pri;
    inout pri_dot;
    inout sec;
    inout sec_dot;


    initial
        begin
        end

endmodule
