-- generated by newgenasym Tue May 31 14:28:24 2022

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity mc_tcm1_83x is
    port (    
	NOT_USED:  INOUT  STD_LOGIC_VECTOR (1 DOWNTO 0);    
	PRI:       INOUT  STD_LOGIC;    
	PRI_DOT:   INOUT  STD_LOGIC;    
	SEC:       INOUT  STD_LOGIC;    
	SEC_DOT:   INOUT  STD_LOGIC);
end mc_tcm1_83x;
