-- generated by newgenasym Tue Dec 15 17:47:31 2020

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity led is
    port (    
	\1\:       INOUT  STD_LOGIC;    
	\2\:       INOUT  STD_LOGIC);
end led;
