-- generated by newgenasym Wed Jan 22 12:52:15 2020

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity ti_csd16403q5a is
    port (    
	D:         INOUT  STD_LOGIC;    
	G:         INOUT  STD_LOGIC;    
	S:         INOUT  STD_LOGIC_VECTOR (3 DOWNTO 1));
end ti_csd16403q5a;
