-- generated by newgenasym Wed Sep 25 17:36:25 2019

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity tyco_1_1469492_x is
    port (    
	\1\:       INOUT  STD_LOGIC;    
	\2\:       INOUT  STD_LOGIC);
end tyco_1_1469492_x;
