// generated by newgenasym  Wed Dec 25 15:45:33 2019


module pu_h5120nl (mct1, mct2, mct3, mct4, \mx1+ , \mx1- , \mx2+ , \mx2- , \mx3+ , \mx3- ,
        \mx4+ , \mx4- , tct1, tct2, tct3, tct4, \td1+ , \td1- , \td2+ , \td2- ,
        \td3+ , \td3- , \td4+ , \td4- );
    inout mct1;
    inout mct2;
    inout mct3;
    inout mct4;
    inout \mx1+ ;
    inout \mx1- ;
    inout \mx2+ ;
    inout \mx2- ;
    inout \mx3+ ;
    inout \mx3- ;
    inout \mx4+ ;
    inout \mx4- ;
    inout tct1;
    inout tct2;
    inout tct3;
    inout tct4;
    inout \td1+ ;
    inout \td1- ;
    inout \td2+ ;
    inout \td2- ;
    inout \td3+ ;
    inout \td3- ;
    inout \td4+ ;
    inout \td4- ;


    initial
        begin
        end

endmodule
