// generated by newgenasym  Tue Apr 24 15:22:49 2018


module is_is21es04gjcli_s (clk, cmd, dat0, dat1, dat2, dat3, dat4, dat5, dat6, dat7, ds,
        nc, rstn, rsv_vss, vcc_e6, vcc_f5, vcc_j10, vcc_k9, vccq_c6,
        vccq_m4, vccq_n4, vccq_p3, vccq_p5, vddi, vss_a6, vss_e7,
        vss_g5, vss_h10, vss_k8, vssq_c4, vssq_n2, vssq_n5, vssq_p4,
        vssq_p6);
    inout clk;
    inout cmd;
    inout dat0;
    inout dat1;
    inout dat2;
    inout dat3;
    inout dat4;
    inout dat5;
    inout dat6;
    inout dat7;
    inout ds;
    inout [89:0] nc;
    inout rstn;
    inout rsv_vss;
    inout vcc_e6;
    inout vcc_f5;
    inout vcc_j10;
    inout vcc_k9;
    inout vccq_c6;
    inout vccq_m4;
    inout vccq_n4;
    inout vccq_p3;
    inout vccq_p5;
    inout vddi;
    inout vss_a6;
    inout vss_e7;
    inout vss_g5;
    inout vss_h10;
    inout vss_k8;
    inout vssq_c4;
    inout vssq_n2;
    inout vssq_n5;
    inout vssq_p4;
    inout vssq_p6;


    initial
        begin
        end

endmodule
