-- generated by newgenasym Tue Mar 27 15:38:51 2018

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity l_hq is
    port (    
	N1:        INOUT  STD_LOGIC;    
	N2:        INOUT  STD_LOGIC);
end l_hq;
