-- generated by newgenasym Mon May 23 14:28:54 2022

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity mc_tc1_33_75g2 is
    port (    
	NOT_USED:  INOUT  STD_LOGIC;    
	PRI:       INOUT  STD_LOGIC;    
	PRI_DOT:   INOUT  STD_LOGIC;    
	SEC:       INOUT  STD_LOGIC;    
	SEC_DOT:   INOUT  STD_LOGIC);
end mc_tc1_33_75g2;
