-- generated by newgenasym Fri Mar 24 11:17:40 2017

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity ttn_ox_xxxxx is
    port (    
	GND:       IN     STD_LOGIC;    
	\nc/3_state\: INOUT  STD_LOGIC;    
	OUTPUT:    OUT    STD_LOGIC;    
	VDD:       IN     STD_LOGIC);
end ttn_ox_xxxxx;
