-- generated by newgenasym Tue Oct 10 15:11:36 2017

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity c_all is
    port (    
	A0:        INOUT  STD_LOGIC;    
	B0:        INOUT  STD_LOGIC);
end c_all;
