// generated by newgenasym  Thu Jun 09 17:38:07 2022


module adi_adp7159 (byp, e_pad, en, ref, ref_s, vin, vout, vreg, vs);
    inout byp;
    inout e_pad;
    inout en;
    inout ref;
    inout ref_s;
    inout [1:0] vin;
    inout [1:0] vout;
    inout vreg;
    inout vs;


    initial
        begin
        end

endmodule
