-- generated by newgenasym Thu Jun 09 17:38:07 2022

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity adi_adp7159 is
    port (    
	BYP:       INOUT  STD_LOGIC;    
	E_PAD:     INOUT  STD_LOGIC;    
	EN:        INOUT  STD_LOGIC;    
	REF:       INOUT  STD_LOGIC;    
	REF_S:     INOUT  STD_LOGIC;    
	VIN:       INOUT  STD_LOGIC_VECTOR (1 DOWNTO 0);    
	VOUT:      INOUT  STD_LOGIC_VECTOR (1 DOWNTO 0);    
	VREG:      INOUT  STD_LOGIC;    
	VS:        INOUT  STD_LOGIC);
end adi_adp7159;
