// generated by newgenasym  Fri Dec 31 14:28:36 2021


module adi_ltc2601 (\clr# , \cs#_ld , gnd, \ldac# , pgnd, ref, sck, sdi, sdo, vcc, vout);
    inout \clr# ;
    inout \cs#_ld ;
    inout gnd;
    inout \ldac# ;
    inout pgnd;
    inout ref;
    inout sck;
    inout sdi;
    inout sdo;
    inout vcc;
    inout vout;


    initial
        begin
        end

endmodule
