-- generated by newgenasym Fri Dec 31 14:28:36 2021

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity adi_ltc2601 is
    port (    
	\clr#\:    INOUT  STD_LOGIC;    
	\cs#_ld\:  INOUT  STD_LOGIC;    
	GND:       INOUT  STD_LOGIC;    
	\ldac#\:   INOUT  STD_LOGIC;    
	PGND:      INOUT  STD_LOGIC;    
	REF:       INOUT  STD_LOGIC;    
	SCK:       INOUT  STD_LOGIC;    
	SDI:       INOUT  STD_LOGIC;    
	SDO:       INOUT  STD_LOGIC;    
	VCC:       INOUT  STD_LOGIC;    
	VOUT:      INOUT  STD_LOGIC);
end adi_ltc2601;
