// generated by newgenasym  Tue Aug 04 13:46:53 2009


module sem_sc4215hsetrt (en, fb, gnd, nc, thermalpad, vin, vo);
    inout en;
    inout fb;
    input gnd;
    inout [2:0] nc;
    input thermalpad;
    inout vin;
    inout vo;


    initial
        begin
        end

endmodule
