// generated by newgenasym  Thu Jun 09 19:20:10 2022


module vco_cvco55cc_xxxx (gnd, rf_out, vcc, vt);
    inout [12:0] gnd;
    inout rf_out;
    inout vcc;
    inout vt;


    initial
        begin
        end

endmodule
