-- generated by newgenasym Thu Jun 09 19:20:10 2022

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity vco_cvco55cc_xxxx is
    port (    
	GND:       INOUT  STD_LOGIC_VECTOR (12 DOWNTO 0);    
	RF_OUT:    INOUT  STD_LOGIC;    
	VCC:       INOUT  STD_LOGIC;    
	VT:        INOUT  STD_LOGIC);
end vco_cvco55cc_xxxx;
