// generated by newgenasym  Mon Jan 08 13:07:57 2018


module ttn_xx_xxxx (\1 , \2 , \3 , \4 );
    inout \1 ;
    inout \2 ;
    inout \3 ;
    inout \4 ;


    initial
        begin
        end

endmodule
