// generated by newgenasym  Wed Oct 24 15:35:30 2018


module will_esd5304d (gnd, in1, in2, in3, in4, out1, out2, out3, out4);
    inout gnd;
    inout in1;
    inout in2;
    inout in3;
    inout in4;
    inout out1;
    inout out2;
    inout out3;
    inout out4;


    initial
        begin
        end

endmodule
