// generated by newgenasym  Sat May 02 13:41:22 2020


module ad_adp1763 (en, epad, gnd, pg, refcap, sense, ss, vadj, vin, vout, vreg);
    inout en;
    inout epad;
    inout gnd;
    inout pg;
    inout refcap;
    inout sense;
    inout ss;
    inout vadj;
    inout [3:0] vin;
    inout [3:0] vout;
    inout vreg;


    initial
        begin
        end

endmodule
