// generated by newgenasym  Thu Jun 09 19:09:17 2022


module adi_ltc6952 (cp, \cs# , e_pad, \ezq_srq+ , \ezq_srq- , gnd, nc, \out0+ , \out0- ,
        \out1+ , \out1- , \out10+ , \out10- , \out2+ , \out2- , \out3+ , \out3- ,
        \out4+ , \out4- , \out5+ , \out5- , \out6+ , \out6- , \out7+ , \out7- , \out8+ ,
        \out8- , \out9+ , \out9- , \ref+ , \ref- , sclk, \sd# , sdi, sdo, stat,
        \vco+ , \vco- , \vcp+ , \vd+ , \vout+ , \vref+ , \vvco+ );
    inout cp;
    inout \cs# ;
    inout e_pad;
    inout \ezq_srq+ ;
    inout \ezq_srq- ;
    inout gnd;
    inout nc;
    inout \out0+ ;
    inout \out0- ;
    inout \out1+ ;
    inout \out1- ;
    inout \out10+ ;
    inout \out10- ;
    inout \out2+ ;
    inout \out2- ;
    inout \out3+ ;
    inout \out3- ;
    inout \out4+ ;
    inout \out4- ;
    inout \out5+ ;
    inout \out5- ;
    inout \out6+ ;
    inout \out6- ;
    inout \out7+ ;
    inout \out7- ;
    inout \out8+ ;
    inout \out8- ;
    inout \out9+ ;
    inout \out9- ;
    inout \ref+ ;
    inout \ref- ;
    inout sclk;
    inout \sd# ;
    inout sdi;
    inout sdo;
    inout stat;
    inout \vco+ ;
    inout \vco- ;
    inout \vcp+ ;
    inout \vd+ ;
    inout [10:0] \vout+ ;
    inout \vref+ ;
    inout \vvco+ ;


    initial
        begin
        end

endmodule
