// generated by newgenasym  Sun Jan 06 15:22:43 2019


module dp_o11f_o11h (gnd_3, nc_2, nc_5, output_4, vc_1, vcc_6);
    inout gnd_3;
    inout nc_2;
    inout nc_5;
    inout output_4;
    inout vc_1;
    inout vcc_6;


    initial
        begin
        end

endmodule
