// generated by newgenasym  Tue Dec 20 14:09:38 2016


module mic_mt41kxxxmxhx (a0, a1, \a10/ap , a11, \a12/bc# , a13, a14, a15, a2, a3, a4, a5, a6,
        a7, a8, a9, ba0, ba1, ba2, \cas# , ck, \ck# , cke, \cs# , dq0, dq1, dq10,
        dq11, dq12, dq13, dq14, dq15, dq2, dq3, dq4, dq5, dq6, dq7, dq8,
        dq9, ldm, ldqs, \ldqs# , nc, odt, \ras# , \reset# , udm, udqs, \udqs# ,
        vdd, vddq, vrefca, vrefdq, vss, vssq, \we# , zq);
    inout a0;
    inout a1;
    inout \a10/ap ;
    inout a11;
    inout \a12/bc# ;
    inout a13;
    input a14;
    input a15;
    inout a2;
    inout a3;
    inout a4;
    inout a5;
    inout a6;
    inout a7;
    inout a8;
    inout a9;
    inout ba0;
    inout ba1;
    inout ba2;
    inout \cas# ;
    inout ck;
    inout \ck# ;
    inout cke;
    inout \cs# ;
    inout dq0;
    inout dq1;
    inout dq10;
    inout dq11;
    inout dq12;
    inout dq13;
    inout dq14;
    inout dq15;
    inout dq2;
    inout dq3;
    inout dq4;
    inout dq5;
    inout dq6;
    inout dq7;
    inout dq8;
    inout dq9;
    inout ldm;
    inout ldqs;
    inout \ldqs# ;
    inout [3:0] nc;
    inout odt;
    inout \ras# ;
    inout \reset# ;
    inout udm;
    inout udqs;
    inout \udqs# ;
    input [8:0] vdd;
    input [8:0] vddq;
    inout vrefca;
    inout vrefdq;
    input [11:0] vss;
    input [8:0] vssq;
    inout \we# ;
    inout zq;


    initial
        begin
        end

endmodule
