-- generated by newgenasym Fri Sep 03 09:39:49 2010

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity sem_sc431cskqtrt is
    port (    
	ANODE:     INOUT  STD_LOGIC;    
	CATHODE:   INOUT  STD_LOGIC;    
	REFERENCE: INOUT  STD_LOGIC);
end sem_sc431cskqtrt;
