// generated by newgenasym  Fri May 11 21:10:57 2018


module xl_xc7z045i900 (cfgbvs_0, done_0, dxn_0, dxp_0, gnd_a1, gnd_a11, gnd_a21,
        gnd_aa1, gnd_aa10, gnd_aa11, gnd_aa21, gnd_aa5, gnd_ab11,
        gnd_ab18, gnd_ab28, gnd_ab3, gnd_ab7, gnd_ac1, gnd_ac11,
        gnd_ac15, gnd_ac25, gnd_ac5, gnd_ac9, gnd_ad11, gnd_ad12,
        gnd_ad22, gnd_ad3, gnd_ad7, gnd_ae1, gnd_ae11, gnd_ae19,
        gnd_ae29, gnd_ae5, gnd_ae9, gnd_af11, gnd_af16, gnd_af26,
        gnd_af3, gnd_af7, gnd_ag1, gnd_ag11, gnd_ag13, gnd_ag23,
        gnd_ag5, gnd_ag9, gnd_ah11, gnd_ah20, gnd_ah3, gnd_ah30,
        gnd_ah7, gnd_aj1, gnd_aj11, gnd_aj17, gnd_aj27, gnd_aj5,
        gnd_aj9, gnd_ak11, gnd_ak14, gnd_ak24, gnd_ak3, gnd_ak7,
        gnd_b18, gnd_b28, gnd_b8, gnd_c15, gnd_c25, gnd_c5, gnd_d12,
        gnd_d2, gnd_d22, gnd_e19, gnd_e29, gnd_e9, gnd_f16, gnd_f26,
        gnd_f6, gnd_g13, gnd_g23, gnd_g3, gnd_h10, gnd_h20, gnd_h30,
        gnd_j17, gnd_j27, gnd_j7, gnd_k14, gnd_k24, gnd_k4, gnd_l11,
        gnd_l21, gnd_m1, gnd_m14, gnd_m18, gnd_m2, gnd_m28, gnd_m3,
        gnd_m4, gnd_m5, gnd_m6, gnd_m7, gnd_m8, gnd_m9, gnd_n1,
        gnd_n11, gnd_n13, gnd_n15, gnd_n17, gnd_n19, gnd_n25,
        gnd_n5, gnd_n9, gnd_p12, gnd_p16, gnd_p18, gnd_p20, gnd_p22,
        gnd_p3, gnd_p7, gnd_r1, gnd_r11, gnd_r13, gnd_r17, gnd_r19,
        gnd_r29, gnd_r5, gnd_t10, gnd_t12, gnd_t16, gnd_t18,
        gnd_t20, gnd_t26, gnd_t3, gnd_t8, gnd_u1, gnd_u11, gnd_u13,
        gnd_u17, gnd_u19, gnd_u23, gnd_u5, gnd_v12, gnd_v14,
        gnd_v16, gnd_v18, gnd_v20, gnd_v3, gnd_v30, gnd_v8, gnd_w1,
        gnd_w11, gnd_w13, gnd_w15, gnd_w17, gnd_w19, gnd_w27,
        gnd_w5, gnd_y14, gnd_y16, gnd_y18, gnd_y24, gnd_y3, gnd_y7,
        gndadc_0, init_b_0, io_0_10, io_0_11, io_0_12, io_0_13,
        io_0_vrn_33, io_0_vrn_34, io_0_vrn_35, io_25_10, io_25_11,
        io_25_12, io_25_13, io_25_vrp_33, io_25_vrp_34,
        io_25_vrp_35, io_l10n_t1_10, io_l10n_t1_11,
        io_l10n_t1_12, io_l10n_t1_13, io_l10n_t1_33,
        io_l10n_t1_34, io_l10n_t1_ad11n_35, io_l10p_t1_10,
        io_l10p_t1_11, io_l10p_t1_12, io_l10p_t1_13,
        io_l10p_t1_33, io_l10p_t1_34, io_l10p_t1_ad11p_35,
        io_l11n_t1_srcc_10, io_l11n_t1_srcc_11,
        io_l11n_t1_srcc_12, io_l11n_t1_srcc_13,
        io_l11n_t1_srcc_33, io_l11n_t1_srcc_34,
        io_l11n_t1_srcc_35, io_l11n_t1_srcc_9,
        io_l11p_t1_srcc_10, io_l11p_t1_srcc_11,
        io_l11p_t1_srcc_12, io_l11p_t1_srcc_13,
        io_l11p_t1_srcc_33, io_l11p_t1_srcc_34,
        io_l11p_t1_srcc_35, io_l11p_t1_srcc_9,
        io_l12n_t1_mrcc_10, io_l12n_t1_mrcc_11,
        io_l12n_t1_mrcc_12, io_l12n_t1_mrcc_13,
        io_l12n_t1_mrcc_33, io_l12n_t1_mrcc_34,
        io_l12n_t1_mrcc_35, io_l12n_t1_mrcc_9,
        io_l12p_t1_mrcc_10, io_l12p_t1_mrcc_11,
        io_l12p_t1_mrcc_12, io_l12p_t1_mrcc_13,
        io_l12p_t1_mrcc_33, io_l12p_t1_mrcc_34,
        io_l12p_t1_mrcc_35, io_l12p_t1_mrcc_9,
        io_l13n_t2_mrcc_10, io_l13n_t2_mrcc_11,
        io_l13n_t2_mrcc_12, io_l13n_t2_mrcc_13,
        io_l13n_t2_mrcc_33, io_l13n_t2_mrcc_34,
        io_l13n_t2_mrcc_35, io_l13n_t2_mrcc_9,
        io_l13p_t2_mrcc_10, io_l13p_t2_mrcc_11,
        io_l13p_t2_mrcc_12, io_l13p_t2_mrcc_13,
        io_l13p_t2_mrcc_33, io_l13p_t2_mrcc_34,
        io_l13p_t2_mrcc_35, io_l13p_t2_mrcc_9,
        io_l14n_t2_ad4n_srcc_35, io_l14n_t2_srcc_10,
        io_l14n_t2_srcc_11, io_l14n_t2_srcc_12,
        io_l14n_t2_srcc_13, io_l14n_t2_srcc_33,
        io_l14n_t2_srcc_34, io_l14n_t2_srcc_9,
        io_l14p_t2_ad4p_srcc_35, io_l14p_t2_srcc_10,
        io_l14p_t2_srcc_11, io_l14p_t2_srcc_12,
        io_l14p_t2_srcc_13, io_l14p_t2_srcc_33,
        io_l14p_t2_srcc_34, io_l14p_t2_srcc_9,
        io_l15n_t2_dqs_10, io_l15n_t2_dqs_11, io_l15n_t2_dqs_12,
        io_l15n_t2_dqs_13, io_l15n_t2_dqs_33, io_l15n_t2_dqs_34,
        io_l15n_t2_dqs_ad12n_35, io_l15p_t2_dqs_10,
        io_l15p_t2_dqs_11, io_l15p_t2_dqs_12, io_l15p_t2_dqs_13,
        io_l15p_t2_dqs_33, io_l15p_t2_dqs_34,
        io_l15p_t2_dqs_ad12p_35, io_l16n_t2_10, io_l16n_t2_11,
        io_l16n_t2_12, io_l16n_t2_13, io_l16n_t2_33,
        io_l16n_t2_34, io_l16n_t2_35, io_l16p_t2_10,
        io_l16p_t2_11, io_l16p_t2_12, io_l16p_t2_13,
        io_l16p_t2_33, io_l16p_t2_34, io_l16p_t2_35,
        io_l17n_t2_10, io_l17n_t2_11, io_l17n_t2_12,
        io_l17n_t2_13, io_l17n_t2_33, io_l17n_t2_34,
        io_l17n_t2_ad5n_35, io_l17p_t2_10, io_l17p_t2_11,
        io_l17p_t2_12, io_l17p_t2_13, io_l17p_t2_33,
        io_l17p_t2_34, io_l17p_t2_ad5p_35, io_l18n_t2_10,
        io_l18n_t2_11, io_l18n_t2_12, io_l18n_t2_13,
        io_l18n_t2_33, io_l18n_t2_34, io_l18n_t2_ad13n_35,
        io_l18p_t2_10, io_l18p_t2_11, io_l18p_t2_12,
        io_l18p_t2_13, io_l18p_t2_33, io_l18p_t2_34,
        io_l18p_t2_ad13p_35, io_l19n_t3_vref_10,
        io_l19n_t3_vref_11, io_l19n_t3_vref_12,
        io_l19n_t3_vref_13, io_l19n_t3_vref_33,
        io_l19n_t3_vref_34, io_l19n_t3_vref_35,
        io_l19n_t3_vref_9, io_l19p_t3_10, io_l19p_t3_11,
        io_l19p_t3_12, io_l19p_t3_13, io_l19p_t3_33,
        io_l19p_t3_34, io_l19p_t3_35, io_l19p_t3_9, io_l1n_t0_10,
        io_l1n_t0_11, io_l1n_t0_12, io_l1n_t0_13, io_l1n_t0_33,
        io_l1n_t0_34, io_l1n_t0_ad0n_35, io_l1p_t0_10,
        io_l1p_t0_11, io_l1p_t0_12, io_l1p_t0_13, io_l1p_t0_33,
        io_l1p_t0_34, io_l1p_t0_ad0p_35, io_l20n_t3_10,
        io_l20n_t3_11, io_l20n_t3_12, io_l20n_t3_13,
        io_l20n_t3_33, io_l20n_t3_34, io_l20n_t3_ad6n_35,
        io_l20p_t3_10, io_l20p_t3_11, io_l20p_t3_12,
        io_l20p_t3_13, io_l20p_t3_33, io_l20p_t3_34,
        io_l20p_t3_ad6p_35, io_l21n_t3_dqs_10,
        io_l21n_t3_dqs_11, io_l21n_t3_dqs_12, io_l21n_t3_dqs_13,
        io_l21n_t3_dqs_33, io_l21n_t3_dqs_34,
        io_l21n_t3_dqs_ad14n_35, io_l21p_t3_dqs_10,
        io_l21p_t3_dqs_11, io_l21p_t3_dqs_12, io_l21p_t3_dqs_13,
        io_l21p_t3_dqs_33, io_l21p_t3_dqs_34,
        io_l21p_t3_dqs_ad14p_35, io_l22n_t3_10, io_l22n_t3_11,
        io_l22n_t3_12, io_l22n_t3_13, io_l22n_t3_33,
        io_l22n_t3_34, io_l22n_t3_ad7n_35, io_l22p_t3_10,
        io_l22p_t3_11, io_l22p_t3_12, io_l22p_t3_13,
        io_l22p_t3_33, io_l22p_t3_34, io_l22p_t3_ad7p_35,
        io_l23n_t3_10, io_l23n_t3_11, io_l23n_t3_12,
        io_l23n_t3_13, io_l23n_t3_33, io_l23n_t3_34,
        io_l23n_t3_35, io_l23p_t3_10, io_l23p_t3_11,
        io_l23p_t3_12, io_l23p_t3_13, io_l23p_t3_33,
        io_l23p_t3_34, io_l23p_t3_35, io_l24n_t3_10,
        io_l24n_t3_11, io_l24n_t3_12, io_l24n_t3_13,
        io_l24n_t3_33, io_l24n_t3_34, io_l24n_t3_ad15n_35,
        io_l24p_t3_10, io_l24p_t3_11, io_l24p_t3_12,
        io_l24p_t3_13, io_l24p_t3_33, io_l24p_t3_34,
        io_l24p_t3_ad15p_35, io_l2n_t0_10, io_l2n_t0_11,
        io_l2n_t0_12, io_l2n_t0_13, io_l2n_t0_33, io_l2n_t0_34,
        io_l2n_t0_ad8n_35, io_l2p_t0_10, io_l2p_t0_11,
        io_l2p_t0_12, io_l2p_t0_13, io_l2p_t0_33, io_l2p_t0_34,
        io_l2p_t0_ad8p_35, io_l3n_t0_dqs_10, io_l3n_t0_dqs_11,
        io_l3n_t0_dqs_12, io_l3n_t0_dqs_13, io_l3n_t0_dqs_33,
        io_l3n_t0_dqs_34, io_l3n_t0_dqs_ad1n_35,
        io_l3p_t0_dqs_10, io_l3p_t0_dqs_11, io_l3p_t0_dqs_12,
        io_l3p_t0_dqs_13, io_l3p_t0_dqs_33,
        io_l3p_t0_dqs_ad1p_35, io_l3p_t0_dqs_pudc_b_34,
        io_l4n_t0_10, io_l4n_t0_11, io_l4n_t0_12, io_l4n_t0_13,
        io_l4n_t0_33, io_l4n_t0_34, io_l4n_t0_35, io_l4p_t0_10,
        io_l4p_t0_11, io_l4p_t0_12, io_l4p_t0_13, io_l4p_t0_33,
        io_l4p_t0_34, io_l4p_t0_35, io_l5n_t0_10, io_l5n_t0_11,
        io_l5n_t0_12, io_l5n_t0_13, io_l5n_t0_33, io_l5n_t0_34,
        io_l5n_t0_ad9n_35, io_l5p_t0_10, io_l5p_t0_11,
        io_l5p_t0_12, io_l5p_t0_13, io_l5p_t0_33, io_l5p_t0_34,
        io_l5p_t0_ad9p_35, io_l6n_t0_vref_10, io_l6n_t0_vref_11,
        io_l6n_t0_vref_12, io_l6n_t0_vref_13, io_l6n_t0_vref_33,
        io_l6n_t0_vref_34, io_l6n_t0_vref_35, io_l6n_t0_vref_9,
        io_l6p_t0_10, io_l6p_t0_11, io_l6p_t0_12, io_l6p_t0_13,
        io_l6p_t0_33, io_l6p_t0_34, io_l6p_t0_35, io_l6p_t0_9,
        io_l7n_t1_10, io_l7n_t1_11, io_l7n_t1_12, io_l7n_t1_13,
        io_l7n_t1_33, io_l7n_t1_34, io_l7n_t1_ad2n_35,
        io_l7p_t1_10, io_l7p_t1_11, io_l7p_t1_12, io_l7p_t1_13,
        io_l7p_t1_33, io_l7p_t1_34, io_l7p_t1_ad2p_35,
        io_l8n_t1_10, io_l8n_t1_11, io_l8n_t1_12, io_l8n_t1_13,
        io_l8n_t1_33, io_l8n_t1_34, io_l8n_t1_ad10n_35,
        io_l8p_t1_10, io_l8p_t1_11, io_l8p_t1_12, io_l8p_t1_13,
        io_l8p_t1_33, io_l8p_t1_34, io_l8p_t1_ad10p_35,
        io_l9n_t1_dqs_10, io_l9n_t1_dqs_11, io_l9n_t1_dqs_12,
        io_l9n_t1_dqs_13, io_l9n_t1_dqs_33, io_l9n_t1_dqs_34,
        io_l9n_t1_dqs_ad3n_35, io_l9p_t1_dqs_10,
        io_l9p_t1_dqs_11, io_l9p_t1_dqs_12, io_l9p_t1_dqs_13,
        io_l9p_t1_dqs_33, io_l9p_t1_dqs_34,
        io_l9p_t1_dqs_ad3p_35, mgtavcc_aa6, mgtavcc_ab8,
        mgtavcc_ac10, mgtavcc_ac6, mgtavcc_ad8, mgtavcc_ae10,
        mgtavcc_ae6, mgtavcc_af8, mgtavcc_ag10, mgtavcc_ah8,
        mgtavcc_aj10, mgtavcc_n6, mgtavcc_p8, mgtavcc_r6,
        mgtavcc_u6, mgtavcc_w6, mgtavcc_y8, mgtavtt_aa2,
        mgtavtt_ab4, mgtavtt_ac2, mgtavtt_ad4, mgtavtt_ae2,
        mgtavtt_af4, mgtavtt_ag2, mgtavtt_ag6, mgtavtt_ah4,
        mgtavtt_aj2, mgtavtt_aj6, mgtavtt_ak4, mgtavtt_ak8,
        mgtavtt_n2, mgtavtt_p4, mgtavtt_r2, mgtavtt_t4,
        mgtavtt_u2, mgtavtt_v4, mgtavtt_w2, mgtavtt_y4,
        mgtavttrcal_112, mgtrefclk0n_109, mgtrefclk0n_110,
        mgtrefclk0n_111, mgtrefclk0n_112, mgtrefclk0p_109,
        mgtrefclk0p_110, mgtrefclk0p_111, mgtrefclk0p_112,
        mgtrefclk1n_109, mgtrefclk1n_110, mgtrefclk1n_111,
        mgtrefclk1n_112, mgtrefclk1p_109, mgtrefclk1p_110,
        mgtrefclk1p_111, mgtrefclk1p_112, mgtrref_112,
        mgtvccaux_t7, mgtvccaux_v7, mgtxrxn0_109, mgtxrxn0_110,
        mgtxrxn0_111, mgtxrxn0_112, mgtxrxn1_109, mgtxrxn1_110,
        mgtxrxn1_111, mgtxrxn1_112, mgtxrxn2_109, mgtxrxn2_110,
        mgtxrxn2_111, mgtxrxn2_112, mgtxrxn3_109, mgtxrxn3_110,
        mgtxrxn3_111, mgtxrxn3_112, mgtxrxp0_109, mgtxrxp0_110,
        mgtxrxp0_111, mgtxrxp0_112, mgtxrxp1_109, mgtxrxp1_110,
        mgtxrxp1_111, mgtxrxp1_112, mgtxrxp2_109, mgtxrxp2_110,
        mgtxrxp2_111, mgtxrxp2_112, mgtxrxp3_109, mgtxrxp3_110,
        mgtxrxp3_111, mgtxrxp3_112, mgtxtxn0_109, mgtxtxn0_110,
        mgtxtxn0_111, mgtxtxn0_112, mgtxtxn1_109, mgtxtxn1_110,
        mgtxtxn1_111, mgtxtxn1_112, mgtxtxn2_109, mgtxtxn2_110,
        mgtxtxn2_111, mgtxtxn2_112, mgtxtxn3_109, mgtxtxn3_110,
        mgtxtxn3_111, mgtxtxn3_112, mgtxtxp0_109, mgtxtxp0_110,
        mgtxtxp0_111, mgtxtxp0_112, mgtxtxp1_109, mgtxtxp1_110,
        mgtxtxp1_111, mgtxtxp1_112, mgtxtxp2_109, mgtxtxp2_110,
        mgtxtxp2_111, mgtxtxp2_112, mgtxtxp3_109, mgtxtxp3_110,
        mgtxtxp3_111, mgtxtxp3_112, program_b_0, ps_clk_500,
        ps_ddr_a0_502, ps_ddr_a10_502, ps_ddr_a11_502,
        ps_ddr_a12_502, ps_ddr_a13_502, ps_ddr_a14_502,
        ps_ddr_a1_502, ps_ddr_a2_502, ps_ddr_a3_502,
        ps_ddr_a4_502, ps_ddr_a5_502, ps_ddr_a6_502,
        ps_ddr_a7_502, ps_ddr_a8_502, ps_ddr_a9_502,
        ps_ddr_ba0_502, ps_ddr_ba1_502, ps_ddr_ba2_502,
        ps_ddr_cas_b_502, ps_ddr_cke_502, ps_ddr_ckn_502,
        ps_ddr_ckp_502, ps_ddr_cs_b_502, ps_ddr_dm0_502,
        ps_ddr_dm1_502, ps_ddr_dm2_502, ps_ddr_dm3_502,
        ps_ddr_dq0_502, ps_ddr_dq10_502, ps_ddr_dq11_502,
        ps_ddr_dq12_502, ps_ddr_dq13_502, ps_ddr_dq14_502,
        ps_ddr_dq15_502, ps_ddr_dq16_502, ps_ddr_dq17_502,
        ps_ddr_dq18_502, ps_ddr_dq19_502, ps_ddr_dq1_502,
        ps_ddr_dq20_502, ps_ddr_dq21_502, ps_ddr_dq22_502,
        ps_ddr_dq23_502, ps_ddr_dq24_502, ps_ddr_dq25_502,
        ps_ddr_dq26_502, ps_ddr_dq27_502, ps_ddr_dq28_502,
        ps_ddr_dq29_502, ps_ddr_dq2_502, ps_ddr_dq30_502,
        ps_ddr_dq31_502, ps_ddr_dq3_502, ps_ddr_dq4_502,
        ps_ddr_dq5_502, ps_ddr_dq6_502, ps_ddr_dq7_502,
        ps_ddr_dq8_502, ps_ddr_dq9_502, ps_ddr_dqs_n0_502,
        ps_ddr_dqs_n1_502, ps_ddr_dqs_n2_502, ps_ddr_dqs_n3_502,
        ps_ddr_dqs_p0_502, ps_ddr_dqs_p1_502, ps_ddr_dqs_p2_502,
        ps_ddr_dqs_p3_502, ps_ddr_drst_b_502, ps_ddr_odt_502,
        ps_ddr_ras_b_502, ps_ddr_vref0_502, ps_ddr_vref1_502,
        ps_ddr_vrn_502, ps_ddr_vrp_502, ps_ddr_we_b_502,
        ps_mio0_500, ps_mio10_500, ps_mio11_500, ps_mio12_500,
        ps_mio13_500, ps_mio14_500, ps_mio15_500, ps_mio16_501,
        ps_mio17_501, ps_mio18_501, ps_mio19_501, ps_mio1_500,
        ps_mio20_501, ps_mio21_501, ps_mio22_501, ps_mio23_501,
        ps_mio24_501, ps_mio25_501, ps_mio26_501, ps_mio27_501,
        ps_mio28_501, ps_mio29_501, ps_mio2_500, ps_mio30_501,
        ps_mio31_501, ps_mio32_501, ps_mio33_501, ps_mio34_501,
        ps_mio35_501, ps_mio36_501, ps_mio37_501, ps_mio38_501,
        ps_mio39_501, ps_mio3_500, ps_mio40_501, ps_mio41_501,
        ps_mio42_501, ps_mio43_501, ps_mio44_501, ps_mio45_501,
        ps_mio46_501, ps_mio47_501, ps_mio48_501, ps_mio49_501,
        ps_mio4_500, ps_mio50_501, ps_mio51_501, ps_mio52_501,
        ps_mio53_501, ps_mio5_500, ps_mio6_500, ps_mio7_500,
        ps_mio8_500, ps_mio9_500, ps_mio_vref_501, ps_por_b_500,
        ps_srst_b_501, rsvdgnd, rsvdvcc1, rsvdvcc2, rsvdvcc3,
        tck_0, tdi_0, tdo_0, tms_0, vccadc_0, vccaux_io_g0_p11,
        vccaux_io_g0_t11, vccaux_io_g0_v11, vccaux_m11,
        vccaux_n10, vccaux_r10, vccaux_u10, vccaux_w10,
        vccaux_y11, vccbatt_0, vccbram_v17, vccbram_v19,
        vccbram_w18, vccbram_w20, vccint_m13, vccint_m15,
        vccint_n12, vccint_n14, vccint_p13, vccint_r12,
        vccint_r16, vccint_t13, vccint_u12, vccint_u16,
        vccint_v13, vccint_v15, vccint_w12, vccint_w14,
        vccint_w16, vccint_y17, vcco_0_y13, vcco_0_y15,
        vcco_10_aa16, vcco_10_ab13, vcco_10_ad17, vcco_10_ae14,
        vcco_10_ag18, vcco_10_ah15, vcco_10_aj12, vcco_11_ab23,
        vcco_11_ae24, vcco_11_af21, vcco_11_ah25, vcco_11_aj22,
        vcco_11_ak19, vcco_11_w22, vcco_12_aa26, vcco_12_ac30,
        vcco_12_ad27, vcco_12_ag28, vcco_12_ak29, vcco_12_y29,
        vcco_13_n30, vcco_13_p27, vcco_13_r24, vcco_13_t21,
        vcco_13_u28, vcco_13_v25, vcco_33_b3, vcco_33_e4,
        vcco_33_f1, vcco_33_h5, vcco_33_j2, vcco_33_l6,
        vcco_34_a6, vcco_34_c10, vcco_34_d7, vcco_34_f11,
        vcco_34_g8, vcco_34_j12, vcco_34_k9, vcco_35_a16,
        vcco_35_b13, vcco_35_d17, vcco_35_e14, vcco_35_h15,
        vcco_35_l16, vcco_9_ac20, vcco_9_y19, vcco_ddr_502_a26,
        vcco_ddr_502_c30, vcco_ddr_502_d27, vcco_ddr_502_g28,
        vcco_ddr_502_h25, vcco_ddr_502_k29, vcco_ddr_502_l26,
        vcco_ddr_502_m23, vcco_mio0_500_b23, vcco_mio0_500_e24,
        vcco_mio0_500_f21, vcco_mio1_501_c20, vcco_mio1_501_g18,
        vcco_mio1_501_j22, vcco_mio1_501_k19, vccpaux_n20,
        vccpaux_p19, vccpaux_r20, vccpaux_u20, vccpint_n16,
        vccpint_p17, vccpint_r18, vccpint_t17, vccpint_t19,
        vccpint_u18, vccpll, vn_0, vp_0, vrefn_0, vrefp_0);
    output cfgbvs_0;
    output done_0;
    output dxn_0;
    output dxp_0;
    input gnd_a1;
    input gnd_a11;
    input gnd_a21;
    input gnd_aa1;
    input gnd_aa10;
    input gnd_aa11;
    input gnd_aa21;
    input gnd_aa5;
    input gnd_ab11;
    input gnd_ab18;
    input gnd_ab28;
    input gnd_ab3;
    input gnd_ab7;
    input gnd_ac1;
    input gnd_ac11;
    input gnd_ac15;
    input gnd_ac25;
    input gnd_ac5;
    input gnd_ac9;
    input gnd_ad11;
    input gnd_ad12;
    input gnd_ad22;
    input gnd_ad3;
    input gnd_ad7;
    input gnd_ae1;
    input gnd_ae11;
    input gnd_ae19;
    input gnd_ae29;
    input gnd_ae5;
    input gnd_ae9;
    input gnd_af11;
    input gnd_af16;
    input gnd_af26;
    input gnd_af3;
    input gnd_af7;
    input gnd_ag1;
    input gnd_ag11;
    input gnd_ag13;
    input gnd_ag23;
    input gnd_ag5;
    input gnd_ag9;
    input gnd_ah11;
    input gnd_ah20;
    input gnd_ah3;
    input gnd_ah30;
    input gnd_ah7;
    input gnd_aj1;
    input gnd_aj11;
    input gnd_aj17;
    input gnd_aj27;
    input gnd_aj5;
    input gnd_aj9;
    input gnd_ak11;
    input gnd_ak14;
    input gnd_ak24;
    input gnd_ak3;
    input gnd_ak7;
    input gnd_b18;
    input gnd_b28;
    input gnd_b8;
    input gnd_c15;
    input gnd_c25;
    input gnd_c5;
    output gnd_d12;
    output gnd_d2;
    output gnd_d22;
    output gnd_e19;
    output gnd_e29;
    output gnd_e9;
    output gnd_f16;
    output gnd_f26;
    output gnd_f6;
    output gnd_g13;
    output gnd_g23;
    output gnd_g3;
    output gnd_h10;
    output gnd_h20;
    output gnd_h30;
    output gnd_j17;
    output gnd_j27;
    output gnd_j7;
    output gnd_k14;
    output gnd_k24;
    output gnd_k4;
    output gnd_l11;
    output gnd_l21;
    output gnd_m1;
    output gnd_m14;
    output gnd_m18;
    output gnd_m2;
    output gnd_m28;
    output gnd_m3;
    output gnd_m4;
    output gnd_m5;
    output gnd_m6;
    output gnd_m7;
    output gnd_m8;
    output gnd_m9;
    input gnd_n1;
    input gnd_n11;
    input gnd_n13;
    input gnd_n15;
    input gnd_n17;
    input gnd_n19;
    input gnd_n25;
    input gnd_n5;
    input gnd_n9;
    input gnd_p12;
    input gnd_p16;
    input gnd_p18;
    input gnd_p20;
    input gnd_p22;
    input gnd_p3;
    input gnd_p7;
    output gnd_r1;
    output gnd_r11;
    output gnd_r13;
    output gnd_r17;
    output gnd_r19;
    output gnd_r29;
    output gnd_r5;
    output gnd_t10;
    output gnd_t12;
    output gnd_t16;
    output gnd_t18;
    output gnd_t20;
    output gnd_t26;
    output gnd_t3;
    output gnd_t8;
    output gnd_u1;
    output gnd_u11;
    output gnd_u13;
    output gnd_u17;
    output gnd_u19;
    output gnd_u23;
    output gnd_u5;
    output gnd_v12;
    output gnd_v14;
    output gnd_v16;
    output gnd_v18;
    output gnd_v20;
    output gnd_v3;
    output gnd_v30;
    output gnd_v8;
    output gnd_w1;
    output gnd_w11;
    output gnd_w13;
    output gnd_w15;
    output gnd_w17;
    output gnd_w19;
    output gnd_w27;
    output gnd_w5;
    output gnd_y14;
    output gnd_y16;
    output gnd_y18;
    output gnd_y24;
    output gnd_y3;
    output gnd_y7;
    output gndadc_0;
    output init_b_0;
    output io_0_10;
    output io_0_11;
    output io_0_12;
    output io_0_13;
    output io_0_vrn_33;
    output io_0_vrn_34;
    output io_0_vrn_35;
    output io_25_10;
    output io_25_11;
    output io_25_12;
    output io_25_13;
    output io_25_vrp_33;
    output io_25_vrp_34;
    output io_25_vrp_35;
    output io_l10n_t1_10;
    output io_l10n_t1_11;
    output io_l10n_t1_12;
    output io_l10n_t1_13;
    output io_l10n_t1_33;
    output io_l10n_t1_34;
    output io_l10n_t1_ad11n_35;
    output io_l10p_t1_10;
    output io_l10p_t1_11;
    output io_l10p_t1_12;
    output io_l10p_t1_13;
    output io_l10p_t1_33;
    output io_l10p_t1_34;
    output io_l10p_t1_ad11p_35;
    output io_l11n_t1_srcc_10;
    output io_l11n_t1_srcc_11;
    output io_l11n_t1_srcc_12;
    output io_l11n_t1_srcc_13;
    output io_l11n_t1_srcc_33;
    output io_l11n_t1_srcc_34;
    output io_l11n_t1_srcc_35;
    output io_l11n_t1_srcc_9;
    output io_l11p_t1_srcc_10;
    output io_l11p_t1_srcc_11;
    output io_l11p_t1_srcc_12;
    output io_l11p_t1_srcc_13;
    output io_l11p_t1_srcc_33;
    output io_l11p_t1_srcc_34;
    output io_l11p_t1_srcc_35;
    output io_l11p_t1_srcc_9;
    output io_l12n_t1_mrcc_10;
    output io_l12n_t1_mrcc_11;
    output io_l12n_t1_mrcc_12;
    output io_l12n_t1_mrcc_13;
    output io_l12n_t1_mrcc_33;
    output io_l12n_t1_mrcc_34;
    output io_l12n_t1_mrcc_35;
    output io_l12n_t1_mrcc_9;
    output io_l12p_t1_mrcc_10;
    output io_l12p_t1_mrcc_11;
    output io_l12p_t1_mrcc_12;
    output io_l12p_t1_mrcc_13;
    output io_l12p_t1_mrcc_33;
    output io_l12p_t1_mrcc_34;
    output io_l12p_t1_mrcc_35;
    output io_l12p_t1_mrcc_9;
    output io_l13n_t2_mrcc_10;
    output io_l13n_t2_mrcc_11;
    output io_l13n_t2_mrcc_12;
    output io_l13n_t2_mrcc_13;
    output io_l13n_t2_mrcc_33;
    output io_l13n_t2_mrcc_34;
    output io_l13n_t2_mrcc_35;
    output io_l13n_t2_mrcc_9;
    output io_l13p_t2_mrcc_10;
    output io_l13p_t2_mrcc_11;
    output io_l13p_t2_mrcc_12;
    output io_l13p_t2_mrcc_13;
    output io_l13p_t2_mrcc_33;
    output io_l13p_t2_mrcc_34;
    output io_l13p_t2_mrcc_35;
    output io_l13p_t2_mrcc_9;
    output io_l14n_t2_ad4n_srcc_35;
    output io_l14n_t2_srcc_10;
    output io_l14n_t2_srcc_11;
    output io_l14n_t2_srcc_12;
    output io_l14n_t2_srcc_13;
    output io_l14n_t2_srcc_33;
    output io_l14n_t2_srcc_34;
    output io_l14n_t2_srcc_9;
    output io_l14p_t2_ad4p_srcc_35;
    output io_l14p_t2_srcc_10;
    output io_l14p_t2_srcc_11;
    output io_l14p_t2_srcc_12;
    output io_l14p_t2_srcc_13;
    output io_l14p_t2_srcc_33;
    output io_l14p_t2_srcc_34;
    output io_l14p_t2_srcc_9;
    output io_l15n_t2_dqs_10;
    output io_l15n_t2_dqs_11;
    output io_l15n_t2_dqs_12;
    output io_l15n_t2_dqs_13;
    output io_l15n_t2_dqs_33;
    output io_l15n_t2_dqs_34;
    output io_l15n_t2_dqs_ad12n_35;
    output io_l15p_t2_dqs_10;
    output io_l15p_t2_dqs_11;
    output io_l15p_t2_dqs_12;
    output io_l15p_t2_dqs_13;
    output io_l15p_t2_dqs_33;
    output io_l15p_t2_dqs_34;
    output io_l15p_t2_dqs_ad12p_35;
    output io_l16n_t2_10;
    output io_l16n_t2_11;
    output io_l16n_t2_12;
    output io_l16n_t2_13;
    output io_l16n_t2_33;
    output io_l16n_t2_34;
    output io_l16n_t2_35;
    output io_l16p_t2_10;
    output io_l16p_t2_11;
    output io_l16p_t2_12;
    output io_l16p_t2_13;
    output io_l16p_t2_33;
    output io_l16p_t2_34;
    output io_l16p_t2_35;
    output io_l17n_t2_10;
    output io_l17n_t2_11;
    output io_l17n_t2_12;
    output io_l17n_t2_13;
    output io_l17n_t2_33;
    output io_l17n_t2_34;
    output io_l17n_t2_ad5n_35;
    output io_l17p_t2_10;
    output io_l17p_t2_11;
    output io_l17p_t2_12;
    output io_l17p_t2_13;
    output io_l17p_t2_33;
    output io_l17p_t2_34;
    output io_l17p_t2_ad5p_35;
    output io_l18n_t2_10;
    output io_l18n_t2_11;
    output io_l18n_t2_12;
    output io_l18n_t2_13;
    output io_l18n_t2_33;
    output io_l18n_t2_34;
    output io_l18n_t2_ad13n_35;
    output io_l18p_t2_10;
    output io_l18p_t2_11;
    output io_l18p_t2_12;
    output io_l18p_t2_13;
    output io_l18p_t2_33;
    output io_l18p_t2_34;
    output io_l18p_t2_ad13p_35;
    output io_l19n_t3_vref_10;
    output io_l19n_t3_vref_11;
    output io_l19n_t3_vref_12;
    output io_l19n_t3_vref_13;
    output io_l19n_t3_vref_33;
    output io_l19n_t3_vref_34;
    output io_l19n_t3_vref_35;
    output io_l19n_t3_vref_9;
    output io_l19p_t3_10;
    output io_l19p_t3_11;
    output io_l19p_t3_12;
    output io_l19p_t3_13;
    output io_l19p_t3_33;
    output io_l19p_t3_34;
    output io_l19p_t3_35;
    output io_l19p_t3_9;
    output io_l1n_t0_10;
    output io_l1n_t0_11;
    output io_l1n_t0_12;
    output io_l1n_t0_13;
    output io_l1n_t0_33;
    output io_l1n_t0_34;
    output io_l1n_t0_ad0n_35;
    output io_l1p_t0_10;
    output io_l1p_t0_11;
    output io_l1p_t0_12;
    output io_l1p_t0_13;
    output io_l1p_t0_33;
    output io_l1p_t0_34;
    output io_l1p_t0_ad0p_35;
    output io_l20n_t3_10;
    output io_l20n_t3_11;
    output io_l20n_t3_12;
    output io_l20n_t3_13;
    output io_l20n_t3_33;
    output io_l20n_t3_34;
    output io_l20n_t3_ad6n_35;
    output io_l20p_t3_10;
    output io_l20p_t3_11;
    output io_l20p_t3_12;
    output io_l20p_t3_13;
    output io_l20p_t3_33;
    output io_l20p_t3_34;
    output io_l20p_t3_ad6p_35;
    output io_l21n_t3_dqs_10;
    output io_l21n_t3_dqs_11;
    output io_l21n_t3_dqs_12;
    output io_l21n_t3_dqs_13;
    output io_l21n_t3_dqs_33;
    output io_l21n_t3_dqs_34;
    output io_l21n_t3_dqs_ad14n_35;
    output io_l21p_t3_dqs_10;
    output io_l21p_t3_dqs_11;
    output io_l21p_t3_dqs_12;
    output io_l21p_t3_dqs_13;
    output io_l21p_t3_dqs_33;
    output io_l21p_t3_dqs_34;
    output io_l21p_t3_dqs_ad14p_35;
    output io_l22n_t3_10;
    output io_l22n_t3_11;
    output io_l22n_t3_12;
    output io_l22n_t3_13;
    output io_l22n_t3_33;
    output io_l22n_t3_34;
    output io_l22n_t3_ad7n_35;
    output io_l22p_t3_10;
    output io_l22p_t3_11;
    output io_l22p_t3_12;
    output io_l22p_t3_13;
    output io_l22p_t3_33;
    output io_l22p_t3_34;
    output io_l22p_t3_ad7p_35;
    output io_l23n_t3_10;
    output io_l23n_t3_11;
    output io_l23n_t3_12;
    output io_l23n_t3_13;
    output io_l23n_t3_33;
    output io_l23n_t3_34;
    output io_l23n_t3_35;
    output io_l23p_t3_10;
    output io_l23p_t3_11;
    output io_l23p_t3_12;
    output io_l23p_t3_13;
    output io_l23p_t3_33;
    output io_l23p_t3_34;
    output io_l23p_t3_35;
    output io_l24n_t3_10;
    output io_l24n_t3_11;
    output io_l24n_t3_12;
    output io_l24n_t3_13;
    output io_l24n_t3_33;
    output io_l24n_t3_34;
    output io_l24n_t3_ad15n_35;
    output io_l24p_t3_10;
    output io_l24p_t3_11;
    output io_l24p_t3_12;
    output io_l24p_t3_13;
    output io_l24p_t3_33;
    output io_l24p_t3_34;
    output io_l24p_t3_ad15p_35;
    output io_l2n_t0_10;
    output io_l2n_t0_11;
    output io_l2n_t0_12;
    output io_l2n_t0_13;
    output io_l2n_t0_33;
    output io_l2n_t0_34;
    output io_l2n_t0_ad8n_35;
    output io_l2p_t0_10;
    output io_l2p_t0_11;
    output io_l2p_t0_12;
    output io_l2p_t0_13;
    output io_l2p_t0_33;
    output io_l2p_t0_34;
    output io_l2p_t0_ad8p_35;
    output io_l3n_t0_dqs_10;
    output io_l3n_t0_dqs_11;
    output io_l3n_t0_dqs_12;
    output io_l3n_t0_dqs_13;
    output io_l3n_t0_dqs_33;
    output io_l3n_t0_dqs_34;
    output io_l3n_t0_dqs_ad1n_35;
    output io_l3p_t0_dqs_10;
    output io_l3p_t0_dqs_11;
    output io_l3p_t0_dqs_12;
    output io_l3p_t0_dqs_13;
    output io_l3p_t0_dqs_33;
    output io_l3p_t0_dqs_ad1p_35;
    output io_l3p_t0_dqs_pudc_b_34;
    output io_l4n_t0_10;
    output io_l4n_t0_11;
    output io_l4n_t0_12;
    output io_l4n_t0_13;
    output io_l4n_t0_33;
    output io_l4n_t0_34;
    output io_l4n_t0_35;
    output io_l4p_t0_10;
    output io_l4p_t0_11;
    output io_l4p_t0_12;
    output io_l4p_t0_13;
    output io_l4p_t0_33;
    output io_l4p_t0_34;
    output io_l4p_t0_35;
    output io_l5n_t0_10;
    output io_l5n_t0_11;
    output io_l5n_t0_12;
    output io_l5n_t0_13;
    output io_l5n_t0_33;
    output io_l5n_t0_34;
    output io_l5n_t0_ad9n_35;
    output io_l5p_t0_10;
    output io_l5p_t0_11;
    output io_l5p_t0_12;
    output io_l5p_t0_13;
    output io_l5p_t0_33;
    output io_l5p_t0_34;
    output io_l5p_t0_ad9p_35;
    output io_l6n_t0_vref_10;
    output io_l6n_t0_vref_11;
    output io_l6n_t0_vref_12;
    output io_l6n_t0_vref_13;
    output io_l6n_t0_vref_33;
    output io_l6n_t0_vref_34;
    output io_l6n_t0_vref_35;
    output io_l6n_t0_vref_9;
    output io_l6p_t0_10;
    output io_l6p_t0_11;
    output io_l6p_t0_12;
    output io_l6p_t0_13;
    output io_l6p_t0_33;
    output io_l6p_t0_34;
    output io_l6p_t0_35;
    output io_l6p_t0_9;
    output io_l7n_t1_10;
    output io_l7n_t1_11;
    output io_l7n_t1_12;
    output io_l7n_t1_13;
    output io_l7n_t1_33;
    output io_l7n_t1_34;
    output io_l7n_t1_ad2n_35;
    output io_l7p_t1_10;
    output io_l7p_t1_11;
    output io_l7p_t1_12;
    output io_l7p_t1_13;
    output io_l7p_t1_33;
    output io_l7p_t1_34;
    output io_l7p_t1_ad2p_35;
    output io_l8n_t1_10;
    output io_l8n_t1_11;
    output io_l8n_t1_12;
    output io_l8n_t1_13;
    output io_l8n_t1_33;
    output io_l8n_t1_34;
    output io_l8n_t1_ad10n_35;
    output io_l8p_t1_10;
    output io_l8p_t1_11;
    output io_l8p_t1_12;
    output io_l8p_t1_13;
    output io_l8p_t1_33;
    output io_l8p_t1_34;
    output io_l8p_t1_ad10p_35;
    output io_l9n_t1_dqs_10;
    output io_l9n_t1_dqs_11;
    output io_l9n_t1_dqs_12;
    output io_l9n_t1_dqs_13;
    output io_l9n_t1_dqs_33;
    output io_l9n_t1_dqs_34;
    output io_l9n_t1_dqs_ad3n_35;
    output io_l9p_t1_dqs_10;
    output io_l9p_t1_dqs_11;
    output io_l9p_t1_dqs_12;
    output io_l9p_t1_dqs_13;
    output io_l9p_t1_dqs_33;
    output io_l9p_t1_dqs_34;
    output io_l9p_t1_dqs_ad3p_35;
    input mgtavcc_aa6;
    input mgtavcc_ab8;
    input mgtavcc_ac10;
    input mgtavcc_ac6;
    input mgtavcc_ad8;
    input mgtavcc_ae10;
    input mgtavcc_ae6;
    input mgtavcc_af8;
    input mgtavcc_ag10;
    input mgtavcc_ah8;
    input mgtavcc_aj10;
    input mgtavcc_n6;
    input mgtavcc_p8;
    input mgtavcc_r6;
    input mgtavcc_u6;
    input mgtavcc_w6;
    input mgtavcc_y8;
    output mgtavtt_aa2;
    output mgtavtt_ab4;
    output mgtavtt_ac2;
    output mgtavtt_ad4;
    output mgtavtt_ae2;
    output mgtavtt_af4;
    output mgtavtt_ag2;
    output mgtavtt_ag6;
    output mgtavtt_ah4;
    output mgtavtt_aj2;
    output mgtavtt_aj6;
    output mgtavtt_ak4;
    output mgtavtt_ak8;
    output mgtavtt_n2;
    output mgtavtt_p4;
    output mgtavtt_r2;
    output mgtavtt_t4;
    output mgtavtt_u2;
    output mgtavtt_v4;
    output mgtavtt_w2;
    output mgtavtt_y4;
    output mgtavttrcal_112;
    input mgtrefclk0n_109;
    input mgtrefclk0n_110;
    input mgtrefclk0n_111;
    input mgtrefclk0n_112;
    input mgtrefclk0p_109;
    input mgtrefclk0p_110;
    input mgtrefclk0p_111;
    input mgtrefclk0p_112;
    input mgtrefclk1n_109;
    input mgtrefclk1n_110;
    input mgtrefclk1n_111;
    input mgtrefclk1n_112;
    input mgtrefclk1p_109;
    input mgtrefclk1p_110;
    input mgtrefclk1p_111;
    input mgtrefclk1p_112;
    output mgtrref_112;
    input mgtvccaux_t7;
    input mgtvccaux_v7;
    input mgtxrxn0_109;
    input mgtxrxn0_110;
    input mgtxrxn0_111;
    input mgtxrxn0_112;
    input mgtxrxn1_109;
    input mgtxrxn1_110;
    input mgtxrxn1_111;
    input mgtxrxn1_112;
    input mgtxrxn2_109;
    input mgtxrxn2_110;
    input mgtxrxn2_111;
    input mgtxrxn2_112;
    input mgtxrxn3_109;
    input mgtxrxn3_110;
    input mgtxrxn3_111;
    input mgtxrxn3_112;
    input mgtxrxp0_109;
    input mgtxrxp0_110;
    input mgtxrxp0_111;
    input mgtxrxp0_112;
    input mgtxrxp1_109;
    input mgtxrxp1_110;
    input mgtxrxp1_111;
    input mgtxrxp1_112;
    input mgtxrxp2_109;
    input mgtxrxp2_110;
    input mgtxrxp2_111;
    input mgtxrxp2_112;
    input mgtxrxp3_109;
    input mgtxrxp3_110;
    input mgtxrxp3_111;
    input mgtxrxp3_112;
    output mgtxtxn0_109;
    output mgtxtxn0_110;
    output mgtxtxn0_111;
    output mgtxtxn0_112;
    output mgtxtxn1_109;
    output mgtxtxn1_110;
    output mgtxtxn1_111;
    output mgtxtxn1_112;
    output mgtxtxn2_109;
    output mgtxtxn2_110;
    output mgtxtxn2_111;
    output mgtxtxn2_112;
    output mgtxtxn3_109;
    output mgtxtxn3_110;
    output mgtxtxn3_111;
    output mgtxtxn3_112;
    output mgtxtxp0_109;
    output mgtxtxp0_110;
    output mgtxtxp0_111;
    output mgtxtxp0_112;
    output mgtxtxp1_109;
    output mgtxtxp1_110;
    output mgtxtxp1_111;
    output mgtxtxp1_112;
    output mgtxtxp2_109;
    output mgtxtxp2_110;
    output mgtxtxp2_111;
    output mgtxtxp2_112;
    output mgtxtxp3_109;
    output mgtxtxp3_110;
    output mgtxtxp3_111;
    output mgtxtxp3_112;
    output program_b_0;
    output ps_clk_500;
    output ps_ddr_a0_502;
    output ps_ddr_a10_502;
    output ps_ddr_a11_502;
    output ps_ddr_a12_502;
    output ps_ddr_a13_502;
    output ps_ddr_a14_502;
    output ps_ddr_a1_502;
    output ps_ddr_a2_502;
    output ps_ddr_a3_502;
    output ps_ddr_a4_502;
    output ps_ddr_a5_502;
    output ps_ddr_a6_502;
    output ps_ddr_a7_502;
    output ps_ddr_a8_502;
    output ps_ddr_a9_502;
    output ps_ddr_ba0_502;
    output ps_ddr_ba1_502;
    output ps_ddr_ba2_502;
    output ps_ddr_cas_b_502;
    output ps_ddr_cke_502;
    output ps_ddr_ckn_502;
    output ps_ddr_ckp_502;
    output ps_ddr_cs_b_502;
    input ps_ddr_dm0_502;
    input ps_ddr_dm1_502;
    input ps_ddr_dm2_502;
    input ps_ddr_dm3_502;
    input ps_ddr_dq0_502;
    input ps_ddr_dq10_502;
    input ps_ddr_dq11_502;
    input ps_ddr_dq12_502;
    input ps_ddr_dq13_502;
    input ps_ddr_dq14_502;
    input ps_ddr_dq15_502;
    input ps_ddr_dq16_502;
    input ps_ddr_dq17_502;
    input ps_ddr_dq18_502;
    input ps_ddr_dq19_502;
    input ps_ddr_dq1_502;
    input ps_ddr_dq20_502;
    input ps_ddr_dq21_502;
    input ps_ddr_dq22_502;
    input ps_ddr_dq23_502;
    input ps_ddr_dq24_502;
    input ps_ddr_dq25_502;
    input ps_ddr_dq26_502;
    input ps_ddr_dq27_502;
    input ps_ddr_dq28_502;
    input ps_ddr_dq29_502;
    input ps_ddr_dq2_502;
    input ps_ddr_dq30_502;
    input ps_ddr_dq31_502;
    input ps_ddr_dq3_502;
    input ps_ddr_dq4_502;
    input ps_ddr_dq5_502;
    input ps_ddr_dq6_502;
    input ps_ddr_dq7_502;
    input ps_ddr_dq8_502;
    input ps_ddr_dq9_502;
    input ps_ddr_dqs_n0_502;
    input ps_ddr_dqs_n1_502;
    input ps_ddr_dqs_n2_502;
    input ps_ddr_dqs_n3_502;
    input ps_ddr_dqs_p0_502;
    input ps_ddr_dqs_p1_502;
    input ps_ddr_dqs_p2_502;
    input ps_ddr_dqs_p3_502;
    output ps_ddr_drst_b_502;
    output ps_ddr_odt_502;
    output ps_ddr_ras_b_502;
    output ps_ddr_vref0_502;
    output ps_ddr_vref1_502;
    output ps_ddr_vrn_502;
    output ps_ddr_vrp_502;
    output ps_ddr_we_b_502;
    output ps_mio0_500;
    output ps_mio10_500;
    output ps_mio11_500;
    output ps_mio12_500;
    output ps_mio13_500;
    output ps_mio14_500;
    output ps_mio15_500;
    output ps_mio16_501;
    output ps_mio17_501;
    output ps_mio18_501;
    output ps_mio19_501;
    output ps_mio1_500;
    output ps_mio20_501;
    output ps_mio21_501;
    output ps_mio22_501;
    output ps_mio23_501;
    output ps_mio24_501;
    output ps_mio25_501;
    output ps_mio26_501;
    output ps_mio27_501;
    output ps_mio28_501;
    output ps_mio29_501;
    output ps_mio2_500;
    output ps_mio30_501;
    output ps_mio31_501;
    output ps_mio32_501;
    output ps_mio33_501;
    output ps_mio34_501;
    output ps_mio35_501;
    output ps_mio36_501;
    output ps_mio37_501;
    output ps_mio38_501;
    output ps_mio39_501;
    output ps_mio3_500;
    output ps_mio40_501;
    output ps_mio41_501;
    output ps_mio42_501;
    output ps_mio43_501;
    output ps_mio44_501;
    output ps_mio45_501;
    output ps_mio46_501;
    output ps_mio47_501;
    output ps_mio48_501;
    output ps_mio49_501;
    output ps_mio4_500;
    output ps_mio50_501;
    output ps_mio51_501;
    output ps_mio52_501;
    output ps_mio53_501;
    output ps_mio5_500;
    output ps_mio6_500;
    output ps_mio7_500;
    output ps_mio8_500;
    output ps_mio9_500;
    output ps_mio_vref_501;
    output ps_por_b_500;
    output ps_srst_b_501;
    input rsvdgnd;
    input rsvdvcc1;
    input rsvdvcc2;
    input rsvdvcc3;
    output tck_0;
    output tdi_0;
    output tdo_0;
    output tms_0;
    output vccadc_0;
    output vccaux_io_g0_p11;
    output vccaux_io_g0_t11;
    output vccaux_io_g0_v11;
    output vccaux_m11;
    output vccaux_n10;
    output vccaux_r10;
    output vccaux_u10;
    output vccaux_w10;
    output vccaux_y11;
    output vccbatt_0;
    input vccbram_v17;
    input vccbram_v19;
    input vccbram_w18;
    input vccbram_w20;
    input vccint_m13;
    input vccint_m15;
    input vccint_n12;
    input vccint_n14;
    input vccint_p13;
    input vccint_r12;
    input vccint_r16;
    input vccint_t13;
    input vccint_u12;
    input vccint_u16;
    input vccint_v13;
    input vccint_v15;
    input vccint_w12;
    input vccint_w14;
    input vccint_w16;
    input vccint_y17;
    input vcco_0_y13;
    input vcco_0_y15;
    input vcco_10_aa16;
    input vcco_10_ab13;
    input vcco_10_ad17;
    input vcco_10_ae14;
    input vcco_10_ag18;
    input vcco_10_ah15;
    input vcco_10_aj12;
    input vcco_11_ab23;
    input vcco_11_ae24;
    input vcco_11_af21;
    input vcco_11_ah25;
    input vcco_11_aj22;
    input vcco_11_ak19;
    input vcco_11_w22;
    input vcco_12_aa26;
    input vcco_12_ac30;
    input vcco_12_ad27;
    input vcco_12_ag28;
    input vcco_12_ak29;
    input vcco_12_y29;
    input vcco_13_n30;
    input vcco_13_p27;
    input vcco_13_r24;
    input vcco_13_t21;
    input vcco_13_u28;
    input vcco_13_v25;
    input vcco_33_b3;
    input vcco_33_e4;
    input vcco_33_f1;
    input vcco_33_h5;
    input vcco_33_j2;
    input vcco_33_l6;
    input vcco_34_a6;
    input vcco_34_c10;
    input vcco_34_d7;
    input vcco_34_f11;
    input vcco_34_g8;
    input vcco_34_j12;
    input vcco_34_k9;
    input vcco_35_a16;
    input vcco_35_b13;
    input vcco_35_d17;
    input vcco_35_e14;
    input vcco_35_h15;
    input vcco_35_l16;
    input vcco_9_ac20;
    input vcco_9_y19;
    output vcco_ddr_502_a26;
    output vcco_ddr_502_c30;
    output vcco_ddr_502_d27;
    output vcco_ddr_502_g28;
    output vcco_ddr_502_h25;
    output vcco_ddr_502_k29;
    output vcco_ddr_502_l26;
    output vcco_ddr_502_m23;
    input vcco_mio0_500_b23;
    input vcco_mio0_500_e24;
    input vcco_mio0_500_f21;
    input vcco_mio1_501_c20;
    input vcco_mio1_501_g18;
    input vcco_mio1_501_j22;
    input vcco_mio1_501_k19;
    output vccpaux_n20;
    output vccpaux_p19;
    output vccpaux_r20;
    output vccpaux_u20;
    input vccpint_n16;
    input vccpint_p17;
    input vccpint_r18;
    input vccpint_t17;
    input vccpint_t19;
    input vccpint_u18;
    output vccpll;
    output vn_0;
    output vp_0;
    output vrefn_0;
    output vrefp_0;


    initial
        begin
        end

endmodule
