-- generated by newgenasym Tue Aug 04 13:46:53 2009

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity sem_sc4215hsetrt is
    port (    
	EN:        INOUT  STD_LOGIC;    
	FB:        INOUT  STD_LOGIC;    
	GND:       IN     STD_LOGIC;    
	NC:        INOUT  STD_LOGIC_VECTOR (2 DOWNTO 0);    
	THERMALPAD: IN     STD_LOGIC;    
	VIN:       INOUT  STD_LOGIC;    
	VO:        INOUT  STD_LOGIC);
end sem_sc4215hsetrt;
