-- generated by newgenasym Sat Sep 26 15:55:00 2015

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity c_s is
    port (    
	A0:        INOUT  STD_LOGIC;    
	B0:        INOUT  STD_LOGIC);
end c_s;
