-- generated by newgenasym Mon Jul 04 14:52:25 2022

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity r_short is
    port (    
	\1\:       INOUT  STD_LOGIC;    
	\2\:       INOUT  STD_LOGIC);
end r_short;
