// generated by newgenasym  Mon May 16 14:25:59 2022


module adi_ad9739a (\cs# , \dacclk* , dacclk_p, \db0_0* , db0_0_p, \db0_1* , \db0_10* ,
        db0_10_p, \db0_11* , db0_11_p, \db0_12* , db0_12_p, \db0_13* ,
        db0_13_p, db0_1_p, \db0_2* , db0_2_p, \db0_3* , db0_3_p, \db0_4* ,
        db0_4_p, \db0_5* , db0_5_p, \db0_6* , db0_6_p, \db0_7* , db0_7_p,
        \db0_8* , db0_8_p, \db0_9* , db0_9_p, \db1_0* , db1_0_p, \db1_1* ,
        \db1_10* , db1_10_p, \db1_11* , db1_11_p, \db1_12* , db1_12_p,
        \db1_13* , db1_13_p, db1_1_p, \db1_2* , db1_2_p, \db1_3* ,
        db1_3_p, \db1_4* , db1_4_p, \db1_5* , db1_5_p, \db1_6* , db1_6_p,
        \db1_7* , db1_7_p, \db1_8* , db1_8_p, \db1_9* , db1_9_p, \dci* ,
        dci_p, \dco* , dco_p, i120, ioutn, ioutp, irq, nc, reset, sclk,
        sdio, sdo, vdd, vdd33, vdda, vddc, vref, vss, vssa,
        vssa_shield, vssc);
    inout \cs# ;
    inout \dacclk* ;
    inout dacclk_p;
    inout \db0_0* ;
    inout db0_0_p;
    inout \db0_1* ;
    inout \db0_10* ;
    inout db0_10_p;
    inout \db0_11* ;
    inout db0_11_p;
    inout \db0_12* ;
    inout db0_12_p;
    inout \db0_13* ;
    inout db0_13_p;
    inout db0_1_p;
    inout \db0_2* ;
    inout db0_2_p;
    inout \db0_3* ;
    inout db0_3_p;
    inout \db0_4* ;
    inout db0_4_p;
    inout \db0_5* ;
    inout db0_5_p;
    inout \db0_6* ;
    inout db0_6_p;
    inout \db0_7* ;
    inout db0_7_p;
    inout \db0_8* ;
    inout db0_8_p;
    inout \db0_9* ;
    inout db0_9_p;
    inout \db1_0* ;
    inout db1_0_p;
    inout \db1_1* ;
    inout \db1_10* ;
    inout db1_10_p;
    inout \db1_11* ;
    inout db1_11_p;
    inout \db1_12* ;
    inout db1_12_p;
    inout \db1_13* ;
    inout db1_13_p;
    inout db1_1_p;
    inout \db1_2* ;
    inout db1_2_p;
    inout \db1_3* ;
    inout db1_3_p;
    inout \db1_4* ;
    inout db1_4_p;
    inout \db1_5* ;
    inout db1_5_p;
    inout \db1_6* ;
    inout db1_6_p;
    inout \db1_7* ;
    inout db1_7_p;
    inout \db1_8* ;
    inout db1_8_p;
    inout \db1_9* ;
    inout db1_9_p;
    inout \dci* ;
    inout dci_p;
    inout \dco* ;
    inout dco_p;
    inout i120;
    inout [3:0] ioutn;
    inout [3:0] ioutp;
    inout irq;
    inout [5:0] nc;
    inout reset;
    inout sclk;
    inout sdio;
    inout sdo;
    inout [5:0] vdd;
    inout [3:0] vdd33;
    inout [7:0] vdda;
    inout [7:0] vddc;
    inout vref;
    inout [9:0] vss;
    inout [7:0] vssa;
    inout [17:0] vssa_shield;
    inout [13:0] vssc;


    initial
        begin
        end

endmodule
