-- generated by newgenasym Wed Oct 24 15:35:30 2018

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity will_esd5304d is
    port (    
	GND:       INOUT  STD_LOGIC;    
	IN1:       INOUT  STD_LOGIC;    
	IN2:       INOUT  STD_LOGIC;    
	IN3:       INOUT  STD_LOGIC;    
	IN4:       INOUT  STD_LOGIC;    
	OUT1:      INOUT  STD_LOGIC;    
	OUT2:      INOUT  STD_LOGIC;    
	OUT3:      INOUT  STD_LOGIC;    
	OUT4:      INOUT  STD_LOGIC);
end will_esd5304d;
