// generated by newgenasym  Mon Oct 21 14:20:38 2019


module mur_sf1186b_3 (gnd_1, gnd_3, gnd_4, gnd_6, \input , \output );
    inout gnd_1;
    inout gnd_3;
    inout gnd_4;
    inout gnd_6;
    inout \input ;
    inout \output ;


    initial
        begin
        end

endmodule
