// generated by newgenasym  Tue Oct 30 20:00:54 2018


module xilinx_spiflash_8p (\cs# , epad, \hold#_io3 , sck, si_io0, so_io1, vcc, vss, \wp#_io2 );
    input \cs# ;
    inout epad;
    output \hold#_io3 ;
    output sck;
    output si_io0;
    input so_io1;
    output vcc;
    input vss;
    input \wp#_io2 ;


    initial
        begin
        end

endmodule
